export {
	COMPOSE_PROTOCOL_VERSION,
	type ComposeAddCaptionOperation,
	type ComposeAddFilterLayerOperation,
	type ComposeAddSoundEffectOperation,
	type ComposeAddStickerOperation,
	type ComposeAddTextOverlayOperation,
	type ComposeAssetLicense,
	type ComposeAssetReference,
	type ComposeAssetType,
	type ComposeBasePatchOperation,
	type ComposeCanvasSize,
	type ComposeFilterStep,
	type ComposeInsertMediaClipOperation,
	type ComposeIntent,
	type ComposeIntentKind,
	type ComposeJob,
	type ComposeJobError,
	type ComposeJobErrorCategory,
	type ComposeJobStatus,
	type ComposePatch,
	type ComposePatchMode,
	type ComposePatchOperation,
	type ComposePatchOperationKind,
	type ComposePatchSource,
	type ComposeProjectRecord,
	type ComposeProjectRecordJob,
	type ComposeProjectRecordPatch,
	type ComposeProjectRecordSnapshot,
	type ComposeProtocolVersion,
	type ComposeProvider,
	type ComposeSetMediaFilterStackOperation,
	type ComposeSnapshot,
	type ComposeSnapshotBeat,
	type ComposeSnapshotCapabilities,
	type ComposeSnapshotCaption,
	type ComposeSnapshotMedia,
	type ComposeSnapshotMediaKind,
	type ComposeSnapshotProject,
	type ComposeSnapshotShot,
	type ComposeUpdateMediaZoomOperation,
	type ComposeUpsertTransitionOperation,
} from "./compose-types.js";
export {
	computeComposeSourceFingerprint,
	type ComposeFingerprintInput,
} from "./compose-fingerprint.js";
export {
	COMPOSE_MAIN_VIDEO_TRACK_ROLE,
	hasComposeValidationErrors,
	validateComposeJob,
	validateComposePatch,
	validateComposeSnapshot,
	type ComposeValidationIssue,
	type ComposeValidationIssueCode,
	type ComposeValidationSeverity,
} from "./compose-validation.js";
export {
	countComposeOperations,
	mergeComposePatches,
} from "./compose-patch-merge.js";
export {
	composeIssueFromSmartPackaging,
	composePatchFromSmartPackaging,
	composeSnapshotFromSmartPackaging,
} from "./smart-packaging-adapter.js";
