import type { EffectMotionChannel } from "@qcut/editor-core";
import type { EffectPreset } from "@/types/effects";
import type {
	VisualEffectCatalogEntry,
	VisualEffectCategoryId,
} from "./effect-catalog-types";

function createMotionCatalogEntry({
	id,
	name,
	localizedName,
	description,
	localizedDescription,
	category,
	icon,
	channels,
	tags,
	releasedAt,
	popularityScore,
}: {
	id: string;
	name: string;
	localizedName: string;
	description: string;
	localizedDescription: string;
	category: VisualEffectCategoryId;
	icon: string;
	channels: EffectMotionChannel[];
	tags: readonly string[];
	releasedAt: string;
	popularityScore: number;
}): VisualEffectCatalogEntry {
	const preset: EffectPreset = {
		id,
		name,
		description,
		category: category === "camera" ? "cinematic" : "distortion",
		icon,
		parameters: {},
		effectType: "motion",
		renderProgram: {
			version: 1,
			stages: [{ kind: "motion", intensity: 1, channels }],
		},
	};

	return {
		preset,
		assetVersion: 1,
		localizedName,
		localizedDescription,
		family: "visual",
		category,
		tags,
		releasedAt,
		popularityScore,
		publication: "published",
		render: {
			kind: "motion",
			previewBackend: "canvas",
			exportBackend: "ffmpeg-filter-complex",
			parity: "verified",
		},
	};
}

export const MOTION_EFFECT_CATALOG = [
	createMotionCatalogEntry({
		id: "dynamic-camera-shake",
		name: "Camera Shake",
		localizedName: "震动镜头",
		description: "Fast positional shake with a restrained rotational wobble.",
		localizedDescription: "快速位置震动，并带有轻微旋转摆动。",
		category: "dynamic",
		icon: "SH",
		channels: [
			{ property: "x", waveform: "sine", amplitude: 0.012, frequencyHz: 7.3 },
			{
				property: "y",
				waveform: "cosine",
				amplitude: 0.01,
				frequencyHz: 8.1,
			},
			{
				property: "rotation",
				waveform: "sine",
				amplitude: 0.7,
				frequencyHz: 6.2,
			},
		],
		tags: ["shake", "impact", "dynamic"],
		releasedAt: "2026-07-18T01:00:00.000Z",
		popularityScore: 92,
	}),
	createMotionCatalogEntry({
		id: "dynamic-rhythm-pulse",
		name: "Rhythm Pulse",
		localizedName: "节奏脉冲",
		description: "A steady scale pulse for rhythmic edits.",
		localizedDescription: "适合节奏剪辑的稳定缩放脉冲。",
		category: "dynamic",
		icon: "PU",
		channels: [
			{
				property: "scale",
				waveform: "sine",
				amplitude: 0.06,
				frequencyHz: 2,
			},
		],
		tags: ["pulse", "rhythm", "scale"],
		releasedAt: "2026-07-18T01:01:00.000Z",
		popularityScore: 88,
	}),
	createMotionCatalogEntry({
		id: "dynamic-elastic-bounce",
		name: "Elastic Bounce",
		localizedName: "弹性跳动",
		description: "Vertical bounce paired with a subtle elastic scale change.",
		localizedDescription: "垂直跳动并配合轻微弹性缩放。",
		category: "dynamic",
		icon: "BO",
		channels: [
			{
				property: "y",
				waveform: "cosine",
				amplitude: 0.025,
				frequencyHz: 1.5,
			},
			{
				property: "scale",
				waveform: "cosine",
				amplitude: -0.025,
				frequencyHz: 1.5,
			},
		],
		tags: ["bounce", "elastic", "dynamic"],
		releasedAt: "2026-07-18T01:02:00.000Z",
		popularityScore: 84,
	}),
	createMotionCatalogEntry({
		id: "camera-push-in",
		name: "Push In",
		localizedName: "缓慢推进",
		description: "A continuous forward camera push across the clip.",
		localizedDescription: "在整个片段中持续缓慢推进镜头。",
		category: "camera",
		icon: "PI",
		channels: [{ property: "scale", waveform: "linear", amplitude: 0.15 }],
		tags: ["push", "zoom", "camera"],
		releasedAt: "2026-07-18T01:03:00.000Z",
		popularityScore: 90,
	}),
	createMotionCatalogEntry({
		id: "camera-cinematic-drift",
		name: "Cinematic Drift",
		localizedName: "电影漂移",
		description: "Slow independent horizontal and vertical camera drift.",
		localizedDescription: "缓慢且独立的水平、垂直镜头漂移。",
		category: "camera",
		icon: "DR",
		channels: [
			{
				property: "x",
				waveform: "sine",
				amplitude: 0.025,
				frequencyHz: 0.12,
			},
			{
				property: "y",
				waveform: "cosine",
				amplitude: 0.018,
				frequencyHz: 0.16,
			},
		],
		tags: ["drift", "cinematic", "camera"],
		releasedAt: "2026-07-18T01:04:00.000Z",
		popularityScore: 86,
	}),
	createMotionCatalogEntry({
		id: "camera-handheld",
		name: "Handheld",
		localizedName: "手持镜头",
		description: "Natural low-amplitude handheld camera movement.",
		localizedDescription: "自然、低幅度的手持镜头运动。",
		category: "camera",
		icon: "HH",
		channels: [
			{
				property: "x",
				waveform: "sine",
				amplitude: 0.006,
				frequencyHz: 3.1,
			},
			{
				property: "y",
				waveform: "cosine",
				amplitude: 0.006,
				frequencyHz: 2.7,
			},
			{
				property: "rotation",
				waveform: "sine",
				amplitude: 0.35,
				frequencyHz: 2.2,
			},
		],
		tags: ["handheld", "camera", "natural"],
		releasedAt: "2026-07-18T01:05:00.000Z",
		popularityScore: 82,
	}),
	createMotionCatalogEntry({
		id: "camera-rotate-zoom",
		name: "Rotate Zoom",
		localizedName: "旋转变焦",
		description: "A slow rotating zoom that eases in and out.",
		localizedDescription: "缓慢旋转并配合推拉变焦，来回渐入渐出。",
		category: "camera",
		icon: "RZ",
		channels: [
			{
				property: "scale",
				waveform: "sine",
				amplitude: 0.06,
				frequencyHz: 0.15,
			},
			{
				property: "rotation",
				waveform: "sine",
				amplitude: 1.6,
				frequencyHz: 0.15,
			},
		],
		tags: ["rotate", "zoom", "camera"],
		releasedAt: "2026-07-20T01:06:00.000Z",
		popularityScore: 85,
	}),
	createMotionCatalogEntry({
		id: "camera-push-pull",
		name: "Push Pull",
		localizedName: "来回推拉",
		description: "A pronounced ping-pong zoom in and back out.",
		localizedDescription: "明显的来回推拉变焦,持续推近再拉远。",
		category: "camera",
		icon: "PP",
		channels: [
			{
				property: "scale",
				waveform: "sine",
				amplitude: 0.12,
				frequencyHz: 0.2,
			},
		],
		tags: ["push", "pull", "zoom", "camera"],
		releasedAt: "2026-07-20T01:07:00.000Z",
		popularityScore: 88,
	}),
	createMotionCatalogEntry({
		id: "camera-sway",
		name: "Sway",
		localizedName: "摇晃运镜",
		description: "A rhythmic horizontal sway with a matching tilt.",
		localizedDescription: "有节奏的左右摇晃,并配合轻微倾斜。",
		category: "camera",
		icon: "SW",
		channels: [
			{ property: "x", waveform: "sine", amplitude: 0.022, frequencyHz: 0.5 },
			{
				property: "rotation",
				waveform: "cosine",
				amplitude: 1,
				frequencyHz: 0.5,
			},
		],
		tags: ["sway", "swing", "camera"],
		releasedAt: "2026-07-20T01:08:00.000Z",
		popularityScore: 83,
	}),
	createMotionCatalogEntry({
		id: "camera-follow",
		name: "Follow",
		localizedName: "跟随运镜",
		description: "A slow tracking drift that follows the action.",
		localizedDescription: "缓慢的跟随漂移,如镜头追随主体。",
		category: "camera",
		icon: "FL",
		channels: [
			{ property: "x", waveform: "sine", amplitude: 0.03, frequencyHz: 0.1 },
			{
				property: "y",
				waveform: "cosine",
				amplitude: 0.018,
				frequencyHz: 0.08,
			},
			{
				property: "scale",
				waveform: "sine",
				amplitude: 0.02,
				frequencyHz: 0.1,
			},
		],
		tags: ["follow", "track", "camera"],
		releasedAt: "2026-07-20T01:09:00.000Z",
		popularityScore: 84,
	}),
	createMotionCatalogEntry({
		id: "dynamic-heartbeat",
		name: "Heartbeat",
		localizedName: "心跳",
		description: "A rhythmic heartbeat scale pulse.",
		localizedDescription: "有节奏的心跳式缩放脉冲。",
		category: "dynamic",
		icon: "HB",
		channels: [
			{
				property: "scale",
				waveform: "sine",
				amplitude: 0.05,
				frequencyHz: 1.3,
			},
		],
		tags: ["heartbeat", "pulse", "dynamic"],
		releasedAt: "2026-07-20T01:10:00.000Z",
		popularityScore: 86,
	}),
	createMotionCatalogEntry({
		id: "dynamic-flash-black",
		name: "Flash Black",
		localizedName: "微震闪黑",
		description: "A jittery shake with a rhythmic dip to black.",
		localizedDescription: "轻微抖动并配合有节奏的闪黑。",
		category: "dynamic",
		icon: "FB",
		channels: [
			{ property: "x", waveform: "sine", amplitude: 0.008, frequencyHz: 9 },
			{ property: "y", waveform: "cosine", amplitude: 0.008, frequencyHz: 10 },
			{
				property: "opacity",
				waveform: "sine",
				amplitude: 0.55,
				frequencyHz: 3,
			},
		],
		tags: ["flash", "black", "strobe", "dynamic"],
		releasedAt: "2026-07-20T01:11:00.000Z",
		popularityScore: 85,
	}),
	createMotionCatalogEntry({
		id: "dynamic-hard-shake",
		name: "Hard Shake",
		localizedName: "抖动",
		description: "A strong, fast full-frame shake.",
		localizedDescription: "强烈快速的整屏抖动。",
		category: "dynamic",
		icon: "HS",
		channels: [
			{ property: "x", waveform: "sine", amplitude: 0.022, frequencyHz: 11 },
			{ property: "y", waveform: "cosine", amplitude: 0.02, frequencyHz: 12.5 },
			{
				property: "rotation",
				waveform: "sine",
				amplitude: 1.2,
				frequencyHz: 9,
			},
		],
		tags: ["shake", "jitter", "dynamic"],
		releasedAt: "2026-07-20T01:12:00.000Z",
		popularityScore: 87,
	}),
	createMotionCatalogEntry({
		id: "dynamic-impact",
		name: "Impact",
		localizedName: "冲击",
		description: "A punchy zoom impact that recoils and settles.",
		localizedDescription: "有力的冲击式缩放,快速推近再回落。",
		category: "dynamic",
		icon: "IM",
		channels: [
			{
				property: "scale",
				waveform: "sine",
				amplitude: 0.14,
				frequencyHz: 0.9,
			},
			{ property: "y", waveform: "cosine", amplitude: 0.02, frequencyHz: 0.9 },
		],
		tags: ["impact", "punch", "zoom", "dynamic"],
		releasedAt: "2026-07-20T01:13:00.000Z",
		popularityScore: 84,
	}),
	createMotionCatalogEntry({
		id: "dynamic-subtle-shake",
		name: "Subtle Shake",
		localizedName: "轻微抖动",
		description: "A gentle low-amplitude jitter.",
		localizedDescription: "轻柔低幅度的抖动。",
		category: "dynamic",
		icon: "SS",
		channels: [
			{ property: "x", waveform: "sine", amplitude: 0.005, frequencyHz: 6 },
			{ property: "y", waveform: "cosine", amplitude: 0.004, frequencyHz: 6.7 },
		],
		tags: ["shake", "subtle", "dynamic"],
		releasedAt: "2026-07-20T01:14:00.000Z",
		popularityScore: 80,
	}),
	createMotionCatalogEntry({
		id: "dynamic-rhythm-swing",
		name: "Rhythm Swing",
		localizedName: "节奏摇摆",
		description: "A musical left-right swing with a matching tilt.",
		localizedDescription: "跟随节拍的左右摇摆并配合倾斜。",
		category: "dynamic",
		icon: "RS",
		channels: [
			{ property: "x", waveform: "sine", amplitude: 0.03, frequencyHz: 1 },
			{
				property: "rotation",
				waveform: "sine",
				amplitude: 2,
				frequencyHz: 1,
			},
		],
		tags: ["swing", "rhythm", "dynamic"],
		releasedAt: "2026-07-20T01:15:00.000Z",
		popularityScore: 83,
	}),
	createMotionCatalogEntry({
		id: "dynamic-quad-shake",
		name: "Quad Shake",
		localizedName: "四方震褫",
		description: "A sharp four-direction jolt.",
		localizedDescription: "上下左右四个方向的锐利震动。",
		category: "dynamic",
		icon: "QS",
		channels: [
			{ property: "x", waveform: "sine", amplitude: 0.02, frequencyHz: 8 },
			{ property: "y", waveform: "sine", amplitude: 0.02, frequencyHz: 8 },
		],
		tags: ["shake", "quad", "dynamic"],
		releasedAt: "2026-07-20T01:16:00.000Z",
		popularityScore: 82,
	}),
	createMotionCatalogEntry({
		id: "dynamic-step-push",
		name: "Step Push",
		localizedName: "逐步推进",
		description: "A stepped zoom that ratchets inward in beats.",
		localizedDescription: "分段推进的阶梯式变焦。",
		category: "dynamic",
		icon: "SP",
		channels: [
			{ property: "scale", waveform: "linear", amplitude: 0.12 },
			{
				property: "scale",
				waveform: "sine",
				amplitude: 0.02,
				frequencyHz: 2,
			},
		],
		tags: ["push", "step", "zoom", "dynamic"],
		releasedAt: "2026-07-20T01:17:00.000Z",
		popularityScore: 81,
	}),
	createMotionCatalogEntry({
		id: "dynamic-flash-pulse",
		name: "Flash Pulse",
		localizedName: "闪动脉冲",
		description: "A rhythmic opacity flash with a light scale pop.",
		localizedDescription: "有节奏的闪烁脉冲并配合轻微缩放。",
		category: "dynamic",
		icon: "FP",
		channels: [
			{
				property: "opacity",
				waveform: "sine",
				amplitude: 0.4,
				frequencyHz: 4,
			},
			{ property: "scale", waveform: "sine", amplitude: 0.03, frequencyHz: 4 },
		],
		tags: ["flash", "pulse", "strobe", "dynamic"],
		releasedAt: "2026-07-20T01:18:00.000Z",
		popularityScore: 84,
	}),
] as const satisfies readonly VisualEffectCatalogEntry[];
