import type { EffectPreset } from "@/types/effects";

export const EFFECT_PRESETS = [
	{
		id: "brightness-increase",
		name: "Brighten",
		description: "Lift exposure for a brighter image.",
		category: "basic",
		icon: "+",
		parameters: { brightness: 20 },
	},
	{
		id: "brightness-decrease",
		name: "Darken",
		description: "Lower exposure for a darker image.",
		category: "basic",
		icon: "-",
		parameters: { brightness: -20 },
	},
	{
		id: "contrast-high",
		name: "High Contrast",
		description: "Strengthen separation between highlights and shadows.",
		category: "basic",
		icon: "C+",
		parameters: { contrast: 30 },
	},
	{
		id: "contrast-soft",
		name: "Soft Contrast",
		description: "Compress contrast for a softer tonal range.",
		category: "basic",
		icon: "C-",
		parameters: { contrast: -20 },
	},
	{
		id: "saturation-boost",
		name: "Vibrant",
		description: "Boost color saturation without changing exposure.",
		category: "color",
		icon: "V",
		parameters: { saturation: 40 },
	},
	{
		id: "desaturate",
		name: "Muted",
		description: "Reduce saturation for restrained color.",
		category: "color",
		icon: "M",
		parameters: { saturation: -35 },
	},
	{
		id: "warm-filter",
		name: "Warm Tone",
		description: "Shift hues warmer and gently lift saturation.",
		category: "color",
		icon: "W",
		parameters: { hue: -10, saturation: 18, brightness: 5 },
	},
	{
		id: "cool-filter",
		name: "Cool Tone",
		description: "Shift hues cooler with a crisp tonal lift.",
		category: "color",
		icon: "K",
		parameters: { hue: 12, saturation: 10, contrast: 5 },
	},
	{
		id: "hue-shift",
		name: "Hue Shift",
		description: "Rotate the palette for a stylized color treatment.",
		category: "color",
		icon: "H",
		parameters: { hue: 42 },
	},
	{
		id: "sepia",
		name: "Sepia",
		description: "Apply a warm photographic sepia matrix.",
		category: "vintage",
		icon: "S",
		parameters: { sepia: 80 },
	},
	{
		id: "faded-film",
		name: "Faded Film",
		description: "Blend a restrained sepia cast with faded color and contrast.",
		category: "vintage",
		icon: "FF",
		parameters: {
			brightness: 6,
			contrast: -8,
			saturation: -20,
			sepia: 35,
		},
	},
	{
		id: "grayscale",
		name: "Black & White",
		description: "Remove color for a monochrome image.",
		category: "artistic",
		icon: "BW",
		parameters: { grayscale: 100 },
	},
	{
		id: "blur-soft",
		name: "Soft Blur",
		description: "Apply a gentle full-frame blur.",
		category: "artistic",
		icon: "B",
		parameters: { blur: 2 },
	},
	{
		id: "dreamy",
		name: "Dreamy",
		description: "Soften detail while lifting light and color.",
		category: "cinematic",
		icon: "D",
		parameters: {
			brightness: 12,
			contrast: -10,
			saturation: 12,
			blur: 1.2,
		},
	},
	{
		id: "dramatic",
		name: "Dramatic",
		description: "Deepen contrast and restrain color for impact.",
		category: "cinematic",
		icon: "DR",
		parameters: { brightness: -8, contrast: 35, saturation: -15 },
	},
	{
		id: "invert",
		name: "Invert",
		description: "Invert every color channel for a negative image.",
		category: "artistic",
		icon: "I",
		parameters: { invert: 100 },
	},
] as const satisfies readonly EffectPreset[];

export type EffectPresetId = (typeof EFFECT_PRESETS)[number]["id"];
