import type { EffectParameters } from "@qcut/editor-core";
import type { EffectPreset } from "@/types/effects";
import type {
	VisualEffectCatalogEntry,
	VisualEffectCategoryId,
} from "./effect-catalog-types";

function createFilterCatalogEntry({
	id,
	name,
	localizedName,
	description,
	localizedDescription,
	category,
	icon,
	parameters,
	tags,
	releasedAt,
	popularityScore,
}: {
	id: string;
	name: string;
	localizedName: string;
	description: string;
	localizedDescription: string;
	category: VisualEffectCategoryId;
	icon: string;
	parameters: EffectParameters;
	tags: readonly string[];
	releasedAt: string;
	popularityScore: number;
}): VisualEffectCatalogEntry {
	const preset: EffectPreset = {
		id,
		name,
		description,
		category: "basic",
		icon,
		parameters,
		renderProgram: { version: 1, stages: [{ kind: "filter" }] },
	};

	return {
		preset,
		assetVersion: 1,
		localizedName,
		localizedDescription,
		family: "visual",
		category,
		tags,
		releasedAt,
		popularityScore,
		publication: "published",
		render: {
			kind: "filter",
			previewBackend: "css-filter",
			exportBackend: "ffmpeg-filter",
			parity: "verified",
		},
	};
}

export const FILTER_EFFECT_CATALOG = [
	createFilterCatalogEntry({
		id: "basic-clean-bright",
		name: "Clean Bright",
		localizedName: "清透提亮",
		description: "A restrained lift in exposure, contrast, and color.",
		localizedDescription: "轻微提升曝光、对比度与色彩。",
		category: "basic",
		icon: "CB",
		parameters: { brightness: 8, contrast: 10, saturation: 5 },
		tags: ["clean", "bright", "basic"],
		releasedAt: "2026-07-18T02:00:00.000Z",
		popularityScore: 78,
	}),
	createFilterCatalogEntry({
		id: "basic-soft-focus",
		name: "Soft Focus",
		localizedName: "柔焦",
		description: "Gently softens detail while retaining overall clarity.",
		localizedDescription: "轻柔弱化细节，同时保留整体清晰感。",
		category: "basic",
		icon: "SF",
		parameters: { brightness: 5, contrast: -5, blur: 0.8 },
		tags: ["soft", "focus", "basic"],
		releasedAt: "2026-07-18T02:01:00.000Z",
		popularityScore: 74,
	}),
	createFilterCatalogEntry({
		id: "basic-crisp-detail",
		name: "Crisp Detail",
		localizedName: "清晰细节",
		description: "Adds clean local contrast and a small color lift.",
		localizedDescription: "增强清晰对比并轻微提升色彩。",
		category: "basic",
		icon: "CD",
		parameters: { contrast: 18, saturation: 8, brightness: 2 },
		tags: ["crisp", "detail", "clarity"],
		releasedAt: "2026-07-18T02:02:00.000Z",
		popularityScore: 76,
	}),
	createFilterCatalogEntry({
		id: "atmosphere-soft-mist",
		name: "Soft Mist",
		localizedName: "柔雾",
		description: "Low-contrast mist with muted color and softened detail.",
		localizedDescription: "低对比柔雾，降低色彩并柔化细节。",
		category: "atmosphere",
		icon: "MI",
		parameters: { brightness: 12, contrast: -18, saturation: -20, blur: 0.6 },
		tags: ["mist", "soft", "atmosphere"],
		releasedAt: "2026-07-18T02:03:00.000Z",
		popularityScore: 80,
	}),
	createFilterCatalogEntry({
		id: "atmosphere-night-mood",
		name: "Night Mood",
		localizedName: "夜色氛围",
		description: "Darkens the frame with cooler restrained color.",
		localizedDescription: "压暗画面，并加入克制的冷色氛围。",
		category: "atmosphere",
		icon: "NM",
		parameters: { brightness: -15, contrast: 15, saturation: -25, hue: 15 },
		tags: ["night", "dark", "mood"],
		releasedAt: "2026-07-18T02:04:00.000Z",
		popularityScore: 83,
	}),
	createFilterCatalogEntry({
		id: "atmosphere-golden-haze",
		name: "Golden Haze",
		localizedName: "金色薄雾",
		description: "A warm faded haze with a restrained sepia cast.",
		localizedDescription: "温暖褪色的薄雾，并带有轻微棕褐色调。",
		category: "atmosphere",
		icon: "GH",
		parameters: { brightness: 8, contrast: -10, saturation: 10, sepia: 18 },
		tags: ["golden", "haze", "warm"],
		releasedAt: "2026-07-18T02:05:00.000Z",
		popularityScore: 81,
	}),
	createFilterCatalogEntry({
		id: "trendy-neon-pop",
		name: "Neon Pop",
		localizedName: "霓虹高彩",
		description: "High contrast, vivid color, and a small hue shift.",
		localizedDescription: "高对比、高饱和，并加入轻微色相偏移。",
		category: "trendy",
		icon: "NP",
		parameters: { contrast: 25, saturation: 45, hue: 8 },
		tags: ["neon", "vivid", "trendy"],
		releasedAt: "2026-07-18T02:06:00.000Z",
		popularityScore: 87,
	}),
	createFilterCatalogEntry({
		id: "trendy-ice-chrome",
		name: "Ice Chrome",
		localizedName: "冰感铬色",
		description: "Bright metallic contrast with a cool hue rotation.",
		localizedDescription: "明亮金属对比，并加入冷色色相偏移。",
		category: "trendy",
		icon: "IC",
		parameters: { brightness: 8, contrast: 28, saturation: -10, hue: 25 },
		tags: ["ice", "chrome", "cool"],
		releasedAt: "2026-07-18T02:07:00.000Z",
		popularityScore: 79,
	}),
	createFilterCatalogEntry({
		id: "trendy-candy-shift",
		name: "Candy Shift",
		localizedName: "糖果变色",
		description: "A bright candy palette with a pronounced hue shift.",
		localizedDescription: "明亮糖果色，并带有明显色相偏移。",
		category: "trendy",
		icon: "CS",
		parameters: { brightness: 6, saturation: 35, hue: 55 },
		tags: ["candy", "color", "trendy"],
		releasedAt: "2026-07-18T02:08:00.000Z",
		popularityScore: 85,
	}),
	createFilterCatalogEntry({
		id: "basic-vignette",
		name: "Vignette",
		localizedName: "暗角",
		description: "Darkens the corners to draw the eye toward the center.",
		localizedDescription: "压暗四角，将视线引向画面中心。",
		category: "basic",
		icon: "VG",
		parameters: { vignette: 55 },
		tags: ["vignette", "corners", "basic"],
		releasedAt: "2026-07-20T02:00:00.000Z",
		popularityScore: 83,
	}),
	createFilterCatalogEntry({
		id: "basic-sharpen",
		name: "Sharpen",
		localizedName: "画质清晰",
		description: "Enhances edge detail for a crisper image.",
		localizedDescription: "增强边缘细节，让画面更清晰锐利。",
		category: "basic",
		icon: "SP",
		parameters: { sharpen: 60, contrast: 4 },
		tags: ["sharpen", "clarity", "detail"],
		releasedAt: "2026-07-20T02:01:00.000Z",
		popularityScore: 82,
	}),
	createFilterCatalogEntry({
		id: "basic-blur",
		name: "Blur",
		localizedName: "模糊",
		description: "A clean overall softening of the frame.",
		localizedDescription: "对整个画面做干净的整体柔化。",
		category: "basic",
		icon: "BL",
		parameters: { blur: 6 },
		tags: ["blur", "soft", "basic"],
		releasedAt: "2026-07-20T02:02:00.000Z",
		popularityScore: 77,
	}),
	createFilterCatalogEntry({
		id: "dynamic-mermaid",
		name: "Mermaid",
		localizedName: "人鱼滤镜",
		description: "A dreamy aqua-teal grade with lifted saturation.",
		localizedDescription: "梦幻的青碧色调,并提升饱和度。",
		category: "dynamic",
		icon: "ME",
		parameters: { hue: 155, saturation: 28, contrast: 8, brightness: 4 },
		tags: ["mermaid", "aqua", "teal", "dynamic"],
		releasedAt: "2026-07-20T02:03:00.000Z",
		popularityScore: 83,
	}),
	createFilterCatalogEntry({
		id: "atmosphere-cinematic",
		name: "Cinematic",
		localizedName: "电影氛围",
		description: "A moody cinematic grade with deep contrast.",
		localizedDescription: "富有电影感的深沉调色氛围。",
		category: "atmosphere",
		icon: "CN",
		parameters: { contrast: 22, saturation: -8, sepia: 12, brightness: -5 },
		tags: ["cinematic", "movie", "mood", "atmosphere"],
		releasedAt: "2026-07-20T02:04:00.000Z",
		popularityScore: 86,
	}),
	createFilterCatalogEntry({
		id: "light-dreamy-glow",
		name: "Dreamy Glow",
		localizedName: "梦幻辉光",
		description: "A soft luminous bloom with lifted brightness and color.",
		localizedDescription: "柔和明亮的梦幻辉光，提升亮度与色彩。",
		category: "light",
		icon: "DG",
		parameters: { brightness: 18, blur: 22, saturation: 25 },
		tags: ["dreamy", "glow", "bloom", "light"],
		releasedAt: "2026-07-27T00:00:00.000Z",
		popularityScore: 93,
	}),
	createFilterCatalogEntry({
		id: "atmosphere-memory-flash",
		name: "Memory Flash",
		localizedName: "回忆检索",
		description: "A faded sepia flashback with soft focus and dark corners.",
		localizedDescription: "泛黄褪色的回忆闪回，柔焦并压暗四角。",
		category: "atmosphere",
		icon: "MF",
		parameters: { sepia: 45, vignette: 40, blur: 12, contrast: -10 },
		tags: ["memory", "flashback", "sepia", "atmosphere"],
		releasedAt: "2026-07-27T00:00:00.000Z",
		popularityScore: 92,
	}),
	createFilterCatalogEntry({
		id: "trendy-summer-cool",
		name: "Summer Cool",
		localizedName: "夏日清凉",
		description: "Rotates warm tones into a refreshing cool-blue summer grade.",
		localizedDescription: "将暖色调旋转为清爽的夏日冷蓝色调。",
		category: "trendy",
		icon: "SC",
		parameters: { hue: 200, saturation: 20, brightness: 10 },
		tags: ["summer", "cool", "fresh", "trendy"],
		releasedAt: "2026-07-27T00:00:00.000Z",
		popularityScore: 91,
	}),
	createFilterCatalogEntry({
		id: "atmosphere-oil-blur",
		name: "Oil Blur",
		localizedName: "油画模糊",
		description: "A heavy painterly blur with rich saturated color.",
		localizedDescription: "浓重的油画感模糊，色彩饱满浓郁。",
		category: "atmosphere",
		icon: "OB",
		parameters: { blur: 35, saturation: 35, contrast: 15 },
		tags: ["oil", "painting", "blur", "atmosphere"],
		releasedAt: "2026-07-27T00:00:00.000Z",
		popularityScore: 78,
	}),
	createFilterCatalogEntry({
		id: "light-spotlight-stage",
		name: "Spotlight Stage",
		localizedName: "聚光灯",
		description: "A bright stage spotlight with deeply darkened surroundings.",
		localizedDescription: "舞台聚光灯效果，中心明亮、四周压暗。",
		category: "light",
		icon: "SL",
		parameters: { vignette: 85, brightness: 15 },
		tags: ["spotlight", "stage", "light"],
		releasedAt: "2026-07-27T00:00:00.000Z",
		popularityScore: 92,
	}),
	// Hand-written entry: pairs the vignette filter with a linear opacity
	// fade-out motion stage, which the single-stage factory cannot express.
	{
		preset: {
			id: "basic-curtain-close",
			name: "Curtain Close",
			description: "Darkened edges close in as the frame fades to black.",
			category: "basic",
			icon: "CC",
			parameters: { vignette: 100 },
			// A vignette that fades out: the motion stage only drives the fade, so
			// this stays a filter effect. Typing it as "motion" would also make it
			// the reset fallback for every legacy motion effect, since the filter
			// catalog is aggregated before the motion catalog.
			effectType: "filter",
			renderProgram: {
				version: 1,
				stages: [
					{ kind: "filter" },
					{
						kind: "motion",
						intensity: 1,
						channels: [
							{ property: "opacity", waveform: "linear", amplitude: -1 },
						],
					},
				],
			},
		},
		assetVersion: 1,
		localizedName: "闭幕",
		localizedDescription: "四周压暗收拢，画面逐渐淡出至黑。",
		family: "visual",
		category: "basic",
		tags: ["curtain", "close", "fade", "ending", "basic"],
		releasedAt: "2026-07-27T00:00:00.000Z",
		popularityScore: 74,
		publication: "published",
		render: {
			kind: "filter",
			previewBackend: "css-filter",
			exportBackend: "ffmpeg-filter-complex",
			parity: "verified",
		},
	},
] as const satisfies readonly VisualEffectCatalogEntry[];
