import type {
	EffectPersonTrackingRenderStage,
	EffectType,
} from "@qcut/editor-core";
import type { EffectPreset } from "@/types/effects";
import type { PersonEffectCatalogEntry } from "./effect-catalog-types";

function createPersonEffectEntry({
	id,
	name,
	localizedName,
	description,
	localizedDescription,
	treatment,
	stroke,
	intensity,
	vignette,
	echoVariant,
	tags,
	releasedAt,
	popularityScore,
}: {
	id: string;
	name: string;
	localizedName: string;
	description: string;
	localizedDescription: string;
	treatment: EffectPersonTrackingRenderStage["treatment"];
	stroke?: EffectPersonTrackingRenderStage["stroke"];
	intensity?: number;
	vignette?: boolean;
	echoVariant?: EffectPersonTrackingRenderStage["echoVariant"];
	tags: readonly string[];
	releasedAt: string;
	popularityScore: number;
}): PersonEffectCatalogEntry {
	const stage: EffectPersonTrackingRenderStage = {
		kind: "person-tracking",
		target: "person",
		treatment,
		fallback: "disable",
		...(stroke ? { stroke } : {}),
		...(intensity !== undefined ? { intensity } : {}),
		...(vignette ? { vignette } : {}),
		...(echoVariant ? { echoVariant } : {}),
	};
	const effectType: EffectType = "person-tracking";
	const preset: EffectPreset = {
		id,
		name,
		description,
		category: "artistic",
		icon: "PT",
		parameters: {},
		effectType,
		renderProgram: { version: 1, stages: [stage] },
		preview: "/images/filter-previews/glow-portrait.webp",
	};

	return {
		preset,
		assetVersion: 1,
		localizedName,
		localizedDescription,
		family: "person",
		category: "person",
		tags,
		releasedAt,
		popularityScore,
		publication: "published",
		render: {
			kind: "person-tracking",
			previewBackend: "canvas",
			exportBackend: "ffmpeg-filter-complex",
			parity: "verified",
		},
	};
}

export const PERSON_EFFECT_CATALOG = [
	createPersonEffectEntry({
		id: "person-neon-outline",
		name: "Person Outline",
		localizedName: "人物描边",
		description: "Tracks the subject with a clean cyan edge glow.",
		localizedDescription: "跟随人物轮廓生成清晰的青色发光描边。",
		treatment: "outline",
		tags: ["person", "portrait", "outline", "glow", "tracking"],
		releasedAt: "2026-07-18T01:20:00.000Z",
		popularityScore: 88,
	}),
	createPersonEffectEntry({
		id: "person-spotlight",
		name: "Person Spotlight",
		localizedName: "人物聚光",
		description: "Keeps the tracked person bright while lowering the scene.",
		localizedDescription: "保持人物明亮，同时压暗并弱化周围画面。",
		treatment: "spotlight",
		tags: ["person", "portrait", "spotlight", "focus", "tracking"],
		releasedAt: "2026-07-18T01:21:00.000Z",
		popularityScore: 91,
	}),
	createPersonEffectEntry({
		id: "person-background-blur",
		name: "Background Blur",
		localizedName: "背景虚化",
		description:
			"Preserves the tracked person over a softly blurred background.",
		localizedDescription: "保留清晰人物，并对人物以外的背景进行柔和虚化。",
		treatment: "background-blur",
		tags: ["person", "portrait", "background", "blur", "tracking"],
		releasedAt: "2026-07-18T01:22:00.000Z",
		popularityScore: 94,
	}),
	createPersonEffectEntry({
		id: "person-electric-outline",
		name: "Electric Outline",
		localizedName: "电光描边",
		description: "Electric flicker along the tracked silhouette.",
		localizedDescription: "沿人物轮廓闪烁的电光描边。",
		treatment: "outline",
		stroke: { style: "electric", color: "#7df9ff", width: 2, glow: 1.5 },
		tags: ["person", "outline", "electric", "tracking"],
		releasedAt: "2026-07-22T02:00:00.000Z",
		popularityScore: 90,
	}),
	createPersonEffectEntry({
		id: "person-electric-outline-2",
		name: "Electric Outline II",
		localizedName: "电光描边Ⅱ",
		description: "Thicker, violet electric edge with a stronger glow.",
		localizedDescription: "更粗更亮的紫电描边。",
		treatment: "outline",
		stroke: { style: "electric", color: "#b19bff", width: 3, glow: 2.4 },
		tags: ["person", "outline", "electric", "tracking"],
		releasedAt: "2026-07-22T02:00:00.000Z",
		popularityScore: 84,
	}),
	createPersonEffectEntry({
		id: "person-rainbow-edge",
		name: "Rainbow Edge",
		localizedName: "彩虹边缘",
		description: "Hue-cycling rainbow rim around the subject.",
		localizedDescription: "环绕人物的循环彩虹光边。",
		treatment: "outline",
		stroke: { style: "rainbow", color: "#ff4d4d", width: 2, glow: 1.2 },
		tags: ["person", "outline", "rainbow", "tracking"],
		releasedAt: "2026-07-22T02:00:00.000Z",
		popularityScore: 89,
	}),
	createPersonEffectEntry({
		id: "person-flow-outline",
		name: "Flow Outline",
		localizedName: "流光描边",
		description: "A light band sweeps along the silhouette.",
		localizedDescription: "流动光带沿轮廓扫过。",
		treatment: "outline",
		stroke: { style: "flow", color: "#ffd76a", width: 2, glow: 1.6 },
		tags: ["person", "outline", "flow", "tracking"],
		releasedAt: "2026-07-22T02:00:00.000Z",
		popularityScore: 87,
	}),
	createPersonEffectEntry({
		id: "person-crayon-outline",
		name: "Crayon Outline",
		localizedName: "彩色蜡笔描边",
		description: "Grainy hand-colored crayon edge.",
		localizedDescription: "蜡笔质感的粗颗粒描边。",
		treatment: "outline",
		stroke: { style: "crayon", color: "#ff8fb3", width: 3, glow: 0.5 },
		tags: ["person", "outline", "crayon", "tracking"],
		releasedAt: "2026-07-22T02:00:00.000Z",
		popularityScore: 80,
	}),
	createPersonEffectEntry({
		id: "person-handwritten-outline",
		name: "Handwritten Outline",
		localizedName: "手写描边",
		description: "Thin wobbling ink line, hand-drawn feel.",
		localizedDescription: "细而微颤的手写墨线描边。",
		treatment: "outline",
		stroke: { style: "handwritten", color: "#ffffff", width: 1, glow: 0.4 },
		tags: ["person", "outline", "handwritten", "tracking"],
		releasedAt: "2026-07-22T02:00:00.000Z",
		popularityScore: 82,
	}),
	createPersonEffectEntry({
		id: "person-shatter-edge",
		name: "Shatter Edge",
		localizedName: "碎闪边缘",
		description: "Broken dashes flash around the subject.",
		localizedDescription: "碎片化闪烁的轮廓光边。",
		treatment: "outline",
		stroke: { style: "shatter", color: "#9ae6ff", width: 2, glow: 1.0 },
		tags: ["person", "outline", "shatter", "tracking"],
		releasedAt: "2026-07-22T02:00:00.000Z",
		popularityScore: 83,
	}),
	createPersonEffectEntry({
		id: "person-neon-outline-2",
		name: "Neon Outline II",
		localizedName: "霓虹描边Ⅱ",
		description: "Wide neon glow with a bright core.",
		localizedDescription: "带亮芯的宽幅霓虹光晕描边。",
		treatment: "outline",
		stroke: { style: "neon", color: "#39ff14", width: 2, glow: 2.6 },
		tags: ["person", "outline", "neon", "tracking"],
		releasedAt: "2026-07-22T02:00:00.000Z",
		popularityScore: 86,
	}),
	createPersonEffectEntry({
		id: "person-highlight-moment",
		name: "Highlight Moment",
		localizedName: "高光时刻",
		description:
			"Strong spotlight that dims the whole scene around the subject.",
		localizedDescription: "强力聚光,大幅压暗人物以外的场景。",
		treatment: "spotlight",
		intensity: 1.6,
		tags: ["person", "focus", "spotlight", "tracking"],
		releasedAt: "2026-07-22T02:10:00.000Z",
		popularityScore: 92,
	}),
	createPersonEffectEntry({
		id: "person-highlight-solo",
		name: "Highlight Solo",
		localizedName: "高光人物",
		description: "Near-black surroundings keep only the subject lit.",
		localizedDescription: "背景近乎全黑,只保留人物高亮。",
		treatment: "spotlight",
		intensity: 2,
		tags: ["person", "focus", "spotlight", "tracking"],
		releasedAt: "2026-07-22T02:10:00.000Z",
		popularityScore: 88,
	}),
	createPersonEffectEntry({
		id: "person-vignette-focus",
		name: "Vignette Focus",
		localizedName: "暗角聚焦",
		description: "Spotlight with heavy darkened corners.",
		localizedDescription: "聚光加浓重暗角,视线聚焦人物。",
		treatment: "spotlight",
		intensity: 1.2,
		vignette: true,
		tags: ["person", "focus", "spotlight", "tracking"],
		releasedAt: "2026-07-22T02:10:00.000Z",
		popularityScore: 85,
	}),
	createPersonEffectEntry({
		id: "person-subject-blur",
		name: "Subject Blur",
		localizedName: "局部模糊",
		description: "Blurs the tracked person while the scene stays sharp.",
		localizedDescription: "模糊人物区域,画面其余部分保持清晰。",
		treatment: "subject-blur",
		intensity: 1,
		tags: ["person", "focus", "subject-blur", "tracking"],
		releasedAt: "2026-07-22T02:10:00.000Z",
		popularityScore: 86,
	}),
	createPersonEffectEntry({
		id: "person-subject-pixelate",
		name: "Subject Pixelate",
		localizedName: "局部马赛克",
		description: "Pixelates the tracked person for quick privacy.",
		localizedDescription: "对人物区域打上马赛克,一键遮挡。",
		treatment: "subject-pixelate",
		intensity: 1,
		tags: ["person", "focus", "subject-pixelate", "tracking"],
		releasedAt: "2026-07-22T02:10:00.000Z",
		popularityScore: 87,
	}),
	createPersonEffectEntry({
		id: "person-strobe-echo",
		name: "Strobe Echo",
		localizedName: "闪影",
		description: "Oscillating ghost copies flash beside the subject.",
		localizedDescription: "人物两侧闪烁摆动的残影分身。",
		treatment: "echo",
		echoVariant: "strobe",
		tags: ["person", "echo", "strobe", "tracking"],
		releasedAt: "2026-07-22T02:20:00.000Z",
		popularityScore: 89,
	}),
	createPersonEffectEntry({
		id: "person-motion-trail",
		name: "Motion Trail",
		localizedName: "背景拖影",
		description: "Fading trail copies stretch behind the subject.",
		localizedDescription: "人物身后拖出渐隐的运动残影。",
		treatment: "echo",
		echoVariant: "trail",
		tags: ["person", "echo", "trail", "tracking"],
		releasedAt: "2026-07-22T02:20:00.000Z",
		popularityScore: 90,
	}),
	createPersonEffectEntry({
		id: "person-shatter-clones",
		name: "Shatter Clones",
		localizedName: "碎片分身",
		description: "Scattered jittering clones burst around the subject.",
		localizedDescription: "环绕人物散落抖动的碎片分身。",
		treatment: "echo",
		echoVariant: "shatter",
		tags: ["person", "echo", "shatter", "tracking"],
		releasedAt: "2026-07-22T02:20:00.000Z",
		popularityScore: 85,
	}),
	createPersonEffectEntry({
		id: "person-dot-clones",
		name: "Dot Clones",
		localizedName: "波点分身",
		description: "Halftone-tinted clones flank the subject.",
		localizedDescription: "色偏波点质感的左右分身。",
		treatment: "echo",
		echoVariant: "dots",
		tags: ["person", "echo", "dots", "tracking"],
		releasedAt: "2026-07-22T02:20:00.000Z",
		popularityScore: 84,
	}),
] as const satisfies readonly PersonEffectCatalogEntry[];
