import type { EffectParticleVariant } from "@qcut/editor-core";
import type { EffectPreset } from "@/types/effects";
import type {
	VisualEffectCatalogEntry,
	VisualEffectCategoryId,
} from "./effect-catalog-types";

function createParticleCatalogEntry({
	id,
	name,
	localizedName,
	description,
	localizedDescription,
	category = "atmosphere",
	icon,
	variant,
	density,
	speed,
	color,
	opacity,
	tags,
	releasedAt,
	popularityScore,
}: {
	id: string;
	name: string;
	localizedName: string;
	description: string;
	localizedDescription: string;
	category?: VisualEffectCategoryId;
	icon: string;
	variant: EffectParticleVariant;
	density: number;
	speed: number;
	color: string;
	opacity: number;
	tags: readonly string[];
	releasedAt: string;
	popularityScore: number;
}): VisualEffectCatalogEntry {
	const preset: EffectPreset = {
		id,
		name,
		description,
		category: "basic",
		icon,
		parameters: {},
		renderProgram: {
			version: 1,
			stages: [{ kind: "particles", variant, density, speed, color, opacity }],
		},
	};

	return {
		preset,
		assetVersion: 1,
		localizedName,
		localizedDescription,
		family: "visual",
		category,
		tags,
		releasedAt,
		popularityScore,
		publication: "published",
		render: {
			kind: "particles",
			previewBackend: "canvas",
			// Rendered per-frame from the deterministic particle model. The export
			// pipeline bakes the same frames to a transparent PNG sequence and
			// composites them in the native FFmpeg pass (effect-procedural-sources).
			exportBackend: "frame-renderer",
			parity: "verified",
		},
	};
}

/**
 * 秋叶遮罩 pairs the sakura particle field with a vignette filter stage so
 * the falling leaves read as a veil framing the scene. Hand-written because
 * the factory above emits a single particles stage.
 */
function createAutumnVeilCatalogEntry(): VisualEffectCatalogEntry {
	const preset: EffectPreset = {
		id: "nature-autumn-veil",
		name: "Autumn Veil",
		description: "Orange-brown autumn leaves falling behind a soft vignette.",
		category: "basic",
		icon: "AV",
		parameters: { vignette: 40 },
		renderProgram: {
			version: 1,
			stages: [
				{ kind: "filter" },
				{
					kind: "particles",
					variant: "sakura",
					density: 0.6,
					speed: 0.85,
					color: "#c9803e",
					opacity: 0.9,
				},
			],
		},
	};

	return {
		preset,
		assetVersion: 1,
		localizedName: "秋叶遮罩",
		localizedDescription: "橙棕色秋叶飘落,配合柔和暗角遮罩。",
		family: "visual",
		category: "nature",
		tags: ["leaves", "autumn", "veil", "vignette", "nature", "particles"],
		releasedAt: "2026-07-27T00:00:00.000Z",
		popularityScore: 78,
		publication: "published",
		render: {
			kind: "particles",
			previewBackend: "canvas",
			exportBackend: "frame-renderer",
			parity: "verified",
		},
	};
}

export const PARTICLE_EFFECT_CATALOG = [
	createParticleCatalogEntry({
		id: "atmosphere-snow",
		name: "Snowfall",
		localizedName: "雪花散落",
		description: "Soft snow drifting gently down the frame.",
		localizedDescription: "柔软的雪花轻轻飘落。",
		icon: "SN",
		variant: "snow",
		density: 0.8,
		speed: 1,
		color: "#ffffff",
		opacity: 0.85,
		tags: ["snow", "winter", "atmosphere", "particles"],
		releasedAt: "2026-07-20T03:00:00.000Z",
		popularityScore: 90,
	}),
	createParticleCatalogEntry({
		id: "atmosphere-sakura",
		name: "Sakura",
		localizedName: "樱花飘落",
		description: "Pink cherry petals swaying as they fall.",
		localizedDescription: "粉色樱花花瓣摇曳飘落。",
		icon: "SK",
		variant: "sakura",
		density: 0.6,
		speed: 0.9,
		color: "#ffb7d5",
		opacity: 0.9,
		tags: ["sakura", "petals", "spring", "atmosphere", "particles"],
		releasedAt: "2026-07-20T03:01:00.000Z",
		popularityScore: 92,
	}),
	createParticleCatalogEntry({
		id: "atmosphere-embers",
		name: "Embers",
		localizedName: "星火",
		description: "Warm glowing embers rising and twinkling.",
		localizedDescription: "温暖的星火向上升腾并闪烁。",
		icon: "EM",
		variant: "embers",
		density: 0.7,
		speed: 1,
		color: "#ff9a3c",
		opacity: 0.9,
		tags: ["embers", "fire", "sparks", "atmosphere", "particles"],
		releasedAt: "2026-07-20T03:02:00.000Z",
		popularityScore: 87,
	}),
	createParticleCatalogEntry({
		id: "atmosphere-stars",
		name: "Starfield",
		localizedName: "繁星点点",
		description: "A field of gently twinkling stars.",
		localizedDescription: "满屏轻柔闪烁的繁星。",
		icon: "ST",
		variant: "stars",
		density: 0.85,
		speed: 1,
		color: "#fff4c2",
		opacity: 0.85,
		tags: ["stars", "night", "twinkle", "atmosphere", "particles"],
		releasedAt: "2026-07-20T03:03:00.000Z",
		popularityScore: 88,
	}),
	createParticleCatalogEntry({
		id: "atmosphere-confetti",
		name: "Confetti",
		localizedName: "缤纷彩带",
		description: "Colorful confetti tumbling down for celebrations.",
		localizedDescription: "五彩缤纷的彩带欢庆飘落。",
		icon: "CF",
		variant: "confetti",
		density: 0.75,
		speed: 1.1,
		color: "#ff5d8f",
		opacity: 0.95,
		tags: ["confetti", "celebrate", "party", "atmosphere", "particles"],
		releasedAt: "2026-07-20T03:04:00.000Z",
		popularityScore: 86,
	}),
	createParticleCatalogEntry({
		id: "atmosphere-fog",
		name: "Drifting Fog",
		localizedName: "腾云驾雾",
		description: "Soft fog banks drifting across the frame.",
		localizedDescription: "柔和的雾气在画面中缓缓流动。",
		icon: "FG",
		variant: "fog",
		density: 0.9,
		speed: 0.6,
		color: "#e8eef5",
		opacity: 0.4,
		tags: ["fog", "mist", "cloud", "atmosphere", "particles"],
		releasedAt: "2026-07-20T03:05:00.000Z",
		popularityScore: 84,
	}),
	createParticleCatalogEntry({
		id: "atmosphere-snow-sparkle",
		name: "Snow Sparkle",
		localizedName: "雪花细闪",
		description: "Fine glittering snow that twinkles across the frame.",
		localizedDescription: "细密闪烁的雪花点缀画面。",
		icon: "SS",
		variant: "stars",
		density: 1,
		speed: 0.9,
		color: "#ffffff",
		opacity: 0.8,
		tags: ["snow", "sparkle", "twinkle", "atmosphere", "particles"],
		releasedAt: "2026-07-20T03:10:00.000Z",
		popularityScore: 89,
	}),
	createParticleCatalogEntry({
		id: "atmosphere-sad-snow",
		name: "Melancholy Snow",
		localizedName: "伤感雪花",
		description: "Slow cool-toned snow drifting for a wistful mood.",
		localizedDescription: "缓慢的冷调雪花,烘托伤感氛围。",
		icon: "MS",
		variant: "snow",
		density: 0.55,
		speed: 0.6,
		color: "#cfe0f5",
		opacity: 0.8,
		tags: ["snow", "sad", "mood", "atmosphere", "particles"],
		releasedAt: "2026-07-20T03:11:00.000Z",
		popularityScore: 84,
	}),
	createParticleCatalogEntry({
		id: "atmosphere-gold-stars",
		name: "Gold Stars",
		localizedName: "金色星星",
		description: "Warm golden stars twinkling gently.",
		localizedDescription: "温暖的金色星星轻柔闪烁。",
		icon: "GS",
		variant: "stars",
		density: 0.8,
		speed: 1,
		color: "#ffd700",
		opacity: 0.9,
		tags: ["stars", "gold", "twinkle", "atmosphere", "particles"],
		releasedAt: "2026-07-20T03:12:00.000Z",
		popularityScore: 87,
	}),
	createParticleCatalogEntry({
		id: "atmosphere-gold-coins",
		name: "Gold Coins",
		localizedName: "灿灿金币",
		description: "Shimmering gold coins tumbling down for prosperity.",
		localizedDescription: "闪耀的金币纷纷落下,寓意招财。",
		icon: "GC",
		variant: "coins",
		density: 0.7,
		speed: 1,
		color: "#ffcf3f",
		opacity: 0.95,
		tags: ["coins", "gold", "wealth", "atmosphere", "particles"],
		releasedAt: "2026-07-20T03:13:00.000Z",
		popularityScore: 88,
	}),
	createParticleCatalogEntry({
		id: "atmosphere-butterfly",
		name: "Butterflies",
		localizedName: "梦蝶",
		description: "Dreamy butterflies fluttering across the frame.",
		localizedDescription: "梦幻的蝴蝶翩翩飞舞。",
		icon: "BF",
		variant: "butterfly",
		density: 0.6,
		speed: 0.8,
		color: "#c9a8ff",
		opacity: 0.9,
		tags: ["butterfly", "dream", "atmosphere", "particles"],
		releasedAt: "2026-07-20T03:14:00.000Z",
		popularityScore: 90,
	}),
	createParticleCatalogEntry({
		id: "atmosphere-dissolve",
		name: "Particle Dissolve",
		localizedName: "粒子消散",
		description: "Soft particles rising and dissolving upward.",
		localizedDescription: "柔和的粒子向上升腾并消散。",
		icon: "PD",
		variant: "embers",
		density: 0.8,
		speed: 0.8,
		color: "#eaf2ff",
		opacity: 0.75,
		tags: ["dissolve", "particles", "atmosphere"],
		releasedAt: "2026-07-20T03:15:00.000Z",
		popularityScore: 85,
	}),
	// Nature tab — reuses the particle model so the new 自然 category ships with
	// content instead of an empty scaffold.
	createParticleCatalogEntry({
		id: "nature-falling-leaves",
		name: "Falling Leaves",
		localizedName: "落叶纷飞",
		description: "Autumn leaves tumbling and swaying downward.",
		localizedDescription: "秋叶翻转摇曳,缓缓飘落。",
		category: "nature",
		icon: "LV",
		variant: "sakura",
		density: 0.6,
		speed: 0.85,
		color: "#e0a04a",
		opacity: 0.92,
		tags: ["leaves", "autumn", "nature", "particles"],
		releasedAt: "2026-07-20T03:06:00.000Z",
		popularityScore: 85,
	}),
	createParticleCatalogEntry({
		id: "nature-fireflies",
		name: "Fireflies",
		localizedName: "萤火虫",
		description: "Soft fireflies drifting and glowing in the dark.",
		localizedDescription: "柔和的萤火虫飘忽闪烁。",
		category: "nature",
		icon: "FF",
		variant: "embers",
		density: 0.5,
		speed: 0.5,
		color: "#c8ff7a",
		opacity: 0.9,
		tags: ["fireflies", "glow", "nature", "particles"],
		releasedAt: "2026-07-20T03:07:00.000Z",
		popularityScore: 86,
	}),
	createParticleCatalogEntry({
		id: "nature-snowfall",
		name: "Nature Snow",
		localizedName: "林间飘雪",
		description: "Gentle snow settling over a natural scene.",
		localizedDescription: "自然场景中轻柔飘落的雪。",
		category: "nature",
		icon: "NS",
		variant: "snow",
		density: 0.7,
		speed: 0.9,
		color: "#f4f9ff",
		opacity: 0.85,
		tags: ["snow", "winter", "nature", "particles"],
		releasedAt: "2026-07-20T03:08:00.000Z",
		popularityScore: 83,
	}),
	// 2026-07-27 剪映氛围包 — recolor/density variants of existing particle
	// models (bubbles=embers, bokeh=snow, petals/leaves=sakura).
	createParticleCatalogEntry({
		id: "atmosphere-bubbles",
		name: "Bubbles",
		localizedName: "泡泡",
		description: "Translucent bubbles drifting upward and shimmering.",
		localizedDescription: "半透明的泡泡向上飘浮并闪烁。",
		icon: "BB",
		variant: "embers",
		density: 0.4,
		speed: 0.7,
		color: "#dceeff",
		opacity: 0.55,
		tags: ["bubbles", "float", "water", "atmosphere", "particles"],
		releasedAt: "2026-07-27T00:00:00.000Z",
		popularityScore: 83,
	}),
	createParticleCatalogEntry({
		id: "light-bokeh-fall",
		name: "Bokeh Fall",
		localizedName: "光斑飘落",
		description: "Warm golden bokeh orbs drifting slowly down the frame.",
		localizedDescription: "温暖的金色光斑缓缓飘落。",
		category: "light",
		icon: "BK",
		variant: "snow",
		density: 0.5,
		speed: 0.5,
		color: "#ffd98a",
		opacity: 0.75,
		tags: ["bokeh", "glow", "gold", "light", "particles"],
		releasedAt: "2026-07-27T00:00:00.000Z",
		popularityScore: 85,
	}),
	createParticleCatalogEntry({
		id: "atmosphere-petal-rush",
		name: "Petal Rush",
		localizedName: "花瓣冲屏",
		description: "A dense rush of pink petals sweeping across the frame.",
		localizedDescription: "密集的粉色花瓣高速冲过画面。",
		icon: "PR",
		variant: "sakura",
		density: 0.95,
		speed: 1.8,
		color: "#ff9ec8",
		opacity: 0.95,
		tags: ["petals", "sakura", "rush", "atmosphere", "particles"],
		releasedAt: "2026-07-27T00:00:00.000Z",
		popularityScore: 86,
	}),
	createAutumnVeilCatalogEntry(),
	createParticleCatalogEntry({
		id: "light-starlight-bloom",
		name: "Starlight Bloom",
		localizedName: "星光绽放",
		description: "A dense field of golden-white starlight blooming on screen.",
		localizedDescription: "金白色星光在画面中密集绽放。",
		category: "light",
		icon: "SL",
		variant: "stars",
		density: 1,
		speed: 1,
		color: "#fff1b8",
		opacity: 0.9,
		tags: ["starlight", "bloom", "twinkle", "light", "particles"],
		releasedAt: "2026-07-27T00:00:00.000Z",
		popularityScore: 87,
	}),
] as const satisfies readonly VisualEffectCatalogEntry[];
