// Domain types re-exported from @qcut/editor-core
export type {
	MediaType,
	TrackType,
	MediaElement,
	MediaBlendMode,
	MediaFitMode,
	MediaCrop,
	MediaPerspective,
	MediaKeyframeProperty,
	MediaPropertyKeyframe,
	MediaAnimationType,
	MediaComboAnimationType,
	ClipTransition,
	ClipTransitionDirection,
	ClipTransitionEasing,
	ClipTransitionType,
	MediaAdjustments,
	ColorBasicSettings,
	ColorCubeLut,
	ColorCurvePoint,
	ColorCurveShapeKeyframe,
	ColorCurveShapeProperty,
	ColorCurvesSettings,
	ColorFilterApplication,
	ColorSecondaryCurve,
	ColorSecondaryCurveName,
	ColorSecondaryCurvesSettings,
	ColorGradeMaskSettings,
	ColorHslKeyframeProperty,
	ColorHslRangeName,
	ColorHslRangeSettings,
	ColorHslSettings,
	ColorKeyframeProperty,
	ColorLutSettings,
	ColorManagementSettings,
	ColorPropertyKeyframe,
	ColorSmartSettings,
	ColorSpace,
	ColorWheelKeyframeProperty,
	ColorWheelSettings,
	ColorWheelsSettings,
	MediaColorSettings,
	MediaMask,
	MediaMaskType,
	MediaMaskBlendMode,
	MediaMaskKeyframeProperty,
	MediaMaskPoint,
	MediaMaskStroke,
	MediaMaskStrokeStyle,
	MediaMaskTracking,
	MediaMaskTrackingDirection,
	MediaCustomCutout,
	MediaCustomCutoutBrushMode,
	MediaCustomCutoutPoint,
	MediaCustomCutoutStroke,
	MediaChromaKey,
	MediaChromaKeyKeyframeProperty,
	MediaEnhancements,
	AudioKeyframeProperty,
	AudioLoudnessSettings,
	AudioDenoiseSettings,
	AudioVoiceEnhanceSettings,
	AudioPitchSettings,
	AudioEqualizerSettings,
	AudioCompressorSettings,
	AudioLimiterSettings,
	AudioReverbSettings,
	AudioEchoSettings,
	AudioTelephoneSettings,
	AudioChannelMode,
	AudioParametricFilterType,
	AudioParametricEqBand,
	AudioParametricEqualizerSettings,
	AudioRepairSettings,
	AudioDuckingSettings,
	AudioAutoCrossfadeSettings,
	AudioCrossfade,
	AudioBusEffectsSettings,
	TimelineTrackAudioSettings,
	AudioMixBusSettings,
	ProjectAudioMixSettings,
	AudioStemName,
	AudioSeparationSettings,
	AudioVoiceConversionSettings,
	AudioCoverSettings,
	AudioLyricsWord,
	AudioLyricsSettings,
	MediaAudioSettings,
	TextElement,
	TextKeyframeProperty,
	TextPropertyKeyframe,
	StickerElement,
	AdjustmentElement,
	CaptionElement,
	SubtitleStyle,
	RemotionElement,
	MarkdownElement,
	TimelineElement,
	CreateMediaElement,
	CreateTextElement,
	CreateStickerElement,
	CreateAdjustmentElement,
	CreateCaptionElement,
	CreateRemotionElement,
	CreateMarkdownElement,
	CreateTimelineElement,
	TimelineTrack,
	BuildCompositionPlanOptions,
	CompositionAudioElement,
	CompositionDurationContext,
	CompositionLayer,
	CompositionPlan,
	MediaItemDragData,
	TextItemDragData,
	StickerItemDragData,
	RemotionItemDragData,
	MarkdownItemDragData,
	DragData,
} from "@qcut/editor-core";

// Re-export domain functions from @qcut/editor-core
export {
	sortTracksByOrder,
	normalizeTrackOrder,
	moveTrack,
	buildCompositionPlan,
	findClosestMediaSeam,
	getAudioCrossfadeMaxDuration,
	getTransitionMaxDuration,
	getMainTrack,
	reconcileTimelineTransitions,
	reconcileTrackTransitions,
	resolveAudioCrossfade,
	resolveClipTransition,
	ensureMainTrack,
	canElementGoOnTrack,
	validateElementTrackCompatibility,
	isMediaElement,
	isTextElement,
	isStickerElement,
	isAdjustmentElement,
	isCaptionElement,
	isRemotionElement,
	isMarkdownElement,
	getRemotionElements,
	getActiveRemotionElements,
	generateUUID,
} from "@qcut/editor-core";

// ---------------------------------------------------------------------------
// React/UI-specific types (stay in apps/web, not in editor-core)
// ---------------------------------------------------------------------------

import type { MouseEvent as ReactMouseEvent } from "react";
import type {
	TimelineElement as _TimelineElement,
	TimelineTrack as _TimelineTrack,
} from "@qcut/editor-core";

export interface TimelineElementProps {
	element: _TimelineElement;
	track: _TimelineTrack;
	zoomLevel: number;
	isSelected: boolean;
	onElementMouseDown: (e: ReactMouseEvent, element: _TimelineElement) => void;
	onElementClick: (e: ReactMouseEvent, element: _TimelineElement) => void;
}

export interface ResizeState {
	elementId: string;
	side: "left" | "right";
	startX: number;
	initialStartTime: number;
	initialTrimStart: number;
	initialTrimEnd: number;
}
