import type { FluentStickerCategoryId } from "./sticker-categories";

export interface FluentStickerDefinition {
	icon: string;
	name: string;
	localizedName: string;
}

export const FLUENT_STICKER_SETS: Record<
	FluentStickerCategoryId,
	readonly FluentStickerDefinition[]
> = {
	interaction: [
		{ icon: "thumbs-up", name: "Thumbs up", localizedName: "点赞" },
		{ icon: "clapping-hands", name: "Clapping hands", localizedName: "鼓掌" },
		{ icon: "red-heart", name: "Red heart", localizedName: "爱心" },
		{ icon: "sparkles", name: "Sparkles", localizedName: "闪亮" },
		{ icon: "party-popper", name: "Party popper", localizedName: "庆祝" },
		{ icon: "handshake", name: "Handshake", localizedName: "握手" },
		{ icon: "folded-hands", name: "Folded hands", localizedName: "感谢" },
		{ icon: "victory-hand", name: "Victory hand", localizedName: "胜利" },
		{ icon: "raising-hands", name: "Raising hands", localizedName: "欢呼" },
		{ icon: "hundred-points", name: "Hundred points", localizedName: "满分" },
		{ icon: "waving-hand", name: "Waving hand", localizedName: "挥手" },
		{ icon: "ok-hand", name: "OK hand", localizedName: "OK" },
		{ icon: "call-me-hand", name: "Call me", localizedName: "打电话手势" },
		{ icon: "crossed-fingers", name: "Crossed fingers", localizedName: "祈愿" },
		{ icon: "love-you-gesture", name: "Love you", localizedName: "爱你手势" },
		{ icon: "flexed-biceps", name: "Flexed biceps", localizedName: "加油" },
		{ icon: "index-pointing-up", name: "Pointing up", localizedName: "指上" },
		{
			icon: "backhand-index-pointing-right",
			name: "Pointing right",
			localizedName: "指右",
		},
		{ icon: "oncoming-fist", name: "Fist bump", localizedName: "碰拳" },
		{ icon: "raised-fist", name: "Raised fist", localizedName: "举拳" },
		{ icon: "vulcan-salute", name: "Vulcan salute", localizedName: "瓦肯礼" },
		{
			icon: "pinched-fingers",
			name: "Pinched fingers",
			localizedName: "捏手指",
		},
		{ icon: "palms-up-together", name: "Palms up", localizedName: "掌心向上" },
		{ icon: "open-hands", name: "Open hands", localizedName: "张开双手" },
		{ icon: "fire", name: "Fire", localizedName: "火焰" },
	],
	summer: [
		{ icon: "watermelon", name: "Watermelon", localizedName: "西瓜" },
		{ icon: "sun", name: "Sun", localizedName: "太阳" },
		{
			icon: "beach-with-umbrella",
			name: "Beach umbrella",
			localizedName: "沙滩伞",
		},
		{ icon: "palm-tree", name: "Palm tree", localizedName: "棕榈树" },
		{ icon: "ice-cream", name: "Ice cream", localizedName: "冰淇淋" },
		{ icon: "sun-with-face", name: "Sun with face", localizedName: "笑脸太阳" },
		{ icon: "sunglasses", name: "Sunglasses", localizedName: "太阳镜" },
		{
			icon: "tropical-drink",
			name: "Tropical drink",
			localizedName: "夏日饮料",
		},
		{ icon: "shaved-ice", name: "Shaved ice", localizedName: "刨冰" },
		{ icon: "hibiscus", name: "Hibiscus", localizedName: "扶桑花" },
		{ icon: "pineapple", name: "Pineapple", localizedName: "菠萝" },
		{ icon: "coconut", name: "Coconut", localizedName: "椰子" },
		{ icon: "mango", name: "Mango", localizedName: "芒果" },
		{ icon: "cherries", name: "Cherries", localizedName: "樱桃" },
		{ icon: "strawberry", name: "Strawberry", localizedName: "草莓" },
		{ icon: "spiral-shell", name: "Spiral shell", localizedName: "海螺" },
		{ icon: "crab", name: "Crab", localizedName: "螃蟹" },
		{
			icon: "umbrella-on-ground",
			name: "Beach parasol",
			localizedName: "遮阳伞",
		},
		{ icon: "person-surfing", name: "Surfing", localizedName: "冲浪" },
		{ icon: "person-swimming", name: "Swimming", localizedName: "游泳" },
		{ icon: "cocktail-glass", name: "Cocktail", localizedName: "鸡尾酒" },
		{ icon: "soft-ice-cream", name: "Soft serve", localizedName: "甜筒" },
		{
			icon: "sun-behind-small-cloud",
			name: "Sunny cloud",
			localizedName: "晴间多云",
		},
		{ icon: "butterfly", name: "Butterfly", localizedName: "蝴蝶" },
		{ icon: "seedling", name: "Seedling", localizedName: "嫩芽" },
	],
	vlog: [
		{ icon: "camera", name: "Camera", localizedName: "相机" },
		{ icon: "movie-camera", name: "Movie camera", localizedName: "电影机" },
		{ icon: "clapper-board", name: "Clapperboard", localizedName: "场记板" },
		{ icon: "video-camera", name: "Video camera", localizedName: "摄像机" },
		{ icon: "microphone", name: "Microphone", localizedName: "麦克风" },
		{ icon: "mobile-phone", name: "Mobile phone", localizedName: "手机拍摄" },
		{
			icon: "studio-microphone",
			name: "Studio microphone",
			localizedName: "录音麦克风",
		},
		{ icon: "film-projector", name: "Film projector", localizedName: "放映机" },
		{
			icon: "camera-with-flash",
			name: "Camera flash",
			localizedName: "闪光相机",
		},
		{ icon: "television", name: "Television", localizedName: "视频画面" },
		{ icon: "laptop", name: "Laptop", localizedName: "笔记本电脑" },
		{ icon: "headphone", name: "Headphones", localizedName: "耳机" },
		{ icon: "computer-mouse", name: "Mouse", localizedName: "鼠标" },
		{ icon: "printer", name: "Printer", localizedName: "打印机" },
		{ icon: "alarm-clock", name: "Alarm clock", localizedName: "闹钟" },
		{ icon: "hourglass-done", name: "Hourglass", localizedName: "沙漏" },
		{ icon: "satellite-antenna", name: "Antenna", localizedName: "信号天线" },
		{ icon: "cinema", name: "Cinema", localizedName: "影院" },
		{ icon: "control-knobs", name: "Control knobs", localizedName: "调音旋钮" },
		{ icon: "level-slider", name: "Level slider", localizedName: "推子" },
		{ icon: "battery", name: "Battery", localizedName: "电池" },
		{ icon: "electric-plug", name: "Plug", localizedName: "插头" },
		{
			icon: "magnifying-glass-tilted-left",
			name: "Magnifier",
			localizedName: "放大镜",
		},
		{ icon: "round-pushpin", name: "Pin", localizedName: "定位" },
		{ icon: "bell", name: "Bell", localizedName: "铃铛" },
	],
	mood: [
		{ icon: "grinning-face", name: "Grinning", localizedName: "开心" },
		{
			icon: "smiling-face-with-heart-eyes",
			name: "Heart eyes",
			localizedName: "心动",
		},
		{ icon: "loudly-crying-face", name: "Crying", localizedName: "大哭" },
		{ icon: "angry-face", name: "Angry", localizedName: "生气" },
		{
			icon: "face-with-tears-of-joy",
			name: "Tears of joy",
			localizedName: "笑哭",
		},
		{ icon: "pensive-face", name: "Pensive", localizedName: "低落" },
		{ icon: "astonished-face", name: "Astonished", localizedName: "震惊" },
		{ icon: "fearful-face", name: "Fearful", localizedName: "害怕" },
		{ icon: "relieved-face", name: "Relieved", localizedName: "安心" },
		{
			icon: "rolling-on-the-floor-laughing",
			name: "Laughing out loud",
			localizedName: "笑翻了",
		},
		{ icon: "smiling-face", name: "Smiling face", localizedName: "微笑" },
		{
			icon: "slightly-smiling-face",
			name: "Slight smile",
			localizedName: "浅笑",
		},
		{ icon: "neutral-face", name: "Neutral face", localizedName: "面无表情" },
		{
			icon: "expressionless-face",
			name: "Expressionless",
			localizedName: "无语",
		},
		{ icon: "unamused-face", name: "Unamused", localizedName: "不悦" },
		{ icon: "weary-face", name: "Weary", localizedName: "疲惫" },
		{ icon: "crying-face", name: "Crying", localizedName: "哭泣" },
		{ icon: "pouting-face", name: "Pouting", localizedName: "生闷气" },
		{ icon: "sleepy-face", name: "Sleepy", localizedName: "犯困" },
		{ icon: "sleeping-face", name: "Sleeping", localizedName: "睡着" },
		{ icon: "drooling-face", name: "Drooling", localizedName: "流口水" },
		{ icon: "woozy-face", name: "Woozy", localizedName: "晕乎" },
		{ icon: "exploding-head", name: "Mind blown", localizedName: "爆炸头" },
		{ icon: "cold-face", name: "Cold face", localizedName: "冻僵" },
		{ icon: "hot-face", name: "Hot face", localizedName: "热爆" },
	],
	conceal: [
		{ icon: "see-no-evil-monkey", name: "See no evil", localizedName: "捂眼" },
		{ icon: "eyes", name: "Eyes", localizedName: "眼睛" },
		{
			icon: "face-with-hand-over-mouth",
			name: "Hand over mouth",
			localizedName: "捂嘴",
		},
		{ icon: "zipper-mouth-face", name: "Zipper mouth", localizedName: "闭嘴" },
		{ icon: "shield", name: "Shield", localizedName: "遮挡盾牌" },
		{
			icon: "hear-no-evil-monkey",
			name: "Hear no evil",
			localizedName: "捂耳",
		},
		{
			icon: "speak-no-evil-monkey",
			name: "Speak no evil",
			localizedName: "不说",
		},
		{ icon: "stop-sign", name: "Stop sign", localizedName: "停止" },
		{ icon: "locked", name: "Locked", localizedName: "隐私锁" },
		{ icon: "prohibited", name: "Prohibited", localizedName: "禁止" },
		{ icon: "performing-arts", name: "Theater masks", localizedName: "面具" },
		{ icon: "dog-face", name: "Dog face", localizedName: "狗头" },
		{ icon: "cat-face", name: "Cat face", localizedName: "猫脸" },
		{ icon: "panda", name: "Panda", localizedName: "熊猫" },
		{ icon: "bear", name: "Bear", localizedName: "小熊" },
		{ icon: "koala", name: "Koala", localizedName: "考拉" },
		{ icon: "tiger-face", name: "Tiger face", localizedName: "虎头" },
		{ icon: "fox", name: "Fox", localizedName: "狐狸" },
		{ icon: "monkey-face", name: "Monkey face", localizedName: "猴脸" },
		{ icon: "unicorn", name: "Unicorn", localizedName: "独角兽" },
		{ icon: "pig-face", name: "Pig face", localizedName: "猪头" },
		{ icon: "mouse-face", name: "Mouse face", localizedName: "鼠脸" },
		{ icon: "hamster", name: "Hamster", localizedName: "仓鼠" },
		{ icon: "rabbit-face", name: "Rabbit face", localizedName: "兔脸" },
		{ icon: "frog", name: "Frog", localizedName: "青蛙" },
	],
	festival: [
		{ icon: "wrapped-gift", name: "Gift", localizedName: "礼物" },
		{ icon: "fireworks", name: "Fireworks", localizedName: "烟花" },
		{ icon: "christmas-tree", name: "Christmas tree", localizedName: "圣诞树" },
		{ icon: "red-envelope", name: "Red envelope", localizedName: "红包" },
		{ icon: "balloon", name: "Balloon", localizedName: "气球" },
		{ icon: "confetti-ball", name: "Confetti ball", localizedName: "彩带球" },
		{ icon: "sparkler", name: "Sparkler", localizedName: "仙女棒" },
		{ icon: "moon-cake", name: "Moon cake", localizedName: "月饼" },
		{ icon: "jack-o-lantern", name: "Jack-o-lantern", localizedName: "南瓜灯" },
		{ icon: "birthday-cake", name: "Birthday cake", localizedName: "生日蛋糕" },
		{ icon: "firecracker", name: "Firecracker", localizedName: "鞭炮" },
		{ icon: "ribbon", name: "Ribbon", localizedName: "丝带" },
		{ icon: "snowman", name: "Snowman", localizedName: "雪人" },
		{ icon: "snowflake", name: "Snowflake", localizedName: "雪花" },
		{ icon: "santa-claus", name: "Santa", localizedName: "圣诞老人" },
		{ icon: "four-leaf-clover", name: "Clover", localizedName: "四叶草" },
		{ icon: "bouquet", name: "Bouquet", localizedName: "花束" },
		{ icon: "tulip", name: "Tulip", localizedName: "郁金香" },
		{ icon: "pine-decoration", name: "Pine decoration", localizedName: "门松" },
		{ icon: "wind-chime", name: "Wind chime", localizedName: "风铃" },
		{ icon: "japanese-dolls", name: "Festival dolls", localizedName: "人偶" },
		{ icon: "carp-streamer", name: "Carp streamer", localizedName: "鲤鱼旗" },
		{ icon: "sheaf-of-rice", name: "Rice sheaf", localizedName: "稻穗" },
		{
			icon: "moon-viewing-ceremony",
			name: "Moon viewing",
			localizedName: "赏月",
		},
		{ icon: "izakaya-lantern", name: "Lantern", localizedName: "灯笼" },
	],
	ecommerce: [
		{ icon: "shopping-bags", name: "Shopping bags", localizedName: "购物袋" },
		{ icon: "shopping-cart", name: "Shopping cart", localizedName: "购物车" },
		{ icon: "money-bag", name: "Money bag", localizedName: "钱袋" },
		{ icon: "package", name: "Package", localizedName: "包裹" },
		{ icon: "delivery-truck", name: "Delivery truck", localizedName: "快递" },
		{ icon: "credit-card", name: "Credit card", localizedName: "信用卡" },
		{
			icon: "money-with-wings",
			name: "Money with wings",
			localizedName: "优惠",
		},
		{ icon: "receipt", name: "Receipt", localizedName: "订单" },
		{ icon: "bank", name: "Bank", localizedName: "支付" },
		{ icon: "coin", name: "Coin", localizedName: "金币" },
		{ icon: "label", name: "Label", localizedName: "标签" },
		{ icon: "megaphone", name: "Megaphone", localizedName: "大喇叭" },
		{ icon: "chart-increasing", name: "Chart up", localizedName: "上涨" },
		{ icon: "dollar-banknote", name: "Dollar note", localizedName: "美元" },
		{ icon: "yen-banknote", name: "Yen note", localizedName: "日元" },
		{ icon: "euro-banknote", name: "Euro note", localizedName: "欧元" },
		{ icon: "currency-exchange", name: "Exchange", localizedName: "汇率" },
		{ icon: "heavy-dollar-sign", name: "Dollar sign", localizedName: "钱符号" },
		{ icon: "convenience-store", name: "Store", localizedName: "便利店" },
		{
			icon: "department-store",
			name: "Department store",
			localizedName: "商场",
		},
		{ icon: "bellhop-bell", name: "Service bell", localizedName: "服务铃" },
		{ icon: "calendar", name: "Calendar", localizedName: "日历" },
		{ icon: "spiral-calendar", name: "Spiral calendar", localizedName: "台历" },
		{ icon: "card-file-box", name: "File box", localizedName: "档案盒" },
		{ icon: "chart-decreasing", name: "Chart down", localizedName: "下跌" },
	],
	doodle: [
		{ icon: "crayon", name: "Crayon", localizedName: "蜡笔" },
		{ icon: "artist-palette", name: "Artist palette", localizedName: "调色盘" },
		{ icon: "paintbrush", name: "Paintbrush", localizedName: "画笔" },
		{ icon: "pencil", name: "Pencil", localizedName: "铅笔" },
		{
			icon: "thought-balloon",
			name: "Thought bubble",
			localizedName: "想法气泡",
		},
		{ icon: "scissors", name: "Scissors", localizedName: "剪刀" },
		{ icon: "pushpin", name: "Pushpin", localizedName: "图钉" },
		{
			icon: "speech-balloon",
			name: "Speech bubble",
			localizedName: "对话气泡",
		},
		{ icon: "star", name: "Star", localizedName: "手绘星星" },
		{ icon: "rainbow", name: "Rainbow", localizedName: "彩虹" },
		{ icon: "dizzy", name: "Dizzy", localizedName: "眩晕星" },
		{ icon: "collision", name: "Collision", localizedName: "碰撞" },
		{ icon: "sweat-droplets", name: "Sweat drops", localizedName: "汗滴" },
		{ icon: "dashing-away", name: "Dash away", localizedName: "疾风" },
		{ icon: "zzz", name: "Zzz", localizedName: "呼呼大睡" },
		{ icon: "anger-symbol", name: "Anger mark", localizedName: "怒气" },
		{
			icon: "right-anger-bubble",
			name: "Anger bubble",
			localizedName: "怒气泡",
		},
		{
			icon: "left-speech-bubble",
			name: "Speech bubble",
			localizedName: "对话泡",
		},
		{ icon: "glowing-star", name: "Glowing star", localizedName: "发光星" },
		{ icon: "shooting-star", name: "Shooting star", localizedName: "流星" },
		{ icon: "comet", name: "Comet", localizedName: "彗星" },
		{ icon: "cloud", name: "Cloud", localizedName: "云朵" },
		{ icon: "high-voltage", name: "Lightning", localizedName: "闪电" },
		{ icon: "cyclone", name: "Cyclone", localizedName: "旋涡" },
		{ icon: "musical-notes", name: "Musical notes", localizedName: "音符" },
	],
	sports: [
		{ icon: "person-running", name: "Running", localizedName: "跑步" },
		{ icon: "basketball", name: "Basketball", localizedName: "篮球" },
		{ icon: "soccer-ball", name: "Football", localizedName: "足球" },
		{ icon: "trophy", name: "Trophy", localizedName: "奖杯" },
		{ icon: "running-shoe", name: "Running shoe", localizedName: "跑鞋" },
		{ icon: "volleyball", name: "Volleyball", localizedName: "排球" },
		{ icon: "tennis", name: "Tennis", localizedName: "网球" },
		{ icon: "badminton", name: "Badminton", localizedName: "羽毛球" },
		{ icon: "sports-medal", name: "Sports medal", localizedName: "奖牌" },
		{ icon: "person-biking", name: "Cycling", localizedName: "骑行" },
		{ icon: "baseball", name: "Baseball", localizedName: "棒球" },
		{ icon: "softball", name: "Softball", localizedName: "垒球" },
		{ icon: "american-football", name: "Football", localizedName: "橄榄球" },
		{ icon: "rugby-football", name: "Rugby", localizedName: "英式橄榄球" },
		{ icon: "ping-pong", name: "Ping pong", localizedName: "乒乓球" },
		{ icon: "ice-hockey", name: "Ice hockey", localizedName: "冰球" },
		{ icon: "field-hockey", name: "Field hockey", localizedName: "曲棍球" },
		{ icon: "cricket-game", name: "Cricket", localizedName: "板球" },
		{ icon: "bowling", name: "Bowling", localizedName: "保龄球" },
		{ icon: "boxing-glove", name: "Boxing glove", localizedName: "拳击手套" },
		{
			icon: "martial-arts-uniform",
			name: "Martial arts",
			localizedName: "武道服",
		},
		{ icon: "goal-net", name: "Goal net", localizedName: "球门" },
		{ icon: "flying-disc", name: "Flying disc", localizedName: "飞盘" },
		{ icon: "skateboard", name: "Skateboard", localizedName: "滑板" },
		{ icon: "ice-skate", name: "Ice skate", localizedName: "冰鞋" },
	],
	"little-blue": [
		{ icon: "blue-heart", name: "Blue heart", localizedName: "蓝心" },
		{ icon: "blueberries", name: "Blueberries", localizedName: "蓝莓" },
		{ icon: "dolphin", name: "Dolphin", localizedName: "海豚" },
		{ icon: "water-wave", name: "Water wave", localizedName: "海浪" },
		{
			icon: "light-blue-heart",
			name: "Light blue heart",
			localizedName: "浅蓝心",
		},
		{ icon: "blue-circle", name: "Blue circle", localizedName: "蓝色圆点" },
		{ icon: "whale", name: "Whale", localizedName: "鲸鱼" },
		{ icon: "tropical-fish", name: "Tropical fish", localizedName: "热带鱼" },
		{ icon: "droplet", name: "Droplet", localizedName: "水滴" },
		{ icon: "jellyfish", name: "Jellyfish", localizedName: "水母" },
	],
	frames: [
		{ icon: "film-frames", name: "Film frames", localizedName: "胶片框" },
		{ icon: "framed-picture", name: "Picture frame", localizedName: "相框" },
		{ icon: "mirror", name: "Mirror frame", localizedName: "镜框" },
		{ icon: "window", name: "Window frame", localizedName: "窗框" },
		{
			icon: "identification-card",
			name: "Card frame",
			localizedName: "卡片框",
		},
		{ icon: "admission-tickets", name: "Ticket pair", localizedName: "票券框" },
		{ icon: "card-index", name: "Index card", localizedName: "索引卡" },
		{ icon: "ticket", name: "Ticket", localizedName: "票根框" },
		{ icon: "door", name: "Door frame", localizedName: "门框" },
		{ icon: "placard", name: "Placard", localizedName: "挂牌框" },
		{
			icon: "white-square-button",
			name: "White square",
			localizedName: "白方框",
		},
		{
			icon: "black-square-button",
			name: "Black square",
			localizedName: "黑方框",
		},
		{ icon: "red-square", name: "Red square", localizedName: "红方块" },
		{ icon: "blue-square", name: "Blue square", localizedName: "蓝方块" },
		{ icon: "green-square", name: "Green square", localizedName: "绿方块" },
		{ icon: "yellow-square", name: "Yellow square", localizedName: "黄方块" },
		{ icon: "orange-square", name: "Orange square", localizedName: "橙方块" },
		{ icon: "purple-square", name: "Purple square", localizedName: "紫方块" },
		{ icon: "brown-square", name: "Brown square", localizedName: "棕方块" },
		{
			icon: "white-large-square",
			name: "Large white square",
			localizedName: "大白框",
		},
		{
			icon: "black-large-square",
			name: "Large black square",
			localizedName: "大黑框",
		},
		{
			icon: "diamond-with-a-dot",
			name: "Diamond dot",
			localizedName: "菱形芯",
		},
		{
			icon: "large-blue-diamond",
			name: "Blue diamond",
			localizedName: "蓝菱形",
		},
		{
			icon: "large-orange-diamond",
			name: "Orange diamond",
			localizedName: "橙菱形",
		},
		{ icon: "red-circle", name: "Red circle", localizedName: "红圆框" },
	],
	travel: [
		{ icon: "airplane", name: "Airplane", localizedName: "飞机" },
		{ icon: "luggage", name: "Luggage", localizedName: "行李箱" },
		{ icon: "world-map", name: "World map", localizedName: "世界地图" },
		{ icon: "compass", name: "Compass", localizedName: "指南针" },
		{ icon: "camping", name: "Camping", localizedName: "露营" },
		{ icon: "taxi", name: "Taxi", localizedName: "出租车" },
		{ icon: "rocket", name: "Rocket", localizedName: "火箭旅行" },
		{ icon: "sailboat", name: "Sailboat", localizedName: "帆船" },
		{ icon: "snow-capped-mountain", name: "Mountain", localizedName: "雪山" },
		{ icon: "desert-island", name: "Desert island", localizedName: "海岛" },
		{ icon: "locomotive", name: "Locomotive", localizedName: "火车头" },
		{ icon: "train", name: "Train", localizedName: "列车" },
		{ icon: "metro", name: "Metro", localizedName: "地铁" },
		{ icon: "bus", name: "Bus", localizedName: "巴士" },
		{ icon: "automobile", name: "Car", localizedName: "汽车" },
		{ icon: "motor-scooter", name: "Scooter", localizedName: "踏板车" },
		{ icon: "kick-scooter", name: "Kick scooter", localizedName: "滑板车" },
		{ icon: "ferry", name: "Ferry", localizedName: "渡轮" },
		{ icon: "motor-boat", name: "Motor boat", localizedName: "快艇" },
		{ icon: "anchor", name: "Anchor", localizedName: "船锚" },
		{ icon: "fuel-pump", name: "Fuel pump", localizedName: "加油站" },
		{
			icon: "statue-of-liberty",
			name: "Statue of Liberty",
			localizedName: "自由女神",
		},
		{ icon: "mount-fuji", name: "Mount Fuji", localizedName: "富士山" },
		{ icon: "tokyo-tower", name: "Tokyo Tower", localizedName: "东京塔" },
		{ icon: "national-park", name: "National park", localizedName: "国家公园" },
	],
	handwriting: [
		{ icon: "memo", name: "Memo", localizedName: "便签" },
		{ icon: "fountain-pen", name: "Fountain pen", localizedName: "钢笔" },
		{ icon: "pen", name: "Pen", localizedName: "签字笔" },
		{ icon: "writing-hand", name: "Writing hand", localizedName: "手写" },
		{ icon: "open-book", name: "Open book", localizedName: "手账" },
		{ icon: "closed-book", name: "Closed book", localizedName: "日记本" },
		{ icon: "notebook", name: "Notebook", localizedName: "笔记本" },
		{ icon: "ledger", name: "Ledger", localizedName: "账本" },
		{ icon: "books", name: "Books", localizedName: "书本" },
		{ icon: "bookmark-tabs", name: "Bookmark tabs", localizedName: "标签贴" },
		{ icon: "black-nib", name: "Black nib", localizedName: "钢笔尖" },
		{ icon: "clipboard", name: "Clipboard", localizedName: "写字板" },
		{ icon: "spiral-notepad", name: "Spiral notepad", localizedName: "线圈本" },
		{ icon: "file-folder", name: "File folder", localizedName: "文件夹" },
		{
			icon: "open-file-folder",
			name: "Open folder",
			localizedName: "打开文件夹",
		},
		{
			icon: "card-index-dividers",
			name: "Dividers",
			localizedName: "索引隔页",
		},
		{ icon: "bookmark", name: "Bookmark", localizedName: "书签" },
		{ icon: "page-facing-up", name: "Page", localizedName: "文页" },
		{ icon: "page-with-curl", name: "Curled page", localizedName: "卷角纸" },
		{ icon: "scroll", name: "Scroll", localizedName: "卷轴" },
		{ icon: "newspaper", name: "Newspaper", localizedName: "报纸" },
		{
			icon: "rolled-up-newspaper",
			name: "Rolled newspaper",
			localizedName: "报纸卷",
		},
		{
			icon: "triangular-ruler",
			name: "Triangle ruler",
			localizedName: "三角尺",
		},
		{ icon: "straight-ruler", name: "Ruler", localizedName: "直尺" },
		{ icon: "paperclip", name: "Paperclip", localizedName: "回形针" },
	],
	romance: [
		{ icon: "kiss-mark", name: "Kiss mark", localizedName: "唇印" },
		{ icon: "love-letter", name: "Love letter", localizedName: "情书" },
		{ icon: "two-hearts", name: "Two hearts", localizedName: "双心" },
		{ icon: "rose", name: "Rose", localizedName: "玫瑰" },
		{
			icon: "heart-with-arrow",
			name: "Heart with arrow",
			localizedName: "丘比特之心",
		},
		{
			icon: "sparkling-heart",
			name: "Sparkling heart",
			localizedName: "闪亮爱心",
		},
		{ icon: "growing-heart", name: "Growing heart", localizedName: "心动放大" },
		{
			icon: "heart-with-ribbon",
			name: "Heart with ribbon",
			localizedName: "礼物爱心",
		},
		{
			icon: "revolving-hearts",
			name: "Revolving hearts",
			localizedName: "环绕爱心",
		},
		{ icon: "heart-hands", name: "Heart hands", localizedName: "比心" },
		{
			icon: "heart-exclamation",
			name: "Heart exclamation",
			localizedName: "心叹号",
		},
		{ icon: "broken-heart", name: "Broken heart", localizedName: "心碎" },
		{ icon: "orange-heart", name: "Orange heart", localizedName: "橙心" },
		{ icon: "yellow-heart", name: "Yellow heart", localizedName: "黄心" },
		{ icon: "green-heart", name: "Green heart", localizedName: "绿心" },
		{ icon: "purple-heart", name: "Purple heart", localizedName: "紫心" },
		{ icon: "black-heart", name: "Black heart", localizedName: "黑心" },
		{ icon: "white-heart", name: "White heart", localizedName: "白心" },
		{ icon: "brown-heart", name: "Brown heart", localizedName: "棕心" },
		{
			icon: "heart-decoration",
			name: "Heart decoration",
			localizedName: "心形装饰",
		},
		{ icon: "couple-with-heart", name: "Couple", localizedName: "情侣" },
		{ icon: "kiss", name: "Kiss", localizedName: "亲吻" },
		{ icon: "wedding", name: "Wedding", localizedName: "婚礼" },
		{ icon: "cherry-blossom", name: "Cherry blossom", localizedName: "樱花" },
		{ icon: "white-flower", name: "White flower", localizedName: "白花" },
	],
	beauty: [
		{ icon: "lipstick", name: "Lipstick", localizedName: "口红" },
		{ icon: "nail-polish", name: "Nail polish", localizedName: "美甲" },
		{ icon: "mirror-ball", name: "Mirror ball", localizedName: "闪耀妆容" },
		{ icon: "high-heeled-shoe", name: "High heel", localizedName: "高跟鞋" },
		{ icon: "ring", name: "Ring", localizedName: "戒指" },
		{ icon: "gem-stone", name: "Gem stone", localizedName: "宝石" },
		{ icon: "crown", name: "Crown", localizedName: "皇冠" },
		{ icon: "handbag", name: "Handbag", localizedName: "手提包" },
		{ icon: "dress", name: "Dress", localizedName: "连衣裙" },
		{ icon: "lotion-bottle", name: "Lotion bottle", localizedName: "护肤品" },
		{ icon: "bathtub", name: "Bathtub", localizedName: "浴缸" },
		{ icon: "soap", name: "Soap", localizedName: "香皂" },
		{ icon: "razor", name: "Razor", localizedName: "剃刀" },
		{ icon: "toothbrush", name: "Toothbrush", localizedName: "牙刷" },
		{ icon: "comb", name: "Comb", localizedName: "梳子" },
		{ icon: "shower", name: "Shower", localizedName: "淋浴" },
		{ icon: "kimono", name: "Kimono", localizedName: "和服" },
		{ icon: "coat", name: "Coat", localizedName: "大衣" },
		{ icon: "gloves", name: "Gloves", localizedName: "手套" },
		{ icon: "scarf", name: "Scarf", localizedName: "围巾" },
		{ icon: "top-hat", name: "Top hat", localizedName: "礼帽" },
		{ icon: "billed-cap", name: "Cap", localizedName: "棒球帽" },
		{ icon: "socks", name: "Socks", localizedName: "袜子" },
		{ icon: "person-getting-haircut", name: "Haircut", localizedName: "理发" },
		{ icon: "person-getting-massage", name: "Massage", localizedName: "按摩" },
	],
	faces: [
		{
			icon: "smiling-face-with-hearts",
			name: "Smiling with hearts",
			localizedName: "幸福脸",
		},
		{
			icon: "face-blowing-a-kiss",
			name: "Blowing a kiss",
			localizedName: "飞吻",
		},
		{ icon: "winking-face", name: "Winking", localizedName: "眨眼" },
		{
			icon: "smiling-face-with-smiling-eyes",
			name: "Warm smile",
			localizedName: "微笑",
		},
		{
			icon: "beaming-face-with-smiling-eyes",
			name: "Beaming face",
			localizedName: "灿烂笑脸",
		},
		{
			icon: "smiling-face-with-sunglasses",
			name: "Cool face",
			localizedName: "酷酷脸",
		},
		{ icon: "thinking-face", name: "Thinking face", localizedName: "思考脸" },
		{
			icon: "upside-down-face",
			name: "Upside-down face",
			localizedName: "倒脸",
		},
		{ icon: "partying-face", name: "Partying face", localizedName: "派对脸" },
		{ icon: "star-struck", name: "Star-struck", localizedName: "星星眼" },
		{
			icon: "face-with-rolling-eyes",
			name: "Rolling eyes",
			localizedName: "翻白眼",
		},
		{ icon: "smirking-face", name: "Smirk", localizedName: "坏笑" },
		{
			icon: "face-with-raised-eyebrow",
			name: "Raised eyebrow",
			localizedName: "挑眉",
		},
		{ icon: "face-without-mouth", name: "No mouth", localizedName: "无嘴脸" },
		{ icon: "grimacing-face", name: "Grimace", localizedName: "龇牙咧嘴" },
		{ icon: "face-with-open-mouth", name: "Open mouth", localizedName: "张嘴" },
		{ icon: "hushed-face", name: "Hushed", localizedName: "惊讶安静" },
		{ icon: "flushed-face", name: "Flushed", localizedName: "脸红" },
		{
			icon: "downcast-face-with-sweat",
			name: "Downcast sweat",
			localizedName: "冷汗低落",
		},
		{ icon: "disappointed-face", name: "Disappointed", localizedName: "失望" },
		{ icon: "worried-face", name: "Worried", localizedName: "担心" },
		{ icon: "confused-face", name: "Confused", localizedName: "困惑" },
		{
			icon: "slightly-frowning-face",
			name: "Slight frown",
			localizedName: "微皱眉",
		},
		{
			icon: "face-with-steam-from-nose",
			name: "Steam nose",
			localizedName: "气鼓鼓",
		},
		{ icon: "yawning-face", name: "Yawning", localizedName: "打哈欠" },
	],
};
