import type { ThemedStickerCategoryId } from "./sticker-categories";

export type ThemedStickerStyle =
	| "arrow"
	| "burst"
	| "caption"
	| "frame"
	| "label"
	| "note"
	| "pill"
	| "progress"
	| "speech"
	| "stamp";

export interface ThemedStickerPalette {
	accent: string;
	background: string;
	ink: string;
	secondary: string;
}

export interface ThemedStickerDefinition {
	id: string;
	name: string;
	localizedName: string;
	style: ThemedStickerStyle;
	tags: readonly string[];
}

export interface ThemedStickerPack {
	id: ThemedStickerCategoryId;
	name: string;
	localizedName: string;
	palette: ThemedStickerPalette;
	items: readonly ThemedStickerDefinition[];
}

type PhrasePair = readonly [localizedName: string, name: string];

interface ThemedStickerPackSeed {
	count: number;
	name: string;
	localizedName: string;
	palette: ThemedStickerPalette;
	phrases: readonly PhrasePair[];
}

const STYLES = [
	"pill",
	"burst",
	"speech",
	"arrow",
	"progress",
	"caption",
	"stamp",
	"note",
	"label",
	"frame",
] as const satisfies readonly ThemedStickerStyle[];

const STYLE_NAMES: Record<ThemedStickerStyle, string> = {
	arrow: "Arrow",
	burst: "Burst",
	caption: "Caption",
	frame: "Frame",
	label: "Label",
	note: "Note",
	pill: "Pill",
	progress: "Progress",
	speech: "Speech Bubble",
	stamp: "Stamp",
};

const PACK_SEEDS: Record<ThemedStickerCategoryId, ThemedStickerPackSeed> = {
	popular: {
		count: 48,
		name: "Popular",
		localizedName: "热门",
		palette: {
			accent: "#ff6b35",
			background: "#fff1e8",
			ink: "#3c1f1a",
			secondary: "#ffd166",
		},
		phrases: [
			["爆款推荐", "Trending pick"],
			["高能片段", "High energy"],
			["必看", "Must watch"],
			["今日热门", "Popular today"],
			["全场焦点", "Main focus"],
			["点赞收藏", "Like and save"],
			["精彩来了", "Highlight incoming"],
			["超有料", "Worth watching"],
			["别错过", "Do not miss"],
			["热度拉满", "Full heat"],
			["全网疯传", "Going viral"],
			["万人围观", "Crowd favorite"],
			["强烈安利", "Highly recommend"],
			["榜单第一", "Number one"],
			["封神现场", "Legendary moment"],
			["火出圈了", "Broke the internet"],
			["播放破亿", "Record views"],
			["停不下来", "Can't stop"],
			["反复观看", "On repeat"],
			["高赞视频", "Top rated"],
			["后劲十足", "Stays with you"],
			["名场面", "Iconic scene"],
			["全网催更", "Fans want more"],
			["王炸开场", "Explosive opening"],
		],
	},
	interaction: {
		count: 48,
		name: "Interaction",
		localizedName: "互动",
		palette: {
			accent: "#ffcf33",
			background: "#fff2b8",
			ink: "#3c3151",
			secondary: "#ff6b6b",
		},
		phrases: [
			["关注我", "Follow me"],
			["点赞", "Like"],
			["评论区见", "See you in comments"],
			["转发一下", "Share it"],
			["收藏啦", "Saved"],
			["谢谢支持", "Thanks for the support"],
			["一起互动", "Join the conversation"],
			["记得订阅", "Remember to subscribe"],
			["戳这里", "Tap here"],
			["安排上", "Consider it done"],
			["一键三连", "Show some love"],
			["双击屏幕", "Double tap"],
			["点个小心心", "Tap the heart"],
			["开启小铃铛", "Turn on alerts"],
			["留言告诉我", "Tell me below"],
			["投票选一个", "Vote below"],
			["猜猜看", "Take a guess"],
			["你怎么看", "Your thoughts"],
			["蹲更新", "Stay tuned"],
			["抽奖时间", "Giveaway time"],
			["有奖问答", "Quiz time"],
			["置顶评论", "Pinned comment"],
			["快来打卡", "Check in now"],
			["互关一下", "Follow back"],
		],
	},
	summer: {
		count: 48,
		name: "Summer",
		localizedName: "夏日",
		palette: {
			accent: "#00b8d9",
			background: "#d9fbff",
			ink: "#174a5b",
			secondary: "#ff7f50",
		},
		phrases: [
			["夏日快乐", "Happy summer"],
			["去看海", "See the sea"],
			["清凉一下", "Cool down"],
			["冰爽时刻", "Icy moment"],
			["假日模式", "Holiday mode"],
			["阳光正好", "Perfect sunshine"],
			["海边见", "Meet by the sea"],
			["西瓜自由", "Watermelon time"],
			["热浪来袭", "Heat wave"],
			["夏夜晚风", "Summer night breeze"],
			["冰镇一夏", "Chilled summer"],
			["防晒到位", "Sunscreen on"],
			["泳池派对", "Pool party"],
			["赤脚踩浪", "Barefoot in waves"],
			["冰美式", "Iced coffee"],
			["蝉鸣午后", "Cicada afternoon"],
			["浪花来了", "Wave incoming"],
			["空调自由", "Endless AC"],
			["夏天限定", "Summer only"],
			["浪一整夏", "All summer long"],
			["日落晚霞", "Sunset glow"],
			["汽水冒泡", "Fizzy soda"],
			["冲浪时间", "Surf time"],
			["晒黑警告", "Tan alert"],
		],
	},
	vlog: {
		count: 48,
		name: "Vlog",
		localizedName: "Vlog",
		palette: {
			accent: "#f4d35e",
			background: "#fffbe6",
			ink: "#26233a",
			secondary: "#ee6c4d",
		},
		phrases: [
			["今日美好", "Beautiful today"],
			["记录生活", "Life diary"],
			["出发啦", "Let's go"],
			["好天气", "Good weather"],
			["幸运一天", "Lucky day"],
			["幕后花絮", "Behind the scenes"],
			["本期看点", "Episode highlights"],
			["加载中", "Loading"],
			["下集见", "See you next time"],
			["周末日记", "Weekend diary"],
			["起床啦", "Rise and shine"],
			["早餐时间", "Breakfast time"],
			["日常碎片", "Daily bits"],
			["镜头一转", "Cut to"],
			["午后时光", "Afternoon hours"],
			["超市大采购", "Grocery run"],
			["新的一天", "A new day"],
			["碎碎念", "Random thoughts"],
			["一人食", "Table for one"],
			["回家路上", "Heading home"],
			["打工日常", "Work day"],
			["收工啦", "Wrap up"],
			["未完待续", "To be continued"],
			["晚安时间", "Good night"],
		],
	},
	mood: {
		count: 48,
		name: "Mood",
		localizedName: "情绪",
		palette: {
			accent: "#ff5d8f",
			background: "#ffe8f0",
			ink: "#4a2b45",
			secondary: "#8f7cff",
		},
		phrases: [
			["开心", "Happy"],
			["好期待", "Can't wait"],
			["太棒啦", "Amazing"],
			["有点害羞", "A little shy"],
			["震惊", "Shocked"],
			["委屈", "Upset"],
			["生气了", "Angry"],
			["笑不活了", "So funny"],
			["状态满格", "Full energy"],
			["今天也不错", "Today is good"],
			["破防了", "Broke me"],
			["无语了", "Speechless"],
			["泪目", "Teary eyed"],
			["满血复活", "Back to life"],
			["心花怒放", "Overjoyed"],
			["累到不行", "Totally drained"],
			["想躺平", "Just wanna chill"],
			["超级满足", "So satisfied"],
			["淡定", "Staying calm"],
			["又酸又甜", "Bittersweet"],
			["嘴角上扬", "Can't stop smiling"],
			["社死现场", "Total cringe"],
			["有被感动", "Truly moved"],
		],
	},
	conceal: {
		count: 48,
		name: "Conceal",
		localizedName: "遮挡",
		palette: {
			accent: "#8d99ae",
			background: "#edf2f4",
			ink: "#2b2d42",
			secondary: "#ef476f",
		},
		phrases: [
			["此处保密", "Private"],
			["暂不公开", "Not public"],
			["打码中", "Redacted"],
			["请勿偷看", "Do not peek"],
			["隐藏信息", "Hidden info"],
			["重点遮挡", "Covered"],
			["神秘区域", "Mystery area"],
			["内容保护", "Protected"],
			["稍后揭晓", "Coming soon"],
			["不能说", "Can't tell"],
			["马赛克", "Mosaic"],
			["此处省略", "Omitted here"],
			["无可奉告", "No comment"],
			["别问", "Don't ask"],
			["挡一下", "Just covering"],
			["看不见", "Nothing to see"],
			["敏感信息", "Sensitive info"],
			["悄悄藏起", "Tucked away"],
			["商业机密", "Trade secret"],
			["私人领地", "Private zone"],
			["别拍我", "Don't film me"],
			["名字隐去", "Name hidden"],
			["已屏蔽", "Blocked out"],
			["空白处理", "Blanked out"],
		],
	},
	festival: {
		count: 48,
		name: "Festival",
		localizedName: "节日",
		palette: {
			accent: "#ffd166",
			background: "#fff2d8",
			ink: "#7f1d1d",
			secondary: "#e63946",
		},
		phrases: [
			["节日快乐", "Happy holidays"],
			["新年快乐", "Happy new year"],
			["生日快乐", "Happy birthday"],
			["假期愉快", "Enjoy the holiday"],
			["好运连连", "Good luck"],
			["万事胜意", "Best wishes"],
			["团圆时刻", "Together time"],
			["庆祝一下", "Celebrate"],
			["礼物时间", "Gift time"],
			["快乐加倍", "Double happiness"],
			["恭喜发财", "Wishing prosperity"],
			["大吉大利", "Great fortune"],
			["花好月圆", "Full moon blessings"],
			["心想事成", "Dreams come true"],
			["年年有余", "Abundance always"],
			["阖家欢乐", "Family joy"],
			["举杯同庆", "Cheers together"],
			["烟花绽放", "Fireworks up"],
			["许个愿吧", "Make a wish"],
			["红包拿来", "Red packet please"],
			["新春到", "Spring festival"],
			["张灯结彩", "Lanterns and lights"],
			["岁岁平安", "Safe all year"],
		],
	},
	ecommerce: {
		count: 48,
		name: "E-commerce",
		localizedName: "电商",
		palette: {
			accent: "#ffb703",
			background: "#fff4cc",
			ink: "#4d2d18",
			secondary: "#fb5607",
		},
		phrases: [
			["新品上市", "New arrival"],
			["限时折扣", "Limited offer"],
			["立即抢购", "Shop now"],
			["超值推荐", "Best value"],
			["爆款", "Best seller"],
			["今日特价", "Today only"],
			["好物分享", "Good find"],
			["包邮", "Free shipping"],
			["库存告急", "Almost gone"],
			["买它", "Add to cart"],
			["秒杀", "Flash sale"],
			["手慢无", "Gone in seconds"],
			["到手价", "Final price"],
			["领券下单", "Grab a coupon"],
			["拍下立减", "Instant discount"],
			["现货速发", "Ships today"],
			["预售开启", "Presale open"],
			["打骨折", "Huge markdown"],
			["亲测好用", "Tested and loved"],
			["平价替代", "Budget dupe"],
			["无理由退换", "Easy returns"],
			["赠品多多", "Extra freebies"],
			["最后一波", "Last drop"],
			["直播专享", "Live only"],
		],
	},
	doodle: {
		count: 48,
		name: "Cute Doodles",
		localizedName: "涂鸦萌趣",
		palette: {
			accent: "#8ac926",
			background: "#f1ffd8",
			ink: "#2f3e22",
			secondary: "#ffca3a",
		},
		phrases: [
			["灵感来了", "Idea"],
			["随手一画", "Quick doodle"],
			["可可爱爱", "So cute"],
			["划重点", "Highlight"],
			["看这里", "Look here"],
			["小提醒", "Reminder"],
			["脑洞时间", "Imagination"],
			["手账一下", "Journal moment"],
			["涂鸦日常", "Doodle diary"],
			["灵光一闪", "Spark"],
			["就是它", "That's the one"],
			["笔记一下", "Jot it down"],
			["贴纸时间", "Sticker time"],
			["随便涂涂", "Just scribbling"],
			["星星点点", "Sprinkle stars"],
			["奇奇怪怪", "Weird and cute"],
			["画完收工", "All done"],
			["涂色中", "Coloring in"],
			["歪歪扭扭", "Wobbly lines"],
			["满分", "Full marks"],
			["打个勾", "Check it off"],
			["加个箭头", "This way"],
		],
	},
	sports: {
		count: 48,
		name: "Sports",
		localizedName: "运动",
		palette: {
			accent: "#00b4d8",
			background: "#dcf8ff",
			ink: "#073b4c",
			secondary: "#ff4d6d",
		},
		phrases: [
			["全力以赴", "Give it all"],
			["运动打卡", "Workout done"],
			["燃起来", "On fire"],
			["坚持一下", "Keep going"],
			["状态在线", "Game on"],
			["冲向终点", "Finish strong"],
			["今日训练", "Training day"],
			["能量满格", "Full power"],
			["漂亮一球", "Great shot"],
			["冠军时刻", "Champion moment"],
		],
	},
	"little-blue": {
		count: 48,
		name: "Little Blue",
		localizedName: "小蓝",
		palette: {
			accent: "#4cc9f0",
			background: "#e4f8ff",
			ink: "#1d3557",
			secondary: "#4361ee",
		},
		phrases: [
			["蓝蓝的心", "Blue heart"],
			["清醒一下", "Refresh"],
			["海风吹来", "Ocean breeze"],
			["心情晴朗", "Clear mood"],
			["慢慢来", "Take it easy"],
			["治愈时刻", "Healing moment"],
			["自由呼吸", "Breathe free"],
			["安静一下", "Quiet time"],
			["今日份蓝", "Blue of the day"],
			["保持清凉", "Stay cool"],
			["加油冲", "Let's go"],
			["再来一组", "One more set"],
			["破纪录", "New record"],
			["心跳加速", "Heart racing"],
			["汗水不骗人", "Sweat pays off"],
			["热身开始", "Warming up"],
			["肌肉记忆", "Muscle memory"],
			["不服来战", "Bring it on"],
			["逆风翻盘", "Comeback"],
			["稳住", "Hold steady"],
			["跑起来", "Run it"],
			["一起练", "Train together"],
			["拉伸一下", "Cool down"],
			["下次更强", "Stronger next time"],
			["浪花声", "Sound of waves"],
			["云很轻", "Light clouds"],
			["发发呆", "Zone out"],
			["晒晒太阳", "Soak up sun"],
			["水波荡漾", "Ripples"],
			["把心放空", "Clear your mind"],
			["雨后清新", "After the rain"],
			["温柔一点", "Be gentle"],
			["好好睡觉", "Sleep well"],
			["一起看海", "Ocean day"],
			["无所事事", "Doing nothing"],
			["透透气", "Get some air"],
			["轻轻放下", "Let it go"],
			["星期天", "Sunday mood"],
		],
	},
	frames: {
		count: 48,
		name: "Frames",
		localizedName: "边框",
		palette: {
			accent: "#ff9f1c",
			background: "#fff3df",
			ink: "#463f3a",
			secondary: "#2ec4b6",
		},
		phrases: [
			["今日记录", "Today"],
			["高光时刻", "Highlight"],
			["照片日记", "Photo diary"],
			["故事开始", "Story begins"],
			["这一刻", "This moment"],
			["美好收藏", "Good memories"],
			["镜头里", "In frame"],
			["值得纪念", "Worth remembering"],
			["生活切片", "Life snapshot"],
			["画面定格", "Freeze frame"],
			["取景中", "Framing"],
			["随手一拍", "Quick snap"],
			["旧照重温", "Throwback"],
			["珍藏版", "Keepsake"],
			["合影留念", "Group photo"],
			["框住时光", "Framed in time"],
			["剧照感", "Film still"],
			["底片色", "Film tone"],
			["请入画", "Step inside"],
			["满格回忆", "Full of memories"],
			["最佳角度", "Best angle"],
			["按下快门", "Shutter click"],
			["记忆边框", "Memory frame"],
			["再看一眼", "One more look"],
		],
	},
	travel: {
		count: 48,
		name: "Travel",
		localizedName: "旅行",
		palette: {
			accent: "#06d6a0",
			background: "#defcf2",
			ink: "#194d44",
			secondary: "#118ab2",
		},
		phrases: [
			["出发去旅行", "Let's travel"],
			["下一站", "Next stop"],
			["在路上", "On the road"],
			["城市漫步", "City walk"],
			["旅行日记", "Travel diary"],
			["看世界", "See the world"],
			["周末出逃", "Weekend escape"],
			["抵达快乐", "Arrived happy"],
			["风景正好", "Great view"],
			["一路顺风", "Bon voyage"],
			["打卡地标", "Landmark stop"],
			["山海之间", "Sea and mountains"],
			["说走就走", "Just go"],
			["收拾行李", "Packing up"],
			["机票到手", "Tickets booked"],
			["当地限定", "Local only"],
			["迷路也好", "Happily lost"],
			["日落时分", "Golden hour"],
			["海边发呆", "Beach daydream"],
			["山顶视角", "View from top"],
			["早班车", "Early train"],
			["徒步中", "Hiking now"],
			["返程中", "Heading back"],
		],
	},
	handwriting: {
		count: 48,
		name: "Handwriting",
		localizedName: "手写字",
		palette: {
			accent: "#f28482",
			background: "#fff6f1",
			ink: "#3d405b",
			secondary: "#84a59d",
		},
		phrases: [
			["今日份美好", "Today's joy"],
			["保持热爱", "Stay passionate"],
			["慢慢生活", "Live slowly"],
			["好事发生", "Good things happen"],
			["平安喜乐", "Peace and joy"],
			["随心记录", "Write freely"],
			["愿望清单", "Wish list"],
			["写给自己", "Note to self"],
			["闪闪发光", "Keep shining"],
			["明天会更好", "Better tomorrow"],
			["万事顺遂", "All goes well"],
			["心之所向", "Follow your heart"],
			["不慌不忙", "No rush"],
			["温柔以待", "Be gentle"],
			["生活小记", "Life notes"],
			["前路可期", "Bright road ahead"],
			["认真生活", "Live fully"],
			["自在一点", "Take it easy"],
			["此刻很好", "This moment"],
			["手写心情", "Handwritten mood"],
			["一期一会", "Once in life"],
			["悄悄努力", "Quietly working"],
			["岁月温柔", "Gentle days"],
		],
	},
	romance: {
		count: 48,
		name: "Romance",
		localizedName: "浪漫",
		palette: {
			accent: "#ff70a6",
			background: "#ffe5ec",
			ink: "#5f2942",
			secondary: "#ff9770",
		},
		phrases: [
			["心动时刻", "Heart beat"],
			["喜欢你", "Like you"],
			["甜甜的", "So sweet"],
			["浪漫一下", "Be romantic"],
			["爱意满满", "Full of love"],
			["与你有关", "All about you"],
			["双向奔赴", "Meet halfway"],
			["怦然心动", "Falling for you"],
			["今日约会", "Date day"],
			["永远热恋", "Forever in love"],
			["偷偷看你", "Stealing glances"],
			["想见你了", "Missing you"],
			["心动预警", "Heart alert"],
			["你是唯一", "You're the one"],
			["牵手同行", "Hand in hand"],
			["一起变老", "Grow old together"],
			["恋爱脑", "Lovestruck"],
			["官宣啦", "Making it official"],
			["小鹿乱撞", "Butterflies"],
			["独家宠爱", "Only for you"],
			["撒糖时刻", "Sugar overload"],
			["命中注定", "Meant to be"],
			["恋爱进行时", "In love"],
			["一见钟情", "Instant crush"],
		],
	},
	beauty: {
		count: 48,
		name: "Beauty",
		localizedName: "美妆",
		palette: {
			accent: "#e76f9a",
			background: "#fff0f6",
			ink: "#5a3448",
			secondary: "#9b5de5",
		},
		phrases: [
			["今日妆容", "Today's look"],
			["变美日记", "Beauty diary"],
			["好物推荐", "Beauty pick"],
			["显白神器", "Glow up"],
			["氛围感", "The vibe"],
			["精致一下", "Polished"],
			["素颜也美", "Naturally beautiful"],
			["闪耀登场", "Shine on"],
			["护肤时间", "Skin care time"],
			["今日份漂亮", "Beautiful today"],
			["妆前妆后", "Before and after"],
			["空瓶推荐", "Empties pick"],
			["一秒变美", "Instant glow"],
			["无瑕底妆", "Flawless base"],
			["口红试色", "Lipstick swatch"],
			["平价之光", "Budget hero"],
			["元气妆", "Fresh look"],
			["补水急救", "Hydration boost"],
			["少女感", "Youthful vibe"],
			["抗老必备", "Anti-aging must"],
			["香香的", "Smells good"],
			["眼妆教程", "Eye look tips"],
			["无限回购", "Repeat buy"],
		],
	},
	faces: {
		count: 48,
		name: "Faces",
		localizedName: "颜表情",
		palette: {
			accent: "#ffbe0b",
			background: "#fff5c2",
			ink: "#403d39",
			secondary: "#fb5607",
		},
		phrases: [
			["嘿嘿", "Hehe"],
			["哇哦", "Wow"],
			["好耶", "Yay"],
			["我懂了", "Got it"],
			["真的吗", "Really"],
			["有点慌", "Nervous"],
			["哈哈哈哈", "Hahaha"],
			["不愧是我", "That's me"],
			["可以的", "Nice"],
			["陷入沉思", "Thinking"],
		],
	},
	"world-cup": {
		count: 48,
		name: "World Cup",
		localizedName: "世界杯",
		palette: {
			accent: "#2a9d8f",
			background: "#e5fff7",
			ink: "#173b35",
			secondary: "#f4a261",
		},
		phrases: [
			["为热爱呐喊", "Cheer for the game"],
			["漂亮进球", "Great goal"],
			["今晚看球", "Match night"],
			["全场沸腾", "Crowd goes wild"],
			["冠军之路", "Road to glory"],
			["加时绝杀", "Last minute winner"],
			["绿茵时刻", "Pitch moment"],
			["一起欢呼", "Cheer together"],
			["决赛见", "See you in the final"],
			["热血开场", "Kickoff"],
			["世界波", "Screamer"],
			["点球大战", "Penalty shootout"],
			["扳平比分", "Equalizer"],
			["帽子戏法", "Hat trick"],
			["神级扑救", "Epic save"],
			["逆转开始", "Comeback time"],
			["再进一个", "One more goal"],
			["锁定胜局", "Sealed it"],
			["最后一攻", "Final push"],
			["熬夜也值", "Worth staying up"],
			["球迷集合", "Fans assemble"],
			["守住防线", "Hold the line"],
			["半场结束", "Halftime"],
			["全场最佳", "Match MVP"],
		],
	},
	"line-friends": {
		count: 48,
		name: "QCut Line Friends",
		localizedName: "线条伙伴",
		palette: {
			accent: "#f8f9fa",
			background: "#ffffff",
			ink: "#30343f",
			secondary: "#ff6b6b",
		},
		phrases: [
			["早安", "Good morning"],
			["出发啦", "Let's go"],
			["加油呀", "You can do it"],
			["收到", "Got it"],
			["等等我", "Wait for me"],
			["休息一下", "Take a break"],
			["今天真棒", "Great day"],
			["晚安", "Good night"],
			["谢谢你", "Thank you"],
			["一起走", "Together"],
			["震惊了", "Shocked"],
			["笑死我了", "Dying laughing"],
			["什么情况", "What happened"],
			["好困啊", "So sleepy"],
			["好家伙", "Whoa"],
			["我裂开了", "I'm done"],
			["麻了", "Numb"],
			["心虚", "Guilty"],
			["好想吃", "Craving it"],
			["委屈巴巴", "Pouting"],
			["得意一下", "Feeling smug"],
			["一脸问号", "So confused"],
			["抱抱你", "Big hug"],
			["好开心", "So happy"],
			["饿了呀", "Hungry now"],
			["困死啦", "So sleepy"],
			["想你了", "Miss you"],
			["摸摸头", "Pat pat"],
			["好厉害", "So cool"],
			["陪着你", "I'm here"],
			["偷偷看", "Peeking"],
			["超喜欢", "Love it"],
			["晚点聊", "Talk later"],
			["元气满满", "Full of energy"],
			["快夸我", "Praise me"],
			["害羞了", "So shy"],
		],
	},
	graphics: {
		count: 48,
		name: "Graphics",
		localizedName: "图形库",
		palette: {
			accent: "#80ed99",
			background: "#f1fff4",
			ink: "#263238",
			secondary: "#57cc99",
		},
		phrases: [
			["重点", "Highlight"],
			["提示", "Tip"],
			["向这里", "This way"],
			["加载中", "Loading"],
			["请注意", "Attention"],
			["下一步", "Next"],
			["完成", "Complete"],
			["新内容", "New"],
			["稍等", "Please wait"],
			["目标", "Target"],
			["敲黑板", "Listen up"],
			["高能预警", "Heads up"],
			["放大看", "Zoom in"],
			["对比一下", "Compare"],
			["核心步骤", "Key step"],
			["优先级高", "Top priority"],
			["数据说话", "By the numbers"],
			["从这开始", "Start here"],
			["避坑提醒", "Watch out"],
			["小结一下", "Recap"],
			["秒懂", "Quick take"],
			["答案揭晓", "The answer"],
			["三步搞定", "Three steps"],
			["结论先行", "Bottom line"],
		],
	},
};

function createItems({
	count,
	phrases,
}: {
	count: number;
	phrases: readonly PhrasePair[];
}): ThemedStickerDefinition[] {
	return Array.from({ length: count }, (_, index) => {
		const cycle = Math.floor(index / phrases.length);
		const [localizedName, name] = phrases[index % phrases.length];
		const style = STYLES[(index + cycle * 3) % STYLES.length];
		return {
			id: `${style}-${String(index + 1).padStart(2, "0")}`,
			name: `${name} ${STYLE_NAMES[style]}`,
			localizedName,
			style,
			tags: [name, localizedName, STYLE_NAMES[style]],
		};
	});
}

export const THEMED_STICKER_PACKS: readonly ThemedStickerPack[] =
	Object.entries(PACK_SEEDS).map(([id, seed]) => ({
		id: id as ThemedStickerCategoryId,
		name: seed.name,
		localizedName: seed.localizedName,
		palette: seed.palette,
		items: createItems({ count: seed.count, phrases: seed.phrases }),
	}));
