import type { FluentStickerCategoryId } from "./sticker-categories";

export interface FluentStickerDefinition {
	icon: string;
	name: string;
	localizedName: string;
}

export const FLUENT_STICKER_SETS: Record<
	FluentStickerCategoryId,
	readonly FluentStickerDefinition[]
> = {
	interaction: [
		{ icon: "thumbs-up", name: "Thumbs up", localizedName: "点赞" },
		{ icon: "clapping-hands", name: "Clapping hands", localizedName: "鼓掌" },
		{ icon: "red-heart", name: "Red heart", localizedName: "爱心" },
		{ icon: "sparkles", name: "Sparkles", localizedName: "闪亮" },
		{ icon: "party-popper", name: "Party popper", localizedName: "庆祝" },
		{ icon: "handshake", name: "Handshake", localizedName: "握手" },
		{ icon: "folded-hands", name: "Folded hands", localizedName: "感谢" },
		{ icon: "victory-hand", name: "Victory hand", localizedName: "胜利" },
		{ icon: "raising-hands", name: "Raising hands", localizedName: "欢呼" },
		{ icon: "hundred-points", name: "Hundred points", localizedName: "满分" },
	],
	summer: [
		{ icon: "watermelon", name: "Watermelon", localizedName: "西瓜" },
		{ icon: "sun", name: "Sun", localizedName: "太阳" },
		{
			icon: "beach-with-umbrella",
			name: "Beach umbrella",
			localizedName: "沙滩伞",
		},
		{ icon: "palm-tree", name: "Palm tree", localizedName: "棕榈树" },
		{ icon: "ice-cream", name: "Ice cream", localizedName: "冰淇淋" },
		{ icon: "sun-with-face", name: "Sun with face", localizedName: "笑脸太阳" },
		{ icon: "sunglasses", name: "Sunglasses", localizedName: "太阳镜" },
		{
			icon: "tropical-drink",
			name: "Tropical drink",
			localizedName: "夏日饮料",
		},
		{ icon: "shaved-ice", name: "Shaved ice", localizedName: "刨冰" },
		{ icon: "hibiscus", name: "Hibiscus", localizedName: "扶桑花" },
	],
	vlog: [
		{ icon: "camera", name: "Camera", localizedName: "相机" },
		{ icon: "movie-camera", name: "Movie camera", localizedName: "电影机" },
		{ icon: "clapper-board", name: "Clapperboard", localizedName: "场记板" },
		{ icon: "video-camera", name: "Video camera", localizedName: "摄像机" },
		{ icon: "microphone", name: "Microphone", localizedName: "麦克风" },
		{ icon: "mobile-phone", name: "Mobile phone", localizedName: "手机拍摄" },
		{
			icon: "studio-microphone",
			name: "Studio microphone",
			localizedName: "录音麦克风",
		},
		{ icon: "film-projector", name: "Film projector", localizedName: "放映机" },
		{
			icon: "camera-with-flash",
			name: "Camera flash",
			localizedName: "闪光相机",
		},
		{ icon: "television", name: "Television", localizedName: "视频画面" },
	],
	mood: [
		{ icon: "grinning-face", name: "Grinning", localizedName: "开心" },
		{
			icon: "smiling-face-with-heart-eyes",
			name: "Heart eyes",
			localizedName: "心动",
		},
		{ icon: "loudly-crying-face", name: "Crying", localizedName: "大哭" },
		{ icon: "angry-face", name: "Angry", localizedName: "生气" },
		{
			icon: "face-with-tears-of-joy",
			name: "Tears of joy",
			localizedName: "笑哭",
		},
		{ icon: "pensive-face", name: "Pensive", localizedName: "低落" },
		{ icon: "astonished-face", name: "Astonished", localizedName: "震惊" },
		{ icon: "fearful-face", name: "Fearful", localizedName: "害怕" },
		{ icon: "relieved-face", name: "Relieved", localizedName: "安心" },
		{
			icon: "rolling-on-the-floor-laughing",
			name: "Laughing out loud",
			localizedName: "笑翻了",
		},
	],
	conceal: [
		{ icon: "see-no-evil-monkey", name: "See no evil", localizedName: "捂眼" },
		{ icon: "eyes", name: "Eyes", localizedName: "眼睛" },
		{
			icon: "face-with-hand-over-mouth",
			name: "Hand over mouth",
			localizedName: "捂嘴",
		},
		{ icon: "zipper-mouth-face", name: "Zipper mouth", localizedName: "闭嘴" },
		{ icon: "shield", name: "Shield", localizedName: "遮挡盾牌" },
		{
			icon: "hear-no-evil-monkey",
			name: "Hear no evil",
			localizedName: "捂耳",
		},
		{
			icon: "speak-no-evil-monkey",
			name: "Speak no evil",
			localizedName: "不说",
		},
		{ icon: "stop-sign", name: "Stop sign", localizedName: "停止" },
		{ icon: "locked", name: "Locked", localizedName: "隐私锁" },
		{ icon: "prohibited", name: "Prohibited", localizedName: "禁止" },
	],
	festival: [
		{ icon: "wrapped-gift", name: "Gift", localizedName: "礼物" },
		{ icon: "fireworks", name: "Fireworks", localizedName: "烟花" },
		{ icon: "christmas-tree", name: "Christmas tree", localizedName: "圣诞树" },
		{ icon: "red-envelope", name: "Red envelope", localizedName: "红包" },
		{ icon: "balloon", name: "Balloon", localizedName: "气球" },
		{ icon: "confetti-ball", name: "Confetti ball", localizedName: "彩带球" },
		{ icon: "sparkler", name: "Sparkler", localizedName: "仙女棒" },
		{ icon: "moon-cake", name: "Moon cake", localizedName: "月饼" },
		{ icon: "jack-o-lantern", name: "Jack-o-lantern", localizedName: "南瓜灯" },
		{ icon: "birthday-cake", name: "Birthday cake", localizedName: "生日蛋糕" },
	],
	ecommerce: [
		{ icon: "shopping-bags", name: "Shopping bags", localizedName: "购物袋" },
		{ icon: "shopping-cart", name: "Shopping cart", localizedName: "购物车" },
		{ icon: "money-bag", name: "Money bag", localizedName: "钱袋" },
		{ icon: "package", name: "Package", localizedName: "包裹" },
		{ icon: "delivery-truck", name: "Delivery truck", localizedName: "快递" },
		{ icon: "credit-card", name: "Credit card", localizedName: "信用卡" },
		{
			icon: "money-with-wings",
			name: "Money with wings",
			localizedName: "优惠",
		},
		{ icon: "receipt", name: "Receipt", localizedName: "订单" },
		{ icon: "bank", name: "Bank", localizedName: "支付" },
		{ icon: "coin", name: "Coin", localizedName: "金币" },
	],
	doodle: [
		{ icon: "crayon", name: "Crayon", localizedName: "蜡笔" },
		{ icon: "artist-palette", name: "Artist palette", localizedName: "调色盘" },
		{ icon: "paintbrush", name: "Paintbrush", localizedName: "画笔" },
		{ icon: "pencil", name: "Pencil", localizedName: "铅笔" },
		{
			icon: "thought-balloon",
			name: "Thought bubble",
			localizedName: "想法气泡",
		},
		{ icon: "scissors", name: "Scissors", localizedName: "剪刀" },
		{ icon: "pushpin", name: "Pushpin", localizedName: "图钉" },
		{
			icon: "speech-balloon",
			name: "Speech bubble",
			localizedName: "对话气泡",
		},
		{ icon: "star", name: "Star", localizedName: "手绘星星" },
		{ icon: "rainbow", name: "Rainbow", localizedName: "彩虹" },
	],
	sports: [
		{ icon: "person-running", name: "Running", localizedName: "跑步" },
		{ icon: "basketball", name: "Basketball", localizedName: "篮球" },
		{ icon: "soccer-ball", name: "Football", localizedName: "足球" },
		{ icon: "trophy", name: "Trophy", localizedName: "奖杯" },
		{ icon: "running-shoe", name: "Running shoe", localizedName: "跑鞋" },
		{ icon: "volleyball", name: "Volleyball", localizedName: "排球" },
		{ icon: "tennis", name: "Tennis", localizedName: "网球" },
		{ icon: "badminton", name: "Badminton", localizedName: "羽毛球" },
		{ icon: "sports-medal", name: "Sports medal", localizedName: "奖牌" },
		{ icon: "person-biking", name: "Cycling", localizedName: "骑行" },
	],
	"little-blue": [
		{ icon: "blue-heart", name: "Blue heart", localizedName: "蓝心" },
		{ icon: "blueberries", name: "Blueberries", localizedName: "蓝莓" },
		{ icon: "dolphin", name: "Dolphin", localizedName: "海豚" },
		{ icon: "water-wave", name: "Water wave", localizedName: "海浪" },
		{
			icon: "light-blue-heart",
			name: "Light blue heart",
			localizedName: "浅蓝心",
		},
		{ icon: "blue-circle", name: "Blue circle", localizedName: "蓝色圆点" },
		{ icon: "whale", name: "Whale", localizedName: "鲸鱼" },
		{ icon: "tropical-fish", name: "Tropical fish", localizedName: "热带鱼" },
		{ icon: "droplet", name: "Droplet", localizedName: "水滴" },
		{ icon: "jellyfish", name: "Jellyfish", localizedName: "水母" },
	],
	frames: [
		{ icon: "film-frames", name: "Film frames", localizedName: "胶片框" },
		{ icon: "framed-picture", name: "Picture frame", localizedName: "相框" },
		{ icon: "mirror", name: "Mirror frame", localizedName: "镜框" },
		{ icon: "window", name: "Window frame", localizedName: "窗框" },
		{
			icon: "identification-card",
			name: "Card frame",
			localizedName: "卡片框",
		},
		{ icon: "admission-tickets", name: "Ticket pair", localizedName: "票券框" },
		{ icon: "card-index", name: "Index card", localizedName: "索引卡" },
		{ icon: "ticket", name: "Ticket", localizedName: "票根框" },
		{ icon: "door", name: "Door frame", localizedName: "门框" },
		{ icon: "placard", name: "Placard", localizedName: "挂牌框" },
	],
	travel: [
		{ icon: "airplane", name: "Airplane", localizedName: "飞机" },
		{ icon: "luggage", name: "Luggage", localizedName: "行李箱" },
		{ icon: "world-map", name: "World map", localizedName: "世界地图" },
		{ icon: "compass", name: "Compass", localizedName: "指南针" },
		{ icon: "camping", name: "Camping", localizedName: "露营" },
		{ icon: "taxi", name: "Taxi", localizedName: "出租车" },
		{ icon: "rocket", name: "Rocket", localizedName: "火箭旅行" },
		{ icon: "sailboat", name: "Sailboat", localizedName: "帆船" },
		{ icon: "snow-capped-mountain", name: "Mountain", localizedName: "雪山" },
		{ icon: "desert-island", name: "Desert island", localizedName: "海岛" },
	],
	handwriting: [
		{ icon: "memo", name: "Memo", localizedName: "便签" },
		{ icon: "fountain-pen", name: "Fountain pen", localizedName: "钢笔" },
		{ icon: "pen", name: "Pen", localizedName: "签字笔" },
		{ icon: "writing-hand", name: "Writing hand", localizedName: "手写" },
		{ icon: "open-book", name: "Open book", localizedName: "手账" },
		{ icon: "closed-book", name: "Closed book", localizedName: "日记本" },
		{ icon: "notebook", name: "Notebook", localizedName: "笔记本" },
		{ icon: "ledger", name: "Ledger", localizedName: "账本" },
		{ icon: "books", name: "Books", localizedName: "书本" },
		{ icon: "bookmark-tabs", name: "Bookmark tabs", localizedName: "标签贴" },
	],
	romance: [
		{ icon: "kiss-mark", name: "Kiss mark", localizedName: "唇印" },
		{ icon: "love-letter", name: "Love letter", localizedName: "情书" },
		{ icon: "two-hearts", name: "Two hearts", localizedName: "双心" },
		{ icon: "rose", name: "Rose", localizedName: "玫瑰" },
		{
			icon: "heart-with-arrow",
			name: "Heart with arrow",
			localizedName: "丘比特之心",
		},
		{
			icon: "sparkling-heart",
			name: "Sparkling heart",
			localizedName: "闪亮爱心",
		},
		{ icon: "growing-heart", name: "Growing heart", localizedName: "心动放大" },
		{
			icon: "heart-with-ribbon",
			name: "Heart with ribbon",
			localizedName: "礼物爱心",
		},
		{
			icon: "revolving-hearts",
			name: "Revolving hearts",
			localizedName: "环绕爱心",
		},
		{ icon: "heart-hands", name: "Heart hands", localizedName: "比心" },
	],
	beauty: [
		{ icon: "lipstick", name: "Lipstick", localizedName: "口红" },
		{ icon: "nail-polish", name: "Nail polish", localizedName: "美甲" },
		{ icon: "mirror-ball", name: "Mirror ball", localizedName: "闪耀妆容" },
		{ icon: "high-heeled-shoe", name: "High heel", localizedName: "高跟鞋" },
		{ icon: "ring", name: "Ring", localizedName: "戒指" },
		{ icon: "gem-stone", name: "Gem stone", localizedName: "宝石" },
		{ icon: "crown", name: "Crown", localizedName: "皇冠" },
		{ icon: "handbag", name: "Handbag", localizedName: "手提包" },
		{ icon: "dress", name: "Dress", localizedName: "连衣裙" },
		{ icon: "lotion-bottle", name: "Lotion bottle", localizedName: "护肤品" },
	],
	faces: [
		{
			icon: "smiling-face-with-hearts",
			name: "Smiling with hearts",
			localizedName: "幸福脸",
		},
		{
			icon: "face-blowing-a-kiss",
			name: "Blowing a kiss",
			localizedName: "飞吻",
		},
		{ icon: "winking-face", name: "Winking", localizedName: "眨眼" },
		{
			icon: "smiling-face-with-smiling-eyes",
			name: "Warm smile",
			localizedName: "微笑",
		},
		{
			icon: "beaming-face-with-smiling-eyes",
			name: "Beaming face",
			localizedName: "灿烂笑脸",
		},
		{
			icon: "smiling-face-with-sunglasses",
			name: "Cool face",
			localizedName: "酷酷脸",
		},
		{ icon: "thinking-face", name: "Thinking face", localizedName: "思考脸" },
		{
			icon: "upside-down-face",
			name: "Upside-down face",
			localizedName: "倒脸",
		},
		{ icon: "partying-face", name: "Partying face", localizedName: "派对脸" },
		{ icon: "star-struck", name: "Star-struck", localizedName: "星星眼" },
	],
};
