export {
	TEMPLATE_ASPECT_RATIOS,
	TIMELINE_TEMPLATE_SCHEMA,
	TIMELINE_TEMPLATE_SCHEMA_VERSION,
	migrateTemplateSlotValues,
	migrateTimelineTemplate,
	resolveTemplateFontDependencies,
	resolveTimelineTemplateVariant,
	validateTemplateSlotValues,
	validateTimelineTemplate,
	type LegacyTimelineTemplateV1,
	type TemplateAspectRatio,
	type TemplateFontDependency,
	type TemplateInstanceBinding,
	type TemplateMediaPlacement,
	type TemplateMediaSlot,
	type TemplateTextPlacement,
	type TemplateTextSlot,
	type TimelineTemplate,
	type TimelineTemplateDocument,
	type TimelineTemplatePlacement,
	type TimelineTemplateSlot,
	type TimelineTemplateSlotValue,
	type TimelineTemplateSlotValues,
	type TimelineTemplateValidationCode,
	type TimelineTemplateValidationIssue,
	type TimelineTemplateValidationResult,
	type TimelineTemplateVariant,
	type TimelineTemplateVersionMigration,
} from "./timeline-template.js";

export {
	buildSmartPackagingPlan,
	type SmartPackagingAction,
	type SmartPackagingBeat,
	type SmartPackagingCaption,
	type SmartPackagingOptions,
	type SmartPackagingPlan,
	type SmartPackagingShot,
} from "./smart-packaging.js";

export {
	SMART_PACKAGING_PROTOCOL_VERSION,
	buildSmartPackagingSnapshot,
	createSmartPackagingCloudJob,
	mergeSmartPackagingTimelinePatches,
	timelinePatchFromSmartPackagingPlan,
	transitionSmartPackagingCloudJob,
	validateSmartPackagingCloudJob,
	validateSmartPackagingSnapshot,
	type SmartPackagingAddCaptionOperation,
	type SmartPackagingAddSoundEffectOperation,
	type SmartPackagingAddStickerOperation,
	type SmartPackagingAddTextOverlayOperation,
	type SmartPackagingAssetReference,
	type SmartPackagingBasePatchOperation,
	type SmartPackagingCanvasSize,
	type SmartPackagingCloudJob,
	type SmartPackagingCloudJobError,
	type SmartPackagingJobStatus,
	type SmartPackagingProvider,
	type SmartPackagingProtocolIssue,
	type SmartPackagingProtocolVersion,
	type SmartPackagingSnapshot,
	type SmartPackagingSnapshotMedia,
	type SmartPackagingSnapshotMediaKind,
	type SmartPackagingSnapshotOptions,
	type SmartPackagingSnapshotProject,
	type SmartPackagingTimelinePatch,
	type SmartPackagingTimelinePatchOperation,
	type SmartPackagingTimelinePatchSource,
	type SmartPackagingUpdateMediaZoomOperation,
	type SmartPackagingUpsertTransitionOperation,
} from "./smart-packaging-protocol.js";
