export {
	TEMPLATE_ASPECT_RATIOS,
	TIMELINE_TEMPLATE_SCHEMA,
	TIMELINE_TEMPLATE_SCHEMA_VERSION,
	migrateTemplateSlotValues,
	migrateTimelineTemplate,
	resolveTemplateFontDependencies,
	resolveTimelineTemplateVariant,
	validateTemplateSlotValues,
	validateTimelineTemplate,
	type LegacyTimelineTemplateV1,
	type TemplateAspectRatio,
	type TemplateFontDependency,
	type TemplateInstanceBinding,
	type TemplateMediaPlacement,
	type TemplateMediaSlot,
	type TemplateTextPlacement,
	type TemplateTextSlot,
	type TimelineTemplate,
	type TimelineTemplateDocument,
	type TimelineTemplatePlacement,
	type TimelineTemplateSlot,
	type TimelineTemplateSlotValue,
	type TimelineTemplateSlotValues,
	type TimelineTemplateValidationCode,
	type TimelineTemplateValidationIssue,
	type TimelineTemplateValidationResult,
	type TimelineTemplateVariant,
	type TimelineTemplateVersionMigration,
} from "./timeline-template.js";

export {
	buildSmartPackagingPlan,
	type SmartPackagingAction,
	type SmartPackagingBeat,
	type SmartPackagingCaption,
	type SmartPackagingOptions,
	type SmartPackagingPlan,
	type SmartPackagingShot,
} from "./smart-packaging.js";
