/**
 * Image-to-video model definitions
 * @module electron/native-pipeline/registry-data/image-to-video
 */

import { ModelRegistry } from "../infra/registry.js";

/** Register all image-to-video models in the pipeline registry. */
export function registerImageToVideoModels(): void {
	ModelRegistry.register({
		key: "hailuo",
		name: "MiniMax Hailuo-02",
		provider: "MiniMax",
		endpoint: "fal-ai/minimax/hailuo-02/standard/image-to-video",
		categories: ["image_to_video"],
		description: "Standard image-to-video with prompt optimization",
		pricing: 0.05,
		durationOptions: ["6", "10"],
		resolutions: ["768p"],
		defaults: { duration: "6", prompt_optimizer: true },
		features: ["prompt_optimizer"],
		maxDuration: 10,
		extendedParams: ["start_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.08,
		processingTime: 60,
	});

	ModelRegistry.register({
		key: "kling_2_1",
		name: "Kling Video v2.1",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v2.1/standard/image-to-video",
		categories: ["image_to_video"],
		description:
			"High-quality generation with negative prompts and frame interpolation",
		pricing: 0.05,
		durationOptions: ["5", "10"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
		},
		features: ["negative_prompt", "cfg_scale", "frame_interpolation"],
		maxDuration: 10,
		extendedParams: ["start_frame", "end_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.5,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_2_6_pro_i2v",
		name: "Kling Video v2.6 Pro",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v2.6/pro/image-to-video",
		categories: ["image_to_video"],
		providerKey: "kling_2_6_pro",
		description:
			"Professional tier with enhanced quality and frame interpolation",
		pricing: 0.1,
		durationOptions: ["5", "10"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
		},
		features: [
			"negative_prompt",
			"cfg_scale",
			"professional_quality",
			"frame_interpolation",
		],
		maxDuration: 10,
		extendedParams: ["start_frame", "end_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 1.0,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "kling_3_standard_i2v",
		name: "Kling Video v3 Standard",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v3/standard/image-to-video",
		categories: ["image_to_video"],
		providerKey: "kling_3_standard",
		description:
			"Latest generation with native audio, voice control, and multi-prompt support",
		pricing: { no_audio: 0.168, audio: 0.252, voice_control: 0.308 },
		durationOptions: ["5", "10", "12"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
			generate_audio: false,
			voice_ids: [],
			multi_prompt: [],
			elements: [],
			aspect_ratio: "16:9",
		},
		features: [
			"negative_prompt",
			"cfg_scale",
			"frame_interpolation",
			"audio_generation",
			"voice_control",
			"multi_prompt",
			"custom_elements",
		],
		maxDuration: 12,
		extendedParams: ["start_frame", "end_frame", "audio_generate", "elements"],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: true,
			audio_input: false,
			audio_generate: true,
			ref_video: true,
		},
		costEstimate: 0.84,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_3_pro_i2v",
		name: "Kling Video v3 Pro",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v3/pro/image-to-video",
		categories: ["image_to_video"],
		providerKey: "kling_3_pro",
		description:
			"Top-tier cinematic visuals with native audio, voice control, and multi-prompt support",
		pricing: { no_audio: 0.224, audio: 0.336, voice_control: 0.392 },
		durationOptions: ["5", "10", "12"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
			generate_audio: false,
			voice_ids: [],
			multi_prompt: [],
			elements: [],
			aspect_ratio: "16:9",
		},
		features: [
			"negative_prompt",
			"cfg_scale",
			"professional_quality",
			"frame_interpolation",
			"audio_generation",
			"voice_control",
			"multi_prompt",
			"custom_elements",
		],
		maxDuration: 12,
		extendedParams: ["start_frame", "end_frame", "audio_generate", "elements"],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: true,
			audio_input: false,
			audio_generate: true,
			ref_video: true,
		},
		costEstimate: 1.12,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_o3_standard_i2v",
		name: "Kling O3 Standard Image-to-Video",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/o3/standard/image-to-video",
		categories: ["image_to_video"],
		description:
			"O3 (Omni) model with element-based character/object consistency",
		pricing: { no_audio: 0.168, audio: 0.224 },
		durationOptions: ["3", "5", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			generate_audio: true,
			elements: [],
			image_urls: [],
			aspect_ratio: "16:9",
			negative_prompt: null,
			cfg_scale: 0.5,
		},
		features: ["audio_generation", "elements", "end_frame", "reference_images"],
		maxDuration: 15,
		extendedParams: [
			"start_frame",
			"end_frame",
			"audio_generate",
			"elements",
			"image_urls",
		],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: true,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
			elements: true,
		},
		costEstimate: 0.84,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_o3_pro_i2v",
		name: "Kling O3 Pro Image-to-Video",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/o3/pro/image-to-video",
		categories: ["image_to_video"],
		description:
			"Professional O3 (Omni) model with enhanced quality and element consistency",
		pricing: { no_audio: 0.224, audio: 0.28 },
		durationOptions: ["3", "5", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			generate_audio: true,
			elements: [],
			image_urls: [],
			aspect_ratio: "16:9",
			negative_prompt: null,
			cfg_scale: 0.5,
		},
		features: [
			"audio_generation",
			"elements",
			"end_frame",
			"reference_images",
			"professional_quality",
		],
		maxDuration: 15,
		extendedParams: [
			"start_frame",
			"end_frame",
			"audio_generate",
			"elements",
			"image_urls",
		],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: true,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
			elements: true,
		},
		costEstimate: 1.12,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_o3_standard_ref",
		name: "Kling O3 Standard Reference-to-Video",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/o3/standard/reference-to-video",
		categories: ["image_to_video"],
		description:
			"O3 reference model with @ syntax for element-based character generation",
		pricing: { no_audio: 0.084, audio: 0.112 },
		durationOptions: ["3", "5", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			generate_audio: false,
			elements: [],
			image_urls: [],
			aspect_ratio: "16:9",
			multi_prompt: [],
			shot_type: null,
		},
		features: [
			"audio_generation",
			"elements",
			"reference_images",
			"reference_syntax",
			"multi_prompt",
		],
		maxDuration: 15,
		extendedParams: ["start_frame", "audio_generate", "elements", "image_urls"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: true,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
			elements: true,
		},
		costEstimate: 0.42,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_o3_pro_ref",
		name: "Kling O3 Pro Reference-to-Video",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/o3/pro/reference-to-video",
		categories: ["image_to_video"],
		description:
			"Professional O3 reference model with @ syntax and enhanced quality",
		pricing: { no_audio: 0.224, audio: 0.28 },
		durationOptions: ["3", "5", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			generate_audio: false,
			elements: [],
			image_urls: [],
			aspect_ratio: "16:9",
		},
		features: [
			"audio_generation",
			"elements",
			"end_frame",
			"reference_images",
			"reference_syntax",
			"professional_quality",
		],
		maxDuration: 15,
		extendedParams: [
			"start_frame",
			"end_frame",
			"audio_generate",
			"elements",
			"image_urls",
		],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: true,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
			elements: true,
		},
		costEstimate: 1.12,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "seedance_1_5_pro",
		name: "ByteDance Seedance v1.5 Pro",
		provider: "ByteDance",
		endpoint: "fal-ai/bytedance/seedance/v1.5/pro/image-to-video",
		categories: ["image_to_video"],
		description: "Advanced motion synthesis with seed control",
		pricing: 0.08,
		durationOptions: ["5", "10"],
		resolutions: ["720p", "1080p"],
		defaults: { duration: "5", seed: null },
		features: ["seed_control", "motion_quality"],
		maxDuration: 10,
		extendedParams: ["start_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.8,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "sora_2_i2v",
		name: "Sora 2",
		provider: "OpenAI (via FAL)",
		endpoint: "fal-ai/sora-2/image-to-video",
		categories: ["image_to_video"],
		providerKey: "sora_2",
		description: "OpenAI's image-to-video model",
		pricing: 0.1,
		durationOptions: [4, 8, 12],
		aspectRatios: ["auto", "9:16", "16:9"],
		resolutions: ["auto", "720p"],
		defaults: {
			duration: 4,
			resolution: "auto",
			aspect_ratio: "auto",
			delete_video: true,
		},
		features: ["aspect_ratio", "resolution"],
		maxDuration: 12,
		extendedParams: ["start_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.4,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "sora_2_pro_i2v",
		name: "Sora 2 Pro",
		provider: "OpenAI (via FAL)",
		endpoint: "fal-ai/sora-2/image-to-video/pro",
		categories: ["image_to_video"],
		providerKey: "sora_2_pro",
		description: "Professional Sora with 1080p support",
		pricing: 0.3,
		durationOptions: [4, 8, 12],
		aspectRatios: ["auto", "9:16", "16:9"],
		resolutions: ["auto", "720p", "1080p"],
		defaults: {
			duration: 4,
			resolution: "auto",
			aspect_ratio: "auto",
			delete_video: true,
		},
		features: ["aspect_ratio", "resolution", "1080p"],
		maxDuration: 12,
		extendedParams: ["start_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 2.0,
		processingTime: 180,
	});

	ModelRegistry.register({
		key: "veo_3_1_fast",
		name: "Veo 3.1 Fast",
		provider: "Google (via FAL)",
		endpoint: "fal-ai/veo3.1/fast/image-to-video",
		categories: ["image_to_video"],
		description: "Fast video generation with optional audio",
		pricing: 0.1,
		durationOptions: ["4s", "6s", "8s"],
		aspectRatios: ["auto", "16:9", "9:16"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "8s",
			resolution: "720p",
			aspect_ratio: "auto",
			generate_audio: true,
			auto_fix: false,
		},
		features: ["audio_generation", "auto_fix", "fast_processing"],
		maxDuration: 8,
		extendedParams: ["start_frame", "audio_generate"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
		},
		costEstimate: 1.2,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "veo_3_1_lite",
		name: "Veo 3.1 Lite",
		provider: "Google (via FAL)",
		endpoint: "fal-ai/veo3.1/lite/image-to-video",
		categories: ["image_to_video"],
		description: "Budget video generation with mandatory audio",
		pricing: {
			type: "per_second",
			cost_720p: 0.05,
			cost_1080p: 0.08,
		},
		durationOptions: ["4s", "6s", "8s"],
		aspectRatios: ["auto", "16:9", "9:16"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "8s",
			resolution: "720p",
			aspect_ratio: "auto",
			generate_audio: true,
			auto_fix: false,
		},
		features: ["audio_generation", "auto_fix", "budget_tier"],
		maxDuration: 8,
		extendedParams: ["start_frame", "audio_generate"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
		},
		costEstimate: 0.4,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "wan_2_6",
		name: "Wan v2.6",
		provider: "Wan",
		endpoint: "wan/v2.6/image-to-video",
		categories: ["image_to_video"],
		description: "High-quality image-to-video with multi-shot support",
		pricing: 0.1,
		durationOptions: ["5", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			resolution: "1080p",
			negative_prompt: "",
			enable_prompt_expansion: true,
			multi_shots: false,
			seed: null,
			enable_safety_checker: true,
		},
		features: [
			"prompt_expansion",
			"multi_shots",
			"audio_input",
			"seed_control",
			"safety_checker",
		],
		maxDuration: 15,
		extendedParams: ["start_frame", "audio_input"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: true,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.5,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "ltx23_fast_i2v",
		name: "LTX Video 2.3 Fast I2V",
		provider: "Lightricks (via FAL)",
		endpoint: "fal-ai/ltx-2.3/image-to-video/fast",
		categories: ["image_to_video"],
		description:
			"Image-to-video with 4K, audio, and end-frame transitions (6-20s)",
		pricing: {
			type: "per_second",
			cost_1080p: 0.04,
			cost_1440p: 0.08,
			cost_2160p: 0.16,
		},
		durationOptions: ["6", "8", "10", "12", "14", "16", "18", "20"],
		aspectRatios: ["16:9", "9:16", "auto"],
		resolutions: ["1080p", "1440p", "2160p"],
		defaults: {
			duration: 6,
			resolution: "1080p",
			aspect_ratio: "16:9",
			fps: 25,
			generate_audio: true,
		},
		features: [
			"audio_generation",
			"4k_resolution",
			"long_duration",
			"end_frame",
			"aspect_ratio",
			"fps_control",
			"fast_processing",
		],
		maxDuration: 20,
		extendedParams: ["start_frame", "end_frame", "audio_generate"],
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: false,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
		},
		costEstimate: 0.24,
		processingTime: 60,
	});

	ModelRegistry.register({
		key: "pixverse_v6",
		name: "PixVerse v6",
		provider: "PixVerse",
		endpoint: "fal-ai/pixverse/v6/image-to-video",
		categories: ["image_to_video"],
		description:
			"Stylized image-to-video with audio, style presets, and multi-clip",
		pricing: {
			type: "per_second",
			cost_360p: 0.025,
			cost_540p: 0.035,
			cost_720p: 0.045,
			cost_1080p: 0.09,
		},
		durationOptions: ["5", "8", "10", "15"],
		resolutions: ["360p", "540p", "720p", "1080p"],
		defaults: {
			duration: "5",
			resolution: "720p",
			thinking_type: "auto",
		},
		features: [
			"audio_generation",
			"style_presets",
			"multi_clip",
			"seed_control",
			"negative_prompt",
		],
		maxDuration: 15,
		extendedParams: ["start_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
		},
		costEstimate: 0.23,
		processingTime: 45,
	});

	ModelRegistry.register({
		key: "grok_imagine_i2v",
		name: "xAI Grok Imagine Video",
		provider: "xAI (via FAL)",
		endpoint: "xai/grok-imagine-video/image-to-video",
		categories: ["image_to_video"],
		providerKey: "grok_imagine",
		description: "xAI's image-to-video with native audio generation",
		pricing: 0.05,
		durationOptions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
		aspectRatios: ["auto", "16:9", "4:3", "3:2", "1:1", "2:3", "3:4", "9:16"],
		resolutions: ["480p", "720p"],
		defaults: { duration: 6, resolution: "720p", aspect_ratio: "auto" },
		features: [
			"audio_generation",
			"flexible_duration",
			"multiple_aspect_ratios",
		],
		maxDuration: 15,
		extendedParams: ["start_frame"],
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.302,
		processingTime: 60,
	});

	ModelRegistry.register({
		key: "grok_imagine_r2v_i2v",
		name: "xAI Grok Imagine Reference-to-Video",
		provider: "xAI (via FAL)",
		endpoint: "xai/grok-imagine-video/reference-to-video",
		categories: ["image_to_video"],
		providerKey: "grok_imagine",
		description:
			"xAI's reference-to-video using up to 7 reference images to guide generation",
		pricing: 0.05,
		durationOptions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		aspectRatios: ["16:9", "4:3", "3:2", "1:1", "2:3", "3:4", "9:16"],
		resolutions: ["480p", "720p"],
		defaults: { duration: 8, resolution: "480p", aspect_ratio: "16:9" },
		features: [
			"reference_images",
			"flexible_duration",
			"multiple_aspect_ratios",
		],
		maxDuration: 10,
		extendedParams: ["image_urls"],
		extendedFeatures: {
			start_frame: false,
			end_frame: false,
			ref_images: true,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.302,
		processingTime: 60,
	});

	// --- GMI Cloud models ---

	ModelRegistry.register({
		key: "gmi_veo31_lite_i2v",
		name: "Veo 3.1 Lite I2V (GMI)",
		provider: "Google (via GMI)",
		endpoint: "veo-3.1-lite-generate-001",
		categories: ["image_to_video"],
		description:
			"Image-to-video with first/last frame guidance and built-in audio",
		pricing: {
			"720p_audio": 0.05,
			"1080p_audio": 0.08,
			"720p": 0.03,
			"1080p": 0.05,
		},
		durationOptions: ["4", "6", "8"],
		aspectRatios: ["16:9", "9:16"],
		resolutions: ["720p", "1080p"],
		defaults: { durationSeconds: 8, aspectRatio: "16:9", generateAudio: true },
		features: ["audio_generation", "seed", "last_frame"],
		maxDuration: 8,
		inputRequirements: {
			required: ["prompt", "image"],
			optional: [
				"lastFrame",
				"durationSeconds",
				"aspectRatio",
				"generateAudio",
				"seed",
			],
		},
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: false,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
		},
		costEstimate: 0.4,
		processingTime: 90,
		providerBackend: "gmi",
	});

	ModelRegistry.register({
		key: "gmi_skyreels_v4_i2v",
		name: "SkyReels V4 I2V (GMI)",
		provider: "SkyReels (via GMI)",
		endpoint: "skyreels-v4-image-to-video",
		categories: ["image_to_video"],
		description: "Animate images into video with optional sound effects",
		pricing: { per_second: 0.14 },
		durationOptions: ["3", "5", "8", "10", "15"],
		resolutions: ["1080p"],
		defaults: { duration: 5, sound: false, mode: "std" },
		features: ["sound_effects", "flexible_duration"],
		maxDuration: 15,
		inputRequirements: {
			required: ["prompt", "first_frame_image"],
			optional: ["duration", "sound", "mode"],
		},
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0.7,
		processingTime: 90,
		providerBackend: "gmi",
	});

	ModelRegistry.register({
		key: "gmi_kling_v3_i2v",
		name: "Kling V3 I2V (GMI)",
		provider: "Kling (via GMI)",
		endpoint: "kling-v3-image-to-video",
		categories: ["image_to_video"],
		description:
			"Kling V3 image-to-video with end-frame guidance and native audio",
		pricing: { no_sound: 0.168, with_sound: 0.252 },
		durationOptions: ["3", "5", "8", "10", "15"],
		resolutions: ["720p"],
		defaults: { duration: "5" },
		features: ["audio_generation", "negative_prompt", "end_frame"],
		maxDuration: 15,
		inputRequirements: {
			required: ["prompt", "image"],
			optional: ["image_tail", "negative_prompt", "duration", "sound"],
		},
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: false,
			audio_input: false,
			audio_generate: true,
			ref_video: false,
		},
		costEstimate: 0.84,
		processingTime: 90,
		providerBackend: "gmi",
	});

	ModelRegistry.register({
		key: "gmi_kling_v3_omni_i2v",
		name: "Kling V3 Omni I2V (GMI)",
		provider: "Kling (via GMI)",
		endpoint: "kling-v3-omni",
		categories: ["image_to_video"],
		description:
			"Kling V3 Omni image-to-video with end-frame, audio, and elements",
		pricing: { std: 0.084, std_sound: 0.112, pro: 0.112, pro_sound: 0.14 },
		durationOptions: ["3", "5", "8", "10", "15"],
		resolutions: ["720p", "1080p"],
		defaults: { duration: "5", mode: "pro" },
		features: ["audio_generation", "multi_mode", "element_driven", "end_frame"],
		maxDuration: 15,
		inputRequirements: {
			required: ["prompt", "image_list"],
			optional: ["mode", "duration", "sound", "element_list"],
		},
		extendedFeatures: {
			start_frame: true,
			end_frame: true,
			ref_images: false,
			audio_input: false,
			audio_generate: true,
			ref_video: true,
		},
		costEstimate: 0.56,
		processingTime: 90,
		providerBackend: "gmi",
	});

	ModelRegistry.register({
		key: "gmi_kling_motion_control",
		name: "Kling 3 Motion Control (GMI)",
		provider: "Kling (via GMI)",
		endpoint: "kling-3-motion-control",
		categories: ["image_to_video", "motion_transfer"],
		description: "Transfer motion from a reference video to a character image",
		pricing: { std: 0.126, pro: 0.168 },
		durationOptions: ["5", "10", "15", "20", "30"],
		defaults: { mode: "std", character_orientation: "video" },
		features: ["motion_transfer", "keep_audio", "prompt_style_guide"],
		maxDuration: 30,
		inputRequirements: {
			required: ["image_url", "video_url"],
			optional: [
				"character_orientation",
				"mode",
				"keep_original_sound",
				"prompt",
			],
		},
		extendedFeatures: {
			start_frame: true,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: true,
		},
		costEstimate: 1.26,
		processingTime: 120,
		providerBackend: "gmi",
	});
}
