/**
 * Text-to-video model definitions
 * @module electron/native-pipeline/registry-data/text-to-video
 */

import { ModelRegistry } from "../infra/registry.js";

export function registerTextToVideoModels(): void {
	ModelRegistry.register({
		key: "hailuo_pro",
		name: "MiniMax Hailuo-02 Pro",
		provider: "MiniMax",
		endpoint: "fal-ai/minimax/hailuo-02/pro/text-to-video",
		categories: ["text_to_video"],
		description: "Cost-effective text-to-video with prompt optimization",
		pricing: { type: "per_video", cost: 0.08 },
		durationOptions: ["6"],
		aspectRatios: ["16:9"],
		resolutions: ["1080p"],
		defaults: { prompt_optimizer: true },
		features: ["prompt_optimizer", "1080p", "cost_effective"],
		maxDuration: 6,
		costEstimate: 0.08,
		processingTime: 60,
	});

	ModelRegistry.register({
		key: "veo3",
		name: "Google Veo 3",
		provider: "Google (via FAL)",
		endpoint: "fal-ai/veo3",
		categories: ["text_to_video"],
		description: "Premium quality with audio generation",
		pricing: { type: "per_second", cost_no_audio: 0.5, cost_with_audio: 0.75 },
		durationOptions: ["5s", "6s", "7s", "8s"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			duration: "8s",
			aspect_ratio: "16:9",
			generate_audio: true,
			enhance_prompt: true,
		},
		features: [
			"audio_generation",
			"enhance_prompt",
			"negative_prompt",
			"seed_control",
		],
		maxDuration: 8,
		costEstimate: 4.0,
		processingTime: 300,
	});

	ModelRegistry.register({
		key: "veo3_fast",
		name: "Google Veo 3 Fast",
		provider: "Google (via FAL)",
		endpoint: "fal-ai/veo3/fast",
		categories: ["text_to_video"],
		description: "Fast generation with good quality",
		pricing: { type: "per_second", cost_no_audio: 0.25, cost_with_audio: 0.4 },
		durationOptions: ["5s", "6s", "7s", "8s"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: { duration: "8s", aspect_ratio: "16:9", generate_audio: true },
		features: ["audio_generation", "fast_processing", "seed_control"],
		maxDuration: 8,
		costEstimate: 2.0,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "kling_2_6_pro",
		name: "Kling Video v2.6 Pro",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v2.6/pro/text-to-video",
		categories: ["text_to_video"],
		description: "Professional text-to-video with audio support",
		pricing: { type: "per_second", cost_no_audio: 0.07, cost_with_audio: 0.14 },
		durationOptions: ["5", "10"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			duration: "5",
			aspect_ratio: "16:9",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
			generate_audio: true,
		},
		features: [
			"audio_generation",
			"negative_prompt",
			"cfg_scale",
			"multilingual",
		],
		maxDuration: 10,
		costEstimate: 0.35,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_3_standard",
		name: "Kling Video v3 Standard",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v3/standard/text-to-video",
		categories: ["text_to_video"],
		description:
			"Latest generation with native audio, voice control, and multi-prompt support",
		pricing: {
			type: "per_second",
			cost_no_audio: 0.168,
			cost_with_audio: 0.252,
			cost_voice_control: 0.308,
		},
		durationOptions: [
			"3",
			"4",
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
			"11",
			"12",
			"13",
			"14",
			"15",
		],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			duration: "5",
			aspect_ratio: "16:9",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
			generate_audio: false,
			voice_ids: [],
			multi_prompt: [],
			shot_type: null,
		},
		features: [
			"audio_generation",
			"voice_control",
			"multi_prompt",
			"shot_type",
			"negative_prompt",
			"cfg_scale",
			"multilingual",
		],
		maxDuration: 15,
		costEstimate: 0.84,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_3_pro",
		name: "Kling Video v3 Pro",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v3/pro/text-to-video",
		categories: ["text_to_video"],
		description:
			"Top-tier cinematic visuals with native audio, voice control, and multi-prompt support",
		pricing: {
			type: "per_second",
			cost_no_audio: 0.224,
			cost_with_audio: 0.336,
			cost_voice_control: 0.392,
		},
		durationOptions: [
			"3",
			"4",
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
			"11",
			"12",
			"13",
			"14",
			"15",
		],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			duration: "5",
			aspect_ratio: "16:9",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
			generate_audio: false,
			voice_ids: [],
			multi_prompt: [],
			shot_type: null,
		},
		features: [
			"audio_generation",
			"voice_control",
			"multi_prompt",
			"shot_type",
			"negative_prompt",
			"cfg_scale",
			"multilingual",
			"professional_quality",
		],
		maxDuration: 15,
		costEstimate: 1.12,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_o3_pro_t2v",
		name: "Kling O3 Pro Text-to-Video",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/o3/pro/text-to-video",
		categories: ["text_to_video"],
		description:
			"O3 (Omni) model with element-based character/object consistency and @ reference syntax",
		pricing: {
			type: "per_second",
			cost_no_audio: 0.224,
			cost_with_audio: 0.28,
		},
		durationOptions: ["3", "5", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			aspect_ratio: "16:9",
			negative_prompt: null,
			cfg_scale: 0.5,
			generate_audio: true,
			elements: [],
			image_urls: [],
			multi_prompt: [],
			shot_type: null,
		},
		features: [
			"audio_generation",
			"elements",
			"reference_images",
			"reference_syntax",
			"multi_prompt",
			"shot_type",
			"negative_prompt",
			"cfg_scale",
			"professional_quality",
		],
		maxDuration: 15,
		costEstimate: 1.12,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "luma_ray_3_2",
		name: "Luma Ray 3.2",
		provider: "Luma Agents",
		endpoint: "generations",
		categories: ["text_to_video"],
		description:
			"Ray 3.2 text-to-video and image-anchored video via Luma Agents",
		pricing: { type: "external", provider: "luma_agents" },
		durationOptions: ["5s", "10s"],
		aspectRatios: ["9:16", "3:4", "1:1", "4:3", "16:9", "21:9"],
		resolutions: ["540p", "720p", "1080p"],
		providerBackend: "luma",
		defaults: {
			model: "ray-3.2",
			type: "video",
			aspect_ratio: "16:9",
			duration: "5s",
			resolution: "720p",
		},
		features: [
			"text_to_video",
			"image_to_video",
			"start_frame",
			"end_frame",
			"loop",
			"hdr",
			"exr_export",
		],
		maxDuration: 10,
		costEstimate: 0,
		processingTime: 300,
	});

	ModelRegistry.register({
		key: "sora_2",
		name: "Sora 2",
		provider: "OpenAI (via FAL)",
		endpoint: "fal-ai/sora-2/text-to-video",
		categories: ["text_to_video"],
		description: "OpenAI's text-to-video model",
		pricing: { type: "per_second", cost: 0.1 },
		durationOptions: ["4", "8", "12"],
		aspectRatios: ["16:9", "9:16"],
		resolutions: ["720p"],
		defaults: {
			duration: "4",
			resolution: "720p",
			aspect_ratio: "16:9",
			delete_video: true,
		},
		features: ["aspect_ratio", "long_duration"],
		maxDuration: 12,
		costEstimate: 0.4,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "sora_2_pro",
		name: "Sora 2 Pro",
		provider: "OpenAI (via FAL)",
		endpoint: "fal-ai/sora-2/text-to-video/pro",
		categories: ["text_to_video"],
		description: "Professional Sora with 1080p support",
		pricing: { type: "per_second", cost_720p: 0.3, cost_1080p: 0.5 },
		durationOptions: ["4", "8", "12"],
		aspectRatios: ["16:9", "9:16"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "4",
			resolution: "1080p",
			aspect_ratio: "16:9",
			delete_video: true,
		},
		features: ["aspect_ratio", "1080p", "long_duration"],
		maxDuration: 12,
		costEstimate: 2.0,
		processingTime: 180,
	});

	ModelRegistry.register({
		key: "ltx23_pro_t2v",
		name: "LTX Video 2.3 Pro T2V",
		provider: "Lightricks (via FAL)",
		endpoint: "fal-ai/ltx-2.3/text-to-video",
		categories: ["text_to_video"],
		description: "Text-to-video with native audio and 4K support (6-10s)",
		pricing: {
			type: "per_second",
			cost_1080p: 0.06,
			cost_1440p: 0.12,
			cost_2160p: 0.24,
		},
		durationOptions: ["6", "8", "10"],
		aspectRatios: ["16:9", "9:16"],
		resolutions: ["1080p", "1440p", "2160p"],
		defaults: {
			duration: 6,
			resolution: "1080p",
			aspect_ratio: "16:9",
			fps: 25,
			generate_audio: true,
		},
		features: [
			"audio_generation",
			"4k_resolution",
			"aspect_ratio",
			"fps_control",
		],
		maxDuration: 10,
		costEstimate: 0.36,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "ltx23_fast_t2v",
		name: "LTX Video 2.3 Fast T2V",
		provider: "Lightricks (via FAL)",
		endpoint: "fal-ai/ltx-2.3/text-to-video/fast",
		categories: ["text_to_video"],
		description:
			"Fast text-to-video with 4K support and native audio, up to 20s",
		pricing: {
			type: "per_second",
			cost_1080p: 0.04,
			cost_1440p: 0.08,
			cost_2160p: 0.16,
		},
		durationOptions: ["6", "8", "10", "12", "14", "16", "18", "20"],
		aspectRatios: ["16:9", "9:16"],
		resolutions: ["1080p", "1440p", "2160p"],
		defaults: {
			duration: 6,
			resolution: "1080p",
			aspect_ratio: "16:9",
			fps: 25,
			generate_audio: true,
		},
		features: [
			"audio_generation",
			"4k_resolution",
			"long_duration",
			"aspect_ratio",
			"fps_control",
			"fast_processing",
		],
		maxDuration: 20,
		costEstimate: 0.24,
		processingTime: 60,
	});

	ModelRegistry.register({
		key: "ltx23_a2v",
		name: "LTX Video 2.3 Audio-to-Video",
		provider: "Lightricks (via FAL)",
		endpoint: "fal-ai/ltx-2.3/audio-to-video",
		categories: ["text_to_video"],
		description: "Generate video from audio input with text guidance (6-10s)",
		pricing: { type: "per_second", cost: 0.1 },
		durationOptions: ["6", "8", "10"],
		resolutions: ["1080p"],
		defaults: {
			duration: 6,
			resolution: "1080p",
			guidance_scale: 7,
		},
		features: ["audio_input", "text_guidance"],
		maxDuration: 10,
		costEstimate: 0.6,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "grok_imagine",
		name: "xAI Grok Imagine Video",
		provider: "xAI (via FAL)",
		endpoint: "xai/grok-imagine-video/text-to-video",
		categories: ["text_to_video"],
		description: "xAI's text-to-video with native audio generation",
		pricing: {
			type: "per_second",
			base_duration: 6,
			base_cost_6s: 0.3,
			cost_per_additional_second: 0.05,
		},
		durationOptions: [
			"1",
			"2",
			"3",
			"4",
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
			"11",
			"12",
			"13",
			"14",
			"15",
		],
		aspectRatios: ["16:9", "4:3", "3:2", "1:1", "2:3", "3:4", "9:16"],
		resolutions: ["480p", "720p"],
		defaults: { duration: "6", resolution: "720p", aspect_ratio: "16:9" },
		features: [
			"audio_generation",
			"flexible_duration",
			"multiple_aspect_ratios",
		],
		maxDuration: 15,
		costEstimate: 0.3,
		processingTime: 60,
	});

	// --- GMI Cloud models ---

	ModelRegistry.register({
		key: "gmi_veo31_lite_t2v",
		name: "Veo 3.1 Lite (GMI)",
		provider: "Google (via GMI)",
		endpoint: "veo-3.1-lite-generate-001",
		categories: ["text_to_video"],
		description: "Cost-effective Veo 3.1 Lite with built-in audio generation",
		pricing: {
			"720p_audio": 0.05,
			"1080p_audio": 0.08,
			"720p": 0.03,
			"1080p": 0.05,
		},
		durationOptions: ["4", "6", "8"],
		aspectRatios: ["16:9", "9:16"],
		resolutions: ["720p", "1080p"],
		defaults: { durationSeconds: 8, aspectRatio: "16:9", generateAudio: true },
		features: ["audio_generation", "seed"],
		maxDuration: 8,
		costEstimate: 0.4,
		processingTime: 90,
		providerBackend: "gmi",
	});

	ModelRegistry.register({
		key: "gmi_skyreels_v4_t2v",
		name: "SkyReels V4 T2V (GMI)",
		provider: "SkyReels (via GMI)",
		endpoint: "skyreels-v4-text-to-video",
		categories: ["text_to_video"],
		description: "High-quality text-to-video with optional sound effects",
		pricing: { per_second: 0.14 },
		durationOptions: ["3", "5", "8", "10", "15"],
		aspectRatios: ["16:9", "4:3", "1:1", "9:16", "3:4"],
		resolutions: ["1080p"],
		defaults: { duration: 5, aspect_ratio: "16:9", sound: false, mode: "std" },
		features: ["sound_effects", "flexible_duration", "multiple_aspect_ratios"],
		maxDuration: 15,
		costEstimate: 0.7,
		processingTime: 90,
		providerBackend: "gmi",
	});

	ModelRegistry.register({
		key: "gmi_kling_v3_t2v",
		name: "Kling V3 T2V (GMI)",
		provider: "Kling (via GMI)",
		endpoint: "kling-v3-text-to-video",
		categories: ["text_to_video"],
		description: "Kling V3 text-to-video with native audio and 3-15s duration",
		pricing: { no_sound: 0.168, with_sound: 0.252 },
		durationOptions: ["3", "5", "8", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: { duration: "5", aspect_ratio: "16:9" },
		features: ["audio_generation", "negative_prompt"],
		maxDuration: 15,
		costEstimate: 0.84,
		processingTime: 90,
		providerBackend: "gmi",
	});

	ModelRegistry.register({
		key: "gmi_kling_v3_omni_t2v",
		name: "Kling V3 Omni (GMI)",
		provider: "Kling (via GMI)",
		endpoint: "kling-v3-omni",
		categories: ["text_to_video"],
		description: "Unified Kling V3 Omni with std/pro modes and native audio",
		pricing: { std: 0.084, std_sound: 0.112, pro: 0.112, pro_sound: 0.14 },
		durationOptions: ["3", "5", "8", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: { duration: "5", mode: "pro", aspect_ratio: "16:9" },
		features: ["audio_generation", "multi_mode", "element_driven"],
		maxDuration: 15,
		costEstimate: 0.56,
		processingTime: 90,
		providerBackend: "gmi",
	});

	ModelRegistry.register({
		key: "seedance_2_0",
		name: "ByteDance Seedance 2.0",
		provider: "ByteDance",
		endpoint: "fal-ai/bytedance/seedance-2.0/text-to-video",
		categories: ["text_to_video"],
		description:
			"Cinematic video with native audio, physics, and camera control",
		pricing: { type: "per_video", cost: 0.3 },
		durationOptions: ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
		aspectRatios: ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"],
		resolutions: ["720p", "1080p"],
		defaults: { duration: "5", resolution: "1080p", aspect_ratio: "16:9" },
		features: ["native_audio", "camera_control", "physics", "seed"],
		maxDuration: 12,
		costEstimate: 0.3,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "gmi_seedance_2_0_260128_t2v",
		name: "ByteDance Seedance 2.0 260128 T2V (GMI)",
		provider: "ByteDance (via GMI)",
		endpoint: "seedance-2-0-260128",
		categories: ["text_to_video"],
		description:
			"Next-gen Seedance with native audio, reference assets, and 4-15s durations via GMI Cloud",
		pricing: { per_second: 0.052 },
		durationOptions: [
			"4",
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
			"11",
			"12",
			"13",
			"14",
			"15",
		],
		aspectRatios: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "adaptive"],
		resolutions: ["480p", "720p", "1080p"],
		defaults: {
			duration: 5,
			resolution: "720p",
			ratio: "16:9",
			generate_audio: true,
			watermark: false,
			web_search: false,
		},
		features: [
			"audio_generation",
			"reference_images",
			"reference_videos",
			"reference_audios",
			"seed_control",
			"web_search",
			"watermark_toggle",
			"flexible_duration",
			"multiple_aspect_ratios",
		],
		maxDuration: 15,
		costEstimate: 0.26,
		processingTime: 120,
		providerBackend: "gmi",
	});

	ModelRegistry.register({
		key: "gmi_seedance_2_0_fast_260128_t2v",
		name: "ByteDance Seedance 2.0 Fast 260128 T2V (GMI)",
		provider: "ByteDance (via GMI)",
		endpoint: "seedance-2-0-fast-260128",
		categories: ["text_to_video"],
		description:
			"Lower-latency Seedance 2.0 260128 variant — 480p/720p only (no 1080p), priced for drafts",
		pricing: { per_second: 0.022 },
		durationOptions: [
			"4",
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
			"11",
			"12",
			"13",
			"14",
			"15",
		],
		aspectRatios: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "adaptive"],
		resolutions: ["480p", "720p"],
		defaults: {
			duration: 5,
			resolution: "720p",
			ratio: "16:9",
			generate_audio: true,
			watermark: false,
			web_search: false,
		},
		features: [
			"audio_generation",
			"reference_images",
			"reference_videos",
			"reference_audios",
			"seed_control",
			"web_search",
			"watermark_toggle",
			"flexible_duration",
			"multiple_aspect_ratios",
		],
		maxDuration: 15,
		costEstimate: 0.11,
		processingTime: 60,
		providerBackend: "gmi",
	});

	// IMA Router (api.imarouter.com) — direct ByteDance Seedance 2.0 routing.
	// Submit `POST /v1/videos` + poll `GET /v1/videos/{task_id}`. Channel
	// matters: overseas (`seedance-2.0`, `seedance-2.0-fast`) and CN
	// (`-cn` suffix) cannot share asset groups. See
	// docs/task/seedance-imarouter/imarouter-integration-plan.md.
	ModelRegistry.register({
		key: "imarouter_seedance_2_0_t2v",
		name: "ByteDance Seedance 2.0 T2V (IMA Router)",
		provider: "ByteDance (via IMA Router)",
		endpoint: "v1/videos",
		categories: ["text_to_video"],
		description:
			"Seedance 2.0 full quality via IMA Router overseas — 720p / 1080p, 5–15s, native audio toggle",
		pricing: { type: "per_video", cost: 0.3 },
		durationOptions: [
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
			"11",
			"12",
			"13",
			"14",
			"15",
		],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			model: "seedance-2.0",
			duration: 5,
			resolution: "1080p",
			aspect_ratio: "16:9",
		},
		features: [
			"native_audio",
			"reference_images",
			"reference_videos",
			"reference_audios",
		],
		maxDuration: 15,
		costEstimate: 0.3,
		processingTime: 120,
		providerBackend: "imarouter",
	});

	ModelRegistry.register({
		key: "imarouter_seedance_2_0_fast_t2v",
		name: "ByteDance Seedance 2.0 Fast T2V (IMA Router)",
		provider: "ByteDance (via IMA Router)",
		endpoint: "v1/videos",
		categories: ["text_to_video"],
		description:
			"Lower-latency Seedance 2.0 via IMA Router overseas — 720p ONLY (1080p rejected with unsupported_resolution_for_fast_variant), 5–10s",
		pricing: { type: "per_video", cost: 0.12 },
		durationOptions: ["5", "6", "7", "8", "9", "10"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			model: "seedance-2.0-fast",
			duration: 5,
			resolution: "720p",
			aspect_ratio: "16:9",
		},
		features: [
			"native_audio",
			"reference_images",
			"reference_videos",
			"reference_audios",
		],
		maxDuration: 10,
		costEstimate: 0.12,
		processingTime: 60,
		providerBackend: "imarouter",
	});

	// CN variants — mainland China endpoints. `model: "seedance-2.0-cn"` /
	// `"seedance-2.0-fast-cn"` and the asset upload model `ima-pro-upload-cn`
	// must match: overseas group ids cannot consume CN `asset://...` refs.
	ModelRegistry.register({
		key: "imarouter_seedance_2_0_cn_t2v",
		name: "ByteDance Seedance 2.0 T2V (IMA Router CN)",
		provider: "ByteDance (via IMA Router CN)",
		endpoint: "v1/videos",
		categories: ["text_to_video"],
		description:
			"Seedance 2.0 full quality via IMA Router mainland China — 720p / 1080p, 5–15s",
		pricing: { type: "per_video", cost: 0.3 },
		durationOptions: [
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
			"11",
			"12",
			"13",
			"14",
			"15",
		],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			model: "seedance-2.0-cn",
			duration: 5,
			resolution: "1080p",
			aspect_ratio: "16:9",
		},
		features: [
			"native_audio",
			"reference_images",
			"reference_videos",
			"reference_audios",
		],
		maxDuration: 15,
		costEstimate: 0.3,
		processingTime: 120,
		providerBackend: "imarouter",
	});

	ModelRegistry.register({
		key: "imarouter_seedance_2_0_fast_cn_t2v",
		name: "ByteDance Seedance 2.0 Fast T2V (IMA Router CN)",
		provider: "ByteDance (via IMA Router CN)",
		endpoint: "v1/videos",
		categories: ["text_to_video"],
		description:
			"Lower-latency Seedance 2.0 via IMA Router mainland China — 720p ONLY, 5–10s",
		pricing: { type: "per_video", cost: 0.12 },
		durationOptions: ["5", "6", "7", "8", "9", "10"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			model: "seedance-2.0-fast-cn",
			duration: 5,
			resolution: "720p",
			aspect_ratio: "16:9",
		},
		features: [
			"native_audio",
			"reference_images",
			"reference_videos",
			"reference_audios",
		],
		maxDuration: 10,
		costEstimate: 0.12,
		processingTime: 60,
		providerBackend: "imarouter",
	});

	// Alibaba Happy Horse — text-to-video. Supports 5 aspect ratios, 720p/1080p,
	// duration 3–15s. FAL requires `duration` as an integer literal enum (3–15);
	// the string form is rejected with literal_error (verified live 2026-04-30).
	// See docs/task/fal_model/happy-horse-integration.md
	ModelRegistry.register({
		key: "happy_horse_t2v",
		name: "Alibaba Happy Horse T2V",
		provider: "Alibaba (via FAL)",
		endpoint: "alibaba/happy-horse/text-to-video",
		categories: ["text_to_video"],
		description:
			"Alibaba Happy Horse text-to-video — 720p/1080p, 3–15s, 5 aspect ratios",
		pricing: { type: "per_second", cost: null as unknown as number },
		// FAL accepts integer literals 3–15 (verified live — string form
		// returns literal_error). Keep durationOptions as numbers so the
		// CLI/UI surface them without coercion.
		durationOptions: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
		aspectRatios: ["16:9", "9:16", "1:1", "4:3", "3:4"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: 5,
			resolution: "1080p",
			aspect_ratio: "16:9",
			enable_safety_checker: true,
		},
		features: ["multi_aspect", "seed_control"],
		maxDuration: 15,
		inputRequirements: {
			required: ["prompt"],
			optional: [
				"duration",
				"resolution",
				"aspect_ratio",
				"seed",
				"enable_safety_checker",
			],
		},
		extendedFeatures: {
			start_frame: false,
			end_frame: false,
			ref_images: false,
			audio_input: false,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 0,
		processingTime: 60,
	});

	// Alibaba Wan AI Happy Horse 1.0 — text-to-video via GMI Cloud
	// (request-queue API at console.gmicloud.ai). Sibling of `happy_horse_t2v`
	// which is FAL-backed; GMI uses different field names (`ratio` not
	// `aspect_ratio`), uppercase resolution casing (`1080P`), and a wider
	// 2–15s duration range. See
	// docs/task/gmi-provider/gmi-happy-horse-t2v-plan.md
	ModelRegistry.register({
		key: "gmi_happy_horse_t2v",
		name: "Alibaba Happy Horse T2V (GMI)",
		provider: "Alibaba (via GMI)",
		endpoint: "happyhorse1.0-t2v",
		categories: ["text_to_video"],
		description:
			"Alibaba Wan AI Happy Horse 1.0 T2V — 720p/1080p, 2–15s, audio-driven, via GMI Cloud",
		pricing: { per_second: 0.28 },
		durationOptions: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
		aspectRatios: ["16:9", "9:16", "1:1", "4:3", "3:4"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: 5,
			resolution: "1080p",
			aspect_ratio: "16:9",
			prompt_extend: true,
			watermark: false,
		},
		features: [
			"negative_prompt",
			"audio_input",
			"prompt_extension",
			"seed_control",
			"watermark_toggle",
			"flexible_duration",
			"multiple_aspect_ratios",
		],
		maxDuration: 15,
		inputRequirements: {
			required: ["prompt"],
			optional: [
				"duration",
				"resolution",
				"aspect_ratio",
				"negative_prompt",
				"audio_url",
				"prompt_extend",
				"watermark",
				"seed",
			],
		},
		extendedFeatures: {
			start_frame: false,
			end_frame: false,
			ref_images: false,
			audio_input: true,
			audio_generate: false,
			ref_video: false,
		},
		costEstimate: 1.4,
		processingTime: 60,
		providerBackend: "gmi",
	});
}
