/**
 * Text-to-video model definitions
 * @module electron/native-pipeline/registry-data/text-to-video
 */

import { ModelRegistry } from "../infra/registry.js";

export function registerTextToVideoModels(): void {
	ModelRegistry.register({
		key: "hailuo_pro",
		name: "MiniMax Hailuo-02 Pro",
		provider: "MiniMax",
		endpoint: "fal-ai/minimax/hailuo-02/pro/text-to-video",
		categories: ["text_to_video"],
		description: "Cost-effective text-to-video with prompt optimization",
		pricing: { type: "per_video", cost: 0.08 },
		durationOptions: ["6"],
		aspectRatios: ["16:9"],
		resolutions: ["1080p"],
		defaults: { prompt_optimizer: true },
		features: ["prompt_optimizer", "1080p", "cost_effective"],
		maxDuration: 6,
		costEstimate: 0.08,
		processingTime: 60,
	});

	ModelRegistry.register({
		key: "veo3",
		name: "Google Veo 3",
		provider: "Google (via FAL)",
		endpoint: "fal-ai/veo3",
		categories: ["text_to_video"],
		description: "Premium quality with audio generation",
		pricing: { type: "per_second", cost_no_audio: 0.5, cost_with_audio: 0.75 },
		durationOptions: ["5s", "6s", "7s", "8s"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			duration: "8s",
			aspect_ratio: "16:9",
			generate_audio: true,
			enhance_prompt: true,
		},
		features: [
			"audio_generation",
			"enhance_prompt",
			"negative_prompt",
			"seed_control",
		],
		maxDuration: 8,
		costEstimate: 4.0,
		processingTime: 300,
	});

	ModelRegistry.register({
		key: "veo3_fast",
		name: "Google Veo 3 Fast",
		provider: "Google (via FAL)",
		endpoint: "fal-ai/veo3/fast",
		categories: ["text_to_video"],
		description: "Fast generation with good quality",
		pricing: { type: "per_second", cost_no_audio: 0.25, cost_with_audio: 0.4 },
		durationOptions: ["5s", "6s", "7s", "8s"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: { duration: "8s", aspect_ratio: "16:9", generate_audio: true },
		features: ["audio_generation", "fast_processing", "seed_control"],
		maxDuration: 8,
		costEstimate: 2.0,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "kling_2_6_pro",
		name: "Kling Video v2.6 Pro",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v2.6/pro/text-to-video",
		categories: ["text_to_video"],
		description: "Professional text-to-video with audio support",
		pricing: { type: "per_second", cost_no_audio: 0.07, cost_with_audio: 0.14 },
		durationOptions: ["5", "10"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			duration: "5",
			aspect_ratio: "16:9",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
			generate_audio: true,
		},
		features: [
			"audio_generation",
			"negative_prompt",
			"cfg_scale",
			"multilingual",
		],
		maxDuration: 10,
		costEstimate: 0.35,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_3_standard",
		name: "Kling Video v3 Standard",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v3/standard/text-to-video",
		categories: ["text_to_video"],
		description:
			"Latest generation with native audio, voice control, and multi-prompt support",
		pricing: {
			type: "per_second",
			cost_no_audio: 0.168,
			cost_with_audio: 0.252,
			cost_voice_control: 0.308,
		},
		durationOptions: [
			"3",
			"4",
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
			"11",
			"12",
			"13",
			"14",
			"15",
		],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			duration: "5",
			aspect_ratio: "16:9",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
			generate_audio: false,
			voice_ids: [],
			multi_prompt: [],
			shot_type: null,
		},
		features: [
			"audio_generation",
			"voice_control",
			"multi_prompt",
			"shot_type",
			"negative_prompt",
			"cfg_scale",
			"multilingual",
		],
		maxDuration: 15,
		costEstimate: 0.84,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_3_pro",
		name: "Kling Video v3 Pro",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/v3/pro/text-to-video",
		categories: ["text_to_video"],
		description:
			"Top-tier cinematic visuals with native audio, voice control, and multi-prompt support",
		pricing: {
			type: "per_second",
			cost_no_audio: 0.224,
			cost_with_audio: 0.336,
			cost_voice_control: 0.392,
		},
		durationOptions: [
			"3",
			"4",
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
			"11",
			"12",
			"13",
			"14",
			"15",
		],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p"],
		defaults: {
			duration: "5",
			aspect_ratio: "16:9",
			negative_prompt: "blur, distort, and low quality",
			cfg_scale: 0.5,
			generate_audio: false,
			voice_ids: [],
			multi_prompt: [],
			shot_type: null,
		},
		features: [
			"audio_generation",
			"voice_control",
			"multi_prompt",
			"shot_type",
			"negative_prompt",
			"cfg_scale",
			"multilingual",
			"professional_quality",
		],
		maxDuration: 15,
		costEstimate: 1.12,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "kling_o3_pro_t2v",
		name: "Kling O3 Pro Text-to-Video",
		provider: "Kuaishou",
		endpoint: "fal-ai/kling-video/o3/pro/text-to-video",
		categories: ["text_to_video"],
		description:
			"O3 (Omni) model with element-based character/object consistency and @ reference syntax",
		pricing: {
			type: "per_second",
			cost_no_audio: 0.224,
			cost_with_audio: 0.28,
		},
		durationOptions: ["3", "5", "10", "15"],
		aspectRatios: ["16:9", "9:16", "1:1"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "5",
			aspect_ratio: "16:9",
			negative_prompt: null,
			cfg_scale: 0.5,
			generate_audio: true,
			elements: [],
			image_urls: [],
			multi_prompt: [],
			shot_type: null,
		},
		features: [
			"audio_generation",
			"elements",
			"reference_images",
			"reference_syntax",
			"multi_prompt",
			"shot_type",
			"negative_prompt",
			"cfg_scale",
			"professional_quality",
		],
		maxDuration: 15,
		costEstimate: 1.12,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "sora_2",
		name: "Sora 2",
		provider: "OpenAI (via FAL)",
		endpoint: "fal-ai/sora-2/text-to-video",
		categories: ["text_to_video"],
		description: "OpenAI's text-to-video model",
		pricing: { type: "per_second", cost: 0.1 },
		durationOptions: ["4", "8", "12"],
		aspectRatios: ["16:9", "9:16"],
		resolutions: ["720p"],
		defaults: {
			duration: "4",
			resolution: "720p",
			aspect_ratio: "16:9",
			delete_video: true,
		},
		features: ["aspect_ratio", "long_duration"],
		maxDuration: 12,
		costEstimate: 0.4,
		processingTime: 120,
	});

	ModelRegistry.register({
		key: "sora_2_pro",
		name: "Sora 2 Pro",
		provider: "OpenAI (via FAL)",
		endpoint: "fal-ai/sora-2/text-to-video/pro",
		categories: ["text_to_video"],
		description: "Professional Sora with 1080p support",
		pricing: { type: "per_second", cost_720p: 0.3, cost_1080p: 0.5 },
		durationOptions: ["4", "8", "12"],
		aspectRatios: ["16:9", "9:16"],
		resolutions: ["720p", "1080p"],
		defaults: {
			duration: "4",
			resolution: "1080p",
			aspect_ratio: "16:9",
			delete_video: true,
		},
		features: ["aspect_ratio", "1080p", "long_duration"],
		maxDuration: 12,
		costEstimate: 2.0,
		processingTime: 180,
	});

	ModelRegistry.register({
		key: "ltx23_pro_t2v",
		name: "LTX Video 2.3 Pro T2V",
		provider: "Lightricks (via FAL)",
		endpoint: "fal-ai/ltx-2.3/text-to-video",
		categories: ["text_to_video"],
		description:
			"Text-to-video with native audio and 4K support (6-10s)",
		pricing: {
			type: "per_second",
			cost_1080p: 0.06,
			cost_1440p: 0.12,
			cost_2160p: 0.24,
		},
		durationOptions: ["6", "8", "10"],
		aspectRatios: ["16:9", "9:16"],
		resolutions: ["1080p", "1440p", "2160p"],
		defaults: {
			duration: 6,
			resolution: "1080p",
			aspect_ratio: "16:9",
			fps: 25,
			generate_audio: true,
		},
		features: [
			"audio_generation",
			"4k_resolution",
			"aspect_ratio",
			"fps_control",
		],
		maxDuration: 10,
		costEstimate: 0.36,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "ltx23_fast_t2v",
		name: "LTX Video 2.3 Fast T2V",
		provider: "Lightricks (via FAL)",
		endpoint: "fal-ai/ltx-2.3/text-to-video/fast",
		categories: ["text_to_video"],
		description:
			"Fast text-to-video with 4K support and native audio, up to 20s",
		pricing: {
			type: "per_second",
			cost_1080p: 0.04,
			cost_1440p: 0.08,
			cost_2160p: 0.16,
		},
		durationOptions: ["6", "8", "10", "12", "14", "16", "18", "20"],
		aspectRatios: ["16:9", "9:16"],
		resolutions: ["1080p", "1440p", "2160p"],
		defaults: {
			duration: 6,
			resolution: "1080p",
			aspect_ratio: "16:9",
			fps: 25,
			generate_audio: true,
		},
		features: [
			"audio_generation",
			"4k_resolution",
			"long_duration",
			"aspect_ratio",
			"fps_control",
			"fast_processing",
		],
		maxDuration: 20,
		costEstimate: 0.24,
		processingTime: 60,
	});

	ModelRegistry.register({
		key: "ltx23_a2v",
		name: "LTX Video 2.3 Audio-to-Video",
		provider: "Lightricks (via FAL)",
		endpoint: "fal-ai/ltx-2.3/audio-to-video",
		categories: ["text_to_video"],
		description:
			"Generate video from audio input with text guidance (6-10s)",
		pricing: { type: "per_second", cost: 0.1 },
		durationOptions: ["6", "8", "10"],
		resolutions: ["1080p"],
		defaults: {
			duration: 6,
			resolution: "1080p",
			guidance_scale: 7,
		},
		features: ["audio_input", "text_guidance"],
		maxDuration: 10,
		costEstimate: 0.6,
		processingTime: 90,
	});

	ModelRegistry.register({
		key: "grok_imagine",
		name: "xAI Grok Imagine Video",
		provider: "xAI (via FAL)",
		endpoint: "xai/grok-imagine-video/text-to-video",
		categories: ["text_to_video"],
		description: "xAI's text-to-video with native audio generation",
		pricing: {
			type: "per_second",
			base_duration: 6,
			base_cost_6s: 0.3,
			cost_per_additional_second: 0.05,
		},
		durationOptions: [
			"1",
			"2",
			"3",
			"4",
			"5",
			"6",
			"7",
			"8",
			"9",
			"10",
			"11",
			"12",
			"13",
			"14",
			"15",
		],
		aspectRatios: ["16:9", "4:3", "3:2", "1:1", "2:3", "3:4", "9:16"],
		resolutions: ["480p", "720p"],
		defaults: { duration: "6", resolution: "720p", aspect_ratio: "16:9" },
		features: [
			"audio_generation",
			"flexible_duration",
			"multiple_aspect_ratios",
		],
		maxDuration: 15,
		costEstimate: 0.3,
		processingTime: 60,
	});
}
