/**
 * @qcut/editor-core type exports
 * @module @qcut/editor-core/types
 */

export type {
	BackgroundType,
	CanvasSize,
	CanvasMode,
	CanvasPreset,
} from "./editor.js";

export type {
	BlurIntensity,
	ProjectFolder,
	Scene,
	TProject,
} from "./project.js";

export type {
	ColorBasicSettings,
	ColorCubeLut,
	ColorCurvePoint,
	ColorCurveShapeKeyframe,
	ColorCurveShapeProperty,
	ColorCurvesSettings,
	ColorFilterApplication,
	ColorSecondaryCurve,
	ColorSecondaryCurveName,
	ColorSecondaryCurvesSettings,
	ColorGradeMaskSettings,
	ColorHslKeyframeProperty,
	ColorHslRangeName,
	ColorHslRangeSettings,
	ColorHslSettings,
	ColorKeyframeProperty,
	ColorLutSettings,
	ColorManagementSettings,
	ColorPropertyKeyframe,
	ColorSmartSettings,
	ColorSpace,
	ColorWheelKeyframeProperty,
	ColorWheelSettings,
	ColorWheelsSettings,
	MediaColorSettings,
} from "./color.js";

export type {
	EffectAudioReactiveRenderStage,
	EffectAudioReactiveEnvelope,
	EffectAudioReactiveKeyframe,
	EffectCompositeRenderStage,
	EffectFilterRenderStage,
	EffectMotionChannel,
	EffectMotionProperty,
	EffectMotionRenderStage,
	EffectMotionWaveform,
	EffectOverlayRenderStage,
	EffectParticleRenderStage,
	EffectParticleVariant,
	EffectPersonTrackingRenderStage,
	EffectRenderProgram,
	EffectRenderWindow,
	EffectRenderStage,
	EffectRenderStageKind,
} from "./effect-render.js";

export type {
	AnimatedParameter,
	EffectAudioCompanion,
	EffectTimelineRange,
	EffectChain,
	EffectInstance,
	EffectKeyframe,
	EffectParameters,
	EffectType,
} from "./effects.js";

export type {
	MediaType,
	TrackType,
	MediaElement,
	EffectElement,
	CompoundMediaClip,
	MediaCompound,
	MediaBlendMode,
	MediaFitMode,
	MediaCrop,
	MediaPerspective,
	MediaKeyframeProperty,
	MediaPropertyKeyframe,
	MediaAnimationType,
	MediaComboAnimationType,
	ClipTransition,
	ClipTransitionDirection,
	ClipTransitionEasing,
	ClipTransitionKeyframeEasing,
	ClipTransitionTuning,
	ClipTransitionTuningKeyframe,
	ClipTransitionTuningKeyframes,
	ClipTransitionTuningProperty,
	ClipTransitionType,
	MediaAdjustments,
	MediaMask,
	MediaMaskType,
	MediaMaskBlendMode,
	MediaMaskKeyframeProperty,
	MediaMaskPoint,
	MediaMaskStroke,
	MediaMaskStrokeStyle,
	MediaMaskTracking,
	MediaMaskTrackingDirection,
	MediaCustomCutout,
	MediaCustomCutoutBrushMode,
	MediaCustomCutoutPoint,
	MediaCustomCutoutStroke,
	MediaChromaKey,
	MediaChromaKeyKeyframeProperty,
	MediaEnhancements,
	AudioKeyframeProperty,
	AudioLoudnessSettings,
	AudioDenoiseSettings,
	AudioVoiceEnhanceSettings,
	AudioPitchSettings,
	AudioEqualizerSettings,
	AudioCompressorSettings,
	AudioLimiterSettings,
	AudioReverbSettings,
	AudioEchoSettings,
	AudioTelephoneSettings,
	AudioChannelMode,
	AudioParametricFilterType,
	AudioParametricEqBand,
	AudioParametricEqualizerSettings,
	AudioRepairSettings,
	AudioDuckingSettings,
	AudioAutoCrossfadeSettings,
	AudioCrossfade,
	AudioBusEffectsSettings,
	TimelineTrackAudioSettings,
	AudioMixBusSettings,
	ProjectAudioMixSettings,
	AudioStemName,
	AudioSeparationSettings,
	AudioVoiceConversionSettings,
	AudioCoverSettings,
	AudioLyricsWord,
	AudioLyricsSettings,
	MediaAudioSettings,
	TextElement,
	TextKeyframeProperty,
	TextPropertyKeyframe,
	StickerElement,
	AdjustmentElement,
	CaptionElement,
	SubtitleStyle,
	RemotionElement,
	MarkdownElement,
	TimelineElement,
	CreateMediaElement,
	CreateEffectElement,
	CreateTextElement,
	CreateStickerElement,
	CreateAdjustmentElement,
	CreateCaptionElement,
	CreateRemotionElement,
	CreateMarkdownElement,
	CreateTimelineElement,
	TimelineTrack,
	MediaItemDragData,
	TextItemDragData,
	StickerItemDragData,
	RemotionItemDragData,
	MarkdownItemDragData,
	DragData,
} from "./timeline.js";

export type {
	TranscriptionSegment,
	TranscriptionResult,
	TranscriptionRequest,
	TranscriptionError,
	CaptionSegment,
	CaptionTrackData,
	TranscriptionStatus,
	TranscriptionProgress,
	CaptionFormat,
	CaptionExportOptions,
} from "./captions.js";

export type {
	TranscriptionWord as PersistedTranscriptionWord,
	TranscriptionSegment as PersistedTranscriptionSegment,
	PersistedTranscription,
	TranscriptionAvailability,
} from "./transcription.js";
