/**
 * @qcut/editor-core type exports
 * @module @qcut/editor-core/types
 */

export type {
	BackgroundType,
	CanvasSize,
	CanvasMode,
	CanvasPreset,
} from "./editor.js";

export type {
	BlurIntensity,
	Scene,
	TProject,
} from "./project.js";

export type {
	ColorBasicSettings,
	ColorCubeLut,
	ColorCurvePoint,
	ColorCurveShapeKeyframe,
	ColorCurveShapeProperty,
	ColorCurvesSettings,
	ColorFilterApplication,
	ColorSecondaryCurve,
	ColorSecondaryCurveName,
	ColorSecondaryCurvesSettings,
	ColorGradeMaskSettings,
	ColorHslKeyframeProperty,
	ColorHslRangeName,
	ColorHslRangeSettings,
	ColorHslSettings,
	ColorKeyframeProperty,
	ColorLutSettings,
	ColorManagementSettings,
	ColorPropertyKeyframe,
	ColorSmartSettings,
	ColorSpace,
	ColorWheelKeyframeProperty,
	ColorWheelSettings,
	ColorWheelsSettings,
	MediaColorSettings,
} from "./color.js";

export type {
	MediaType,
	TrackType,
	MediaElement,
	MediaBlendMode,
	MediaFitMode,
	MediaCrop,
	MediaPerspective,
	MediaKeyframeProperty,
	MediaPropertyKeyframe,
	MediaAnimationType,
	MediaComboAnimationType,
	MediaAdjustments,
	MediaMask,
	MediaMaskType,
	MediaMaskBlendMode,
	MediaMaskKeyframeProperty,
	MediaMaskPoint,
	MediaMaskStroke,
	MediaMaskStrokeStyle,
	MediaMaskTracking,
	MediaMaskTrackingDirection,
	MediaChromaKey,
	MediaEnhancements,
	AudioKeyframeProperty,
	AudioLoudnessSettings,
	AudioDenoiseSettings,
	AudioVoiceEnhanceSettings,
	AudioPitchSettings,
	AudioEqualizerSettings,
	AudioCompressorSettings,
	AudioLimiterSettings,
	AudioReverbSettings,
	AudioEchoSettings,
	AudioTelephoneSettings,
	AudioStemName,
	AudioSeparationSettings,
	AudioVoiceConversionSettings,
	AudioLyricsWord,
	AudioLyricsSettings,
	MediaAudioSettings,
	TextElement,
	TextKeyframeProperty,
	TextPropertyKeyframe,
	StickerElement,
	CaptionElement,
	SubtitleStyle,
	RemotionElement,
	MarkdownElement,
	TimelineElement,
	CreateMediaElement,
	CreateTextElement,
	CreateStickerElement,
	CreateCaptionElement,
	CreateRemotionElement,
	CreateMarkdownElement,
	CreateTimelineElement,
	TimelineTrack,
	MediaItemDragData,
	TextItemDragData,
	StickerItemDragData,
	RemotionItemDragData,
	MarkdownItemDragData,
	DragData,
} from "./timeline.js";

export type {
	TranscriptionSegment,
	TranscriptionResult,
	TranscriptionRequest,
	TranscriptionError,
	CaptionSegment,
	CaptionTrackData,
	TranscriptionStatus,
	TranscriptionProgress,
	CaptionFormat,
	CaptionExportOptions,
} from "./captions.js";

export type {
	TranscriptionWord as PersistedTranscriptionWord,
	TranscriptionSegment as PersistedTranscriptionSegment,
	PersistedTranscription,
	TranscriptionAvailability,
} from "./transcription.js";
