import type { FilterPreset } from "./filter-types";

export const EXTENDED_FILTER_PRESETS: FilterPreset[] = [
	{
		id: "glow-portrait",
		version: 1,
		name: "Glow Portrait",
		localizedName: "透亮人像",
		category: "portrait",
		tags: ["portrait", "glow", "skin", "人像", "透亮", "肤色"],
		thumbnail: "/images/filter-previews/glow-portrait.webp",
		lutAssetId: "qcut/filter/glow-portrait/v1",
		defaultIntensity: 68,
		isNew: true,
		skinProtection: 55,
		recipe: {
			exposure: 0.1,
			contrast: -0.06,
			saturation: 1.04,
			temperature: 0.22,
			tint: 0.08,
			highlightTint: [0.025, 0.008, 0.012],
		},
	},
	{
		id: "fresh-plate",
		version: 1,
		name: "Fresh Plate",
		localizedName: "鲜味",
		category: "food",
		tags: ["food", "fresh", "bright", "美食", "清新", "明亮"],
		thumbnail: "/images/filter-previews/fresh-plate.webp",
		lutAssetId: "qcut/filter/fresh-plate/v1",
		defaultIntensity: 76,
		isNew: true,
		recipe: {
			exposure: 0.04,
			contrast: 0.12,
			saturation: 1.18,
			temperature: 0.08,
			highlightTint: [0.025, 0.012, -0.012],
		},
		extras: { sharpness: 10 },
	},
	{
		id: "pocket-color",
		version: 1,
		name: "Pocket Color",
		localizedName: "口袋电影",
		category: "camera",
		tags: ["camera", "digital", "cinema", "相机", "数码", "电影感"],
		thumbnail: "/images/filter-previews/pocket-color.webp",
		lutAssetId: "qcut/filter/pocket-color/v1",
		defaultIntensity: 74,
		isNew: true,
		recipe: {
			contrast: 0.18,
			saturation: 1.14,
			temperature: -0.04,
			shadowTint: [-0.018, 0.018, 0.045],
			highlightTint: [0.035, 0.012, -0.018],
		},
		extras: { sharpness: 14 },
	},
	{
		id: "slate-chrome",
		version: 1,
		name: "Slate Chrome",
		localizedName: "岩灰色彩",
		category: "camera",
		tags: ["camera", "chrome", "muted", "相机", "灰调", "纪实"],
		thumbnail: "/images/filter-previews/slate-chrome.webp",
		lutAssetId: "qcut/filter/slate-chrome/v1",
		defaultIntensity: 78,
		recipe: {
			contrast: 0.16,
			saturation: 0.78,
			temperature: -0.12,
			fade: 0.03,
			shadowTint: [-0.02, 0.014, 0.032],
		},
		extras: { grain: 6, sharpness: 8 },
	},
	{
		id: "soft-ccd",
		version: 1,
		name: "Soft CCD",
		localizedName: "柔光 CCD",
		category: "camera",
		tags: ["camera", "ccd", "soft", "相机", "CCD", "柔光"],
		thumbnail: "/images/filter-previews/soft-ccd.webp",
		lutAssetId: "qcut/filter/soft-ccd/v1",
		defaultIntensity: 72,
		recipe: {
			exposure: 0.08,
			contrast: -0.02,
			saturation: 0.92,
			temperature: 0.16,
			tint: 0.12,
			fade: 0.12,
		},
		extras: { grain: 8 },
	},
	{
		id: "neon-city",
		version: 1,
		name: "Neon City",
		localizedName: "霓虹夜城",
		category: "night",
		tags: ["night", "neon", "city", "夜景", "霓虹", "城市"],
		thumbnail: "/images/filter-previews/neon-city.webp",
		lutAssetId: "qcut/filter/neon-city/v1",
		defaultIntensity: 72,
		isNew: true,
		recipe: {
			exposure: -0.06,
			contrast: 0.3,
			saturation: 1.22,
			temperature: -0.34,
			tint: 0.28,
			shadowTint: [-0.025, 0.008, 0.09],
			highlightTint: [0.035, -0.012, 0.055],
		},
		extras: { vignette: 18, sharpness: 8 },
	},
	{
		id: "moonlit",
		version: 1,
		name: "Moonlit",
		localizedName: "月夜",
		category: "night",
		tags: ["night", "moon", "blue", "夜景", "月光", "蓝调"],
		thumbnail: "/images/filter-previews/moonlit.webp",
		lutAssetId: "qcut/filter/moonlit/v1",
		defaultIntensity: 78,
		recipe: {
			exposure: -0.12,
			contrast: 0.18,
			saturation: 0.72,
			temperature: -0.55,
			shadowTint: [-0.025, 0.012, 0.08],
			highlightTint: [-0.01, 0.018, 0.045],
		},
		extras: { vignette: 14 },
	},
	{
		id: "blockbuster",
		version: 1,
		name: "Blockbuster",
		localizedName: "大银幕",
		category: "cinematic",
		tags: ["cinema", "blockbuster", "dramatic", "电影", "大片", "戏剧"],
		thumbnail: "/images/filter-previews/blockbuster.webp",
		lutAssetId: "qcut/filter/blockbuster/v1",
		defaultIntensity: 70,
		isNew: true,
		skinProtection: 24,
		recipe: {
			contrast: 0.28,
			saturation: 1.02,
			temperature: 0.06,
			shadowTint: [-0.04, 0.035, 0.07],
			highlightTint: [0.065, 0.018, -0.032],
		},
		extras: { grain: 6, vignette: 14 },
	},
	{
		id: "trail-clear",
		version: 1,
		name: "Trail Clear",
		localizedName: "山野通透",
		category: "outdoor",
		tags: ["outdoor", "trail", "clear", "户外", "山野", "通透"],
		thumbnail: "/images/filter-previews/trail-clear.webp",
		lutAssetId: "qcut/filter/trail-clear/v1",
		defaultIntensity: 80,
		isNew: true,
		recipe: {
			exposure: 0.05,
			contrast: 0.13,
			saturation: 1.12,
			temperature: 0.05,
		},
		extras: { sharpness: 14 },
	},
	{
		id: "meadow-air",
		version: 1,
		name: "Meadow Air",
		localizedName: "旷野清风",
		category: "outdoor",
		tags: ["outdoor", "meadow", "fresh", "户外", "草地", "清新"],
		thumbnail: "/images/filter-previews/meadow-air.webp",
		lutAssetId: "qcut/filter/meadow-air/v1",
		defaultIntensity: 76,
		recipe: {
			exposure: 0.1,
			contrast: 0.08,
			saturation: 1.1,
			temperature: -0.06,
			tint: -0.08,
			highlightTint: [0.012, 0.02, 0.002],
		},
		extras: { sharpness: 8 },
	},
	{
		id: "cyber-pop",
		version: 1,
		name: "Cyber Pop",
		localizedName: "赛博跃彩",
		category: "stylized",
		tags: ["stylized", "cyber", "pop", "风格化", "赛博", "高饱和"],
		thumbnail: "/images/filter-previews/cyber-pop.webp",
		lutAssetId: "qcut/filter/cyber-pop/v1",
		defaultIntensity: 64,
		isNew: true,
		recipe: {
			contrast: 0.25,
			saturation: 1.38,
			tint: 0.3,
			hueShift: 8,
			shadowTint: [0.005, -0.02, 0.08],
			highlightTint: [0.025, 0.025, -0.035],
		},
		extras: { vignette: 8, sharpness: 10 },
	},
	{
		id: "dreamy-pastel",
		version: 1,
		name: "Dreamy Pastel",
		localizedName: "梦幻粉彩",
		category: "stylized",
		tags: ["stylized", "dreamy", "pastel", "风格化", "梦幻", "粉彩"],
		thumbnail: "/images/filter-previews/dreamy-pastel.webp",
		lutAssetId: "qcut/filter/dreamy-pastel/v1",
		defaultIntensity: 70,
		recipe: {
			exposure: 0.1,
			contrast: -0.16,
			saturation: 0.88,
			temperature: 0.14,
			tint: 0.18,
			fade: 0.18,
		},
	},
	{
		id: "clarity-boost",
		version: 1,
		name: "Clarity Boost",
		localizedName: "清晰增强",
		category: "hd",
		tags: ["hd", "clarity", "detail", "高清", "清晰", "细节"],
		thumbnail: "/images/filter-previews/clarity-boost.webp",
		lutAssetId: "qcut/filter/clarity-boost/v1",
		defaultIntensity: 62,
		isNew: true,
		recipe: { contrast: 0.1, saturation: 1.03, gamma: 0.99 },
		extras: { sharpness: 30 },
	},
	{
		id: "detail-pop",
		version: 1,
		name: "Detail Pop",
		localizedName: "质感增强",
		category: "hd",
		tags: ["hd", "detail", "texture", "高清", "质感", "锐利"],
		thumbnail: "/images/filter-previews/detail-pop.webp",
		lutAssetId: "qcut/filter/detail-pop/v1",
		defaultIntensity: 58,
		recipe: {
			contrast: 0.18,
			saturation: 1.08,
			blackLift: -0.01,
		},
		extras: { sharpness: 40 },
	},
	{
		id: "window-light",
		version: 1,
		name: "Window Light",
		localizedName: "窗边自然光",
		category: "indoor",
		tags: ["indoor", "window", "natural", "室内", "窗光", "自然光"],
		thumbnail: "/images/filter-previews/window-light.webp",
		lutAssetId: "qcut/filter/window-light/v1",
		defaultIntensity: 78,
		isNew: true,
		recipe: {
			exposure: 0.14,
			contrast: -0.03,
			saturation: 0.98,
			temperature: 0.04,
			tint: 0.03,
		},
		extras: { sharpness: 4 },
	},
	{
		id: "warm-room",
		version: 1,
		name: "Warm Room",
		localizedName: "暖室",
		category: "indoor",
		tags: ["indoor", "warm", "home", "室内", "暖光", "居家"],
		thumbnail: "/images/filter-previews/warm-room.webp",
		lutAssetId: "qcut/filter/warm-room/v1",
		defaultIntensity: 72,
		recipe: {
			exposure: 0.08,
			contrast: 0.06,
			saturation: 1.04,
			temperature: 0.42,
			highlightTint: [0.04, 0.018, -0.025],
		},
		extras: { vignette: 4 },
	},
];
