import type { FilterPreset } from "./filter-types";

/**
 * Summer/cinema looks modeled on popular short-video editor grades.
 * Each recipe was least-squares fitted against pixel-aligned reference
 * frames captured at full strength, so defaultIntensity is 100 — the
 * default look matches the reference; lower the slider for subtlety.
 */
export const SUMMER_CINEMA_FILTER_PRESETS: FilterPreset[] = [
	{
		id: "rich-cinema",
		version: 1,
		name: "Rich Cinema",
		localizedName: "浓郁电影感",
		category: "cinematic",
		tags: ["cinema", "rich", "warm", "电影", "浓郁", "暖调"],
		thumbnail: "/images/filter-previews/rich-cinema.webp",
		lutAssetId: "qcut/filter/rich-cinema/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: -0.074,
			contrast: 0.229,
			saturation: 1.052,
			temperature: 0.318,
			tint: 0.216,
			fade: 0.176,
			gamma: 0.955,
			blackLift: 0.016,
			hueShift: 1.6,
			shadowTint: [-0.015, -0.005, 0.002],
			highlightTint: [-0.017, 0.033, 0.065],
		},
	},
	{
		id: "texture-drama",
		version: 1,
		name: "Texture Drama",
		localizedName: "质感大片",
		category: "cinematic",
		tags: ["cinema", "texture", "drama", "电影", "质感", "大片"],
		thumbnail: "/images/filter-previews/texture-drama.webp",
		lutAssetId: "qcut/filter/texture-drama/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: -0.043,
			contrast: 0.166,
			saturation: 1.182,
			temperature: -0.087,
			tint: 0.053,
			fade: 0.228,
			gamma: 0.832,
			blackLift: 0.022,
			hueShift: -0.5,
			shadowTint: [-0.019, -0.012, -0.008],
			highlightTint: [0.023, 0.018, 0.006],
		},
	},
	{
		id: "cinema-light",
		version: 1,
		name: "Cinema Light",
		localizedName: "电影光感",
		category: "cinematic",
		tags: ["cinema", "light", "glow", "电影", "光感", "柔光"],
		thumbnail: "/images/filter-previews/cinema-light.webp",
		lutAssetId: "qcut/filter/cinema-light/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: -0.091,
			contrast: 0.129,
			saturation: 1.033,
			temperature: 0.747,
			tint: 0.492,
			fade: 0.124,
			gamma: 1.059,
			blackLift: 0.021,
			hueShift: 4.1,
			shadowTint: [-0.048, -0.002, -0.013],
			highlightTint: [-0.027, 0.045, 0.094],
		},
	},
	{
		id: "clear-blue",
		version: 1,
		name: "Clear Blue",
		localizedName: "晴朗增蓝",
		category: "summer",
		tags: ["summer", "blue", "sky", "夏日", "增蓝", "晴朗"],
		thumbnail: "/images/filter-previews/clear-blue.webp",
		lutAssetId: "qcut/filter/clear-blue/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.013,
			contrast: 0.108,
			saturation: 1.145,
			temperature: -0.28,
			tint: -0.169,
			fade: 0.245,
			gamma: 1.078,
			blackLift: -0.022,
			hueShift: 5.9,
			shadowTint: [-0.001, -0.016, 0.01],
			highlightTint: [0.038, -0.024, 0.051],
		},
	},
	{
		id: "sunny-natural",
		version: 1,
		name: "Sunny Natural",
		localizedName: "晴朗自然",
		category: "summer",
		tags: ["summer", "sunny", "vivid", "夏日", "晴朗", "自然"],
		thumbnail: "/images/filter-previews/sunny-natural.webp",
		lutAssetId: "qcut/filter/sunny-natural/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: -0.01,
			contrast: 0.326,
			saturation: 1.3,
			temperature: -0.1,
			tint: -0.031,
			fade: 0.188,
			gamma: 1.335,
			blackLift: -0.04,
			hueShift: 3.7,
			shadowTint: [-0.03, 0.005, 0.012],
			highlightTint: [-0.063, -0.056, 0.02],
		},
	},
	{
		id: "summer-clear",
		version: 1,
		name: "Summer Clear",
		localizedName: "夏日晴朗",
		category: "summer",
		tags: ["summer", "clear", "bright", "夏日", "晴朗", "通透"],
		thumbnail: "/images/filter-previews/summer-clear.webp",
		lutAssetId: "qcut/filter/summer-clear/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.145,
			contrast: -0.07,
			saturation: 1.314,
			temperature: 0.148,
			tint: -0.045,
			fade: 0.185,
			gamma: 1.084,
			blackLift: -0.09,
			hueShift: 9.2,
			shadowTint: [-0.047, -0.069, -0.029],
			highlightTint: [-0.045, -0.003, 0.12],
		},
	},
	{
		id: "sea-dehaze",
		version: 1,
		name: "Sea Dehaze",
		localizedName: "海蓝去灰",
		category: "summer",
		tags: ["summer", "sea", "dehaze", "夏日", "海蓝", "去灰"],
		thumbnail: "/images/filter-previews/sea-dehaze.webp",
		lutAssetId: "qcut/filter/sea-dehaze/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.069,
			contrast: 0.195,
			saturation: 0.86,
			temperature: -0.336,
			tint: 0.37,
			fade: 0.073,
			gamma: 1.033,
			blackLift: -0.011,
			hueShift: 7.4,
			shadowTint: [-0.012, 0.024, 0.033],
			highlightTint: [-0.071, 0.006, 0.025],
		},
	},
	{
		id: "beach-drama",
		version: 1,
		name: "Beach Drama",
		localizedName: "海边大片",
		category: "summer",
		tags: ["summer", "beach", "teal", "夏日", "海边", "大片"],
		thumbnail: "/images/filter-previews/beach-drama.webp",
		lutAssetId: "qcut/filter/beach-drama/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: -0.146,
			contrast: 0.294,
			saturation: 0.874,
			temperature: -0.108,
			tint: 0.093,
			fade: 0.095,
			gamma: 0.997,
			blackLift: 0.09,
			hueShift: 1.5,
			shadowTint: [-0.068, -0.041, -0.024],
			highlightTint: [0.015, 0.02, 0.011],
		},
	},
];
