import type { FilterPreset } from "./filter-types";

export const COLLECTION_FILTER_PRESETS: FilterPreset[] = [
	{
		id: "sun-washed",
		version: 1,
		name: "Sun Washed",
		localizedName: "日晒柔光",
		category: "summer",
		tags: ["summer", "sun", "washed", "warm", "夏日", "日晒"],
		thumbnail: "/images/filter-previews/sun-washed.webp",
		lutAssetId: "qcut/filter/sun-washed/v1",
		defaultIntensity: 76,
		isNew: true,
		recipe: {
			exposure: 0.12,
			contrast: -0.04,
			saturation: 1.06,
			temperature: 0.46,
			fade: 0.08,
		},
		extras: { grain: 4 },
	},
	{
		id: "peach-skin",
		version: 1,
		name: "Peach Skin",
		localizedName: "桃肌",
		category: "portrait",
		tags: ["portrait", "peach", "skin", "soft", "人像", "肤色"],
		thumbnail: "/images/filter-previews/peach-skin.webp",
		lutAssetId: "qcut/filter/peach-skin/v1",
		defaultIntensity: 66,
		isNew: true,
		skinProtection: 58,
		recipe: {
			exposure: 0.08,
			contrast: -0.08,
			saturation: 0.96,
			temperature: 0.28,
			tint: 0.12,
			highlightTint: [0.03, 0.008, 0.014],
		},
	},
	{
		id: "forest-depth",
		version: 1,
		name: "Forest Depth",
		localizedName: "森林层次",
		category: "landscape",
		tags: ["landscape", "forest", "depth", "green", "风景", "森林"],
		thumbnail: "/images/filter-previews/forest-depth.webp",
		lutAssetId: "qcut/filter/forest-depth/v1",
		defaultIntensity: 74,
		recipe: {
			contrast: 0.18,
			saturation: 1.16,
			temperature: -0.08,
			tint: -0.12,
			shadowTint: [-0.018, 0.035, 0.012],
		},
		extras: { sharpness: 16 },
	},
	{
		id: "dessert-glow",
		version: 1,
		name: "Dessert Glow",
		localizedName: "甜点柔光",
		category: "food",
		tags: ["food", "dessert", "glow", "warm", "美食", "甜点"],
		thumbnail: "/images/filter-previews/dessert-glow.webp",
		lutAssetId: "qcut/filter/dessert-glow/v1",
		defaultIntensity: 72,
		recipe: {
			exposure: 0.1,
			contrast: 0.04,
			saturation: 1.12,
			temperature: 0.24,
			tint: 0.08,
		},
		extras: { sharpness: 6 },
	},
	{
		id: "instant-film",
		version: 1,
		name: "Instant Film",
		localizedName: "即时成像",
		category: "camera",
		tags: ["camera", "instant", "film", "matte", "相机", "即时成像"],
		thumbnail: "/images/filter-previews/instant-film.webp",
		lutAssetId: "qcut/filter/instant-film/v1",
		defaultIntensity: 74,
		isNew: true,
		recipe: {
			contrast: -0.02,
			saturation: 0.88,
			temperature: 0.22,
			fade: 0.16,
			gamma: 1.04,
		},
		extras: { grain: 10, vignette: 6 },
	},
	{
		id: "amber-night",
		version: 1,
		name: "Amber Night",
		localizedName: "琥珀夜景",
		category: "night",
		tags: ["night", "amber", "warm", "city", "夜景", "琥珀"],
		thumbnail: "/images/filter-previews/amber-night.webp",
		lutAssetId: "qcut/filter/amber-night/v1",
		defaultIntensity: 72,
		recipe: {
			exposure: -0.08,
			contrast: 0.22,
			saturation: 1.08,
			temperature: 0.38,
			shadowTint: [0.035, 0.012, -0.025],
		},
		extras: { vignette: 14 },
	},
	{
		id: "noir-thriller",
		version: 1,
		name: "Noir Thriller",
		localizedName: "黑金悬疑",
		category: "cinematic",
		tags: ["cinema", "noir", "thriller", "dark", "电影", "悬疑"],
		thumbnail: "/images/filter-previews/noir-thriller.webp",
		lutAssetId: "qcut/filter/noir-thriller/v1",
		defaultIntensity: 68,
		isNew: true,
		recipe: {
			contrast: 0.36,
			saturation: 0.58,
			temperature: -0.12,
			blackLift: -0.02,
			shadowTint: [-0.025, 0.018, 0.04],
		},
		extras: { grain: 8, vignette: 18 },
	},
	{
		id: "desert-sun",
		version: 1,
		name: "Desert Sun",
		localizedName: "沙漠日光",
		category: "outdoor",
		tags: ["outdoor", "desert", "sun", "warm", "户外", "沙漠"],
		thumbnail: "/images/filter-previews/desert-sun.webp",
		lutAssetId: "qcut/filter/desert-sun/v1",
		defaultIntensity: 78,
		recipe: {
			exposure: 0.04,
			contrast: 0.16,
			saturation: 1.08,
			temperature: 0.42,
		},
		extras: { sharpness: 12 },
	},
	{
		id: "forest-trail",
		version: 1,
		name: "Forest Trail",
		localizedName: "林间小径",
		category: "outdoor",
		tags: ["outdoor", "forest", "trail", "fresh", "户外", "林间"],
		thumbnail: "/images/filter-previews/forest-trail.webp",
		lutAssetId: "qcut/filter/forest-trail/v1",
		defaultIntensity: 76,
		isNew: true,
		recipe: {
			contrast: 0.12,
			saturation: 1.14,
			temperature: -0.08,
			tint: -0.16,
		},
		extras: { sharpness: 10 },
	},
	{
		id: "acid-green",
		version: 1,
		name: "Acid Green",
		localizedName: "酸性绿",
		category: "stylized",
		tags: ["stylized", "acid", "green", "bold", "风格化", "酸性绿"],
		thumbnail: "/images/filter-previews/acid-green.webp",
		lutAssetId: "qcut/filter/acid-green/v1",
		defaultIntensity: 58,
		recipe: {
			contrast: 0.2,
			saturation: 1.28,
			tint: -0.32,
			hueShift: -12,
			shadowTint: [-0.02, 0.045, 0.01],
		},
		extras: { sharpness: 8 },
	},
	{
		id: "retro-pop",
		version: 1,
		name: "Retro Pop",
		localizedName: "复古波普",
		category: "stylized",
		tags: ["stylized", "retro", "pop", "color", "风格化", "波普"],
		thumbnail: "/images/filter-previews/retro-pop.webp",
		lutAssetId: "qcut/filter/retro-pop/v1",
		defaultIntensity: 62,
		isNew: true,
		recipe: {
			contrast: 0.22,
			saturation: 1.34,
			temperature: 0.14,
			hueShift: 8,
		},
		extras: { grain: 6 },
	},
	{
		id: "silver-mist",
		version: 1,
		name: "Silver Mist",
		localizedName: "银雾",
		category: "monochrome",
		tags: ["monochrome", "silver", "mist", "soft", "黑白", "银雾"],
		thumbnail: "/images/filter-previews/silver-mist.webp",
		lutAssetId: "qcut/filter/silver-mist/v1",
		defaultIntensity: 90,
		recipe: {
			monochrome: 1,
			contrast: -0.08,
			fade: 0.12,
			gamma: 1.08,
		},
		extras: { grain: 8 },
	},
	{
		id: "documentary-mono",
		version: 1,
		name: "Documentary Mono",
		localizedName: "纪实黑白",
		category: "monochrome",
		tags: ["monochrome", "documentary", "street", "contrast", "黑白", "纪实"],
		thumbnail: "/images/filter-previews/documentary-mono.webp",
		lutAssetId: "qcut/filter/documentary-mono/v1",
		defaultIntensity: 94,
		isNew: true,
		recipe: {
			monochrome: 1,
			contrast: 0.22,
			blackLift: -0.015,
			gamma: 0.98,
		},
		extras: { grain: 12, sharpness: 10 },
	},
	{
		id: "crisp-motion",
		version: 1,
		name: "Crisp Motion",
		localizedName: "动态清晰",
		category: "hd",
		tags: ["hd", "motion", "crisp", "detail", "高清", "动态"],
		thumbnail: "/images/filter-previews/crisp-motion.webp",
		lutAssetId: "qcut/filter/crisp-motion/v1",
		defaultIntensity: 54,
		recipe: { contrast: 0.12, saturation: 1.05, gamma: 0.98 },
		extras: { sharpness: 50 },
	},
	{
		id: "clean-detail",
		version: 1,
		name: "Clean Detail",
		localizedName: "纯净细节",
		category: "hd",
		tags: ["hd", "clean", "detail", "natural", "高清", "细节"],
		thumbnail: "/images/filter-previews/clean-detail.webp",
		lutAssetId: "qcut/filter/clean-detail/v1",
		defaultIntensity: 60,
		isNew: true,
		recipe: { exposure: 0.04, contrast: 0.08, saturation: 0.98 },
		extras: { sharpness: 24 },
	},
	{
		id: "faded-35mm",
		version: 1,
		name: "Faded 35mm",
		localizedName: "褪色 35mm",
		category: "film",
		tags: ["film", "35mm", "faded", "grain", "胶片", "褪色"],
		thumbnail: "/images/filter-previews/faded-35mm.webp",
		lutAssetId: "qcut/filter/faded-35mm/v1",
		defaultIntensity: 74,
		recipe: {
			contrast: -0.06,
			saturation: 0.82,
			temperature: 0.16,
			fade: 0.18,
			highlightTint: [0.025, 0.008, -0.012],
		},
		extras: { grain: 18, vignette: 8 },
	},
	{
		id: "cool-16mm",
		version: 1,
		name: "Cool 16mm",
		localizedName: "冷调 16mm",
		category: "film",
		tags: ["film", "16mm", "cool", "grain", "胶片", "冷调"],
		thumbnail: "/images/filter-previews/cool-16mm.webp",
		lutAssetId: "qcut/filter/cool-16mm/v1",
		defaultIntensity: 70,
		isNew: true,
		recipe: {
			contrast: 0.14,
			saturation: 0.76,
			temperature: -0.24,
			fade: 0.08,
			shadowTint: [-0.018, 0.012, 0.035],
		},
		extras: { grain: 22, vignette: 10 },
	},
	{
		id: "balanced-light",
		version: 1,
		name: "Balanced Light",
		localizedName: "均衡光感",
		category: "basic",
		tags: ["basic", "balanced", "light", "neutral", "基础", "均衡"],
		thumbnail: "/images/filter-previews/balanced-light.webp",
		lutAssetId: "qcut/filter/balanced-light/v1",
		defaultIntensity: 82,
		recipe: {
			exposure: 0.04,
			contrast: 0.06,
			saturation: 1.04,
			gamma: 1.01,
		},
	},
	{
		id: "gallery-white",
		version: 1,
		name: "Gallery White",
		localizedName: "展厅白光",
		category: "indoor",
		tags: ["indoor", "gallery", "white", "clean", "室内", "白光"],
		thumbnail: "/images/filter-previews/gallery-white.webp",
		lutAssetId: "qcut/filter/gallery-white/v1",
		defaultIntensity: 76,
		recipe: {
			exposure: 0.12,
			contrast: 0.03,
			saturation: 0.92,
			temperature: -0.08,
			tint: 0.04,
		},
		extras: { sharpness: 6 },
	},
	{
		id: "cozy-cafe",
		version: 1,
		name: "Cozy Cafe",
		localizedName: "暖调咖啡馆",
		category: "indoor",
		tags: ["indoor", "cafe", "cozy", "warm", "室内", "咖啡馆"],
		thumbnail: "/images/filter-previews/cozy-cafe.webp",
		lutAssetId: "qcut/filter/cozy-cafe/v1",
		defaultIntensity: 74,
		isNew: true,
		recipe: {
			exposure: 0.06,
			contrast: 0.1,
			saturation: 1.05,
			temperature: 0.48,
			shadowTint: [0.025, 0.008, -0.018],
		},
		extras: { vignette: 5 },
	},
];
