import type {
	FilterCategory,
	FilterExtras,
	FilterLutRecipe,
	FilterPreset,
} from "./filter-types";

interface FilterExpansionPresetSpec {
	id: string;
	name: string;
	localizedName: string;
	tags: string[];
	defaultIntensity: number;
	isNew?: boolean;
	skinProtection?: number;
	recipe: FilterLutRecipe;
	extras?: FilterExtras;
}

interface FilterCategoryExpansion {
	category: FilterCategory;
	presets: FilterExpansionPresetSpec[];
}

const CATEGORY_EXPANSIONS: FilterCategoryExpansion[] = [
	{
		category: "basic",
		presets: [
			{
				id: "true-neutral",
				name: "True Neutral",
				localizedName: "真实中性",
				tags: ["basic", "neutral", "clean", "自然", "中性"],
				defaultIntensity: 82,
				isNew: true,
				recipe: { contrast: 0.03, saturation: 1.01, gamma: 1.01 },
				extras: { sharpness: 4 },
			},
			{
				id: "daily-bright",
				name: "Daily Bright",
				localizedName: "日常提亮",
				tags: ["basic", "bright", "daily", "基础", "提亮"],
				defaultIntensity: 78,
				recipe: { exposure: 0.08, contrast: 0.04, saturation: 1.04 },
			},
			{
				id: "soft-contrast",
				name: "Soft Contrast",
				localizedName: "柔和对比",
				tags: ["basic", "contrast", "soft", "基础", "柔和"],
				defaultIntensity: 74,
				recipe: { contrast: 0.1, saturation: 0.98, fade: 0.04 },
			},
			{
				id: "clear-shadow",
				name: "Clear Shadow",
				localizedName: "暗部清透",
				tags: ["basic", "shadow", "clear", "基础", "暗部"],
				defaultIntensity: 76,
				recipe: { contrast: 0.06, saturation: 1.02, blackLift: 0.012 },
				extras: { sharpness: 6 },
			},
			{
				id: "gentle-color",
				name: "Gentle Color",
				localizedName: "轻彩",
				tags: ["basic", "color", "gentle", "基础", "轻彩"],
				defaultIntensity: 80,
				recipe: { contrast: 0.04, saturation: 1.1, temperature: 0.06 },
			},
		],
	},
	{
		category: "summer",
		presets: [
			{
				id: "melon-sun",
				name: "Melon Sun",
				localizedName: "西瓜晴日",
				tags: ["summer", "sunny", "fresh", "夏日", "清爽"],
				defaultIntensity: 80,
				isNew: true,
				recipe: {
					exposure: 0.08,
					contrast: 0.06,
					saturation: 1.16,
					temperature: 0.28,
					tint: -0.06,
				},
			},
			{
				id: "pool-day",
				name: "Pool Day",
				localizedName: "泳池蓝日",
				tags: ["summer", "pool", "cyan", "夏日", "蓝调"],
				defaultIntensity: 76,
				recipe: {
					contrast: 0.08,
					saturation: 1.12,
					temperature: -0.16,
					shadowTint: [-0.018, 0.018, 0.052],
				},
			},
			{
				id: "iced-lemon",
				name: "Iced Lemon",
				localizedName: "冰柠气泡",
				tags: ["summer", "lemon", "bright", "夏日", "明亮"],
				defaultIntensity: 78,
				recipe: {
					exposure: 0.1,
					contrast: 0.04,
					saturation: 1.14,
					temperature: 0.22,
					highlightTint: [0.04, 0.028, -0.026],
				},
			},
			{
				id: "beach-breeze",
				name: "Beach Breeze",
				localizedName: "海风",
				tags: ["summer", "beach", "breeze", "夏日", "海边"],
				defaultIntensity: 74,
				recipe: {
					contrast: 0.06,
					saturation: 1.1,
					temperature: -0.04,
					fade: 0.04,
					shadowTint: [-0.012, 0.02, 0.035],
				},
			},
			{
				id: "noon-pop",
				name: "Noon Pop",
				localizedName: "正午鲜彩",
				tags: ["summer", "noon", "pop", "夏日", "鲜彩"],
				defaultIntensity: 72,
				recipe: { contrast: 0.16, saturation: 1.22, temperature: 0.12 },
				extras: { sharpness: 8 },
			},
		],
	},
	{
		category: "landscape",
		presets: [
			{
				id: "wide-valley",
				name: "Wide Valley",
				localizedName: "开阔山谷",
				tags: ["landscape", "valley", "wide", "风景", "山谷"],
				defaultIntensity: 80,
				isNew: true,
				recipe: {
					contrast: 0.14,
					saturation: 1.14,
					temperature: -0.05,
					shadowTint: [-0.012, 0.02, 0.025],
				},
				extras: { sharpness: 14 },
			},
			{
				id: "lake-glass",
				name: "Lake Glass",
				localizedName: "湖面通透",
				tags: ["landscape", "lake", "clear", "风景", "湖面"],
				defaultIntensity: 76,
				recipe: {
					exposure: 0.04,
					contrast: 0.1,
					saturation: 1.1,
					temperature: -0.18,
					highlightTint: [-0.006, 0.012, 0.035],
				},
				extras: { sharpness: 12 },
			},
			{
				id: "cloud-plain",
				name: "Cloud Plain",
				localizedName: "云影草原",
				tags: ["landscape", "cloud", "plain", "风景", "草原"],
				defaultIntensity: 78,
				recipe: { contrast: 0.12, saturation: 1.18, temperature: 0.02 },
			},
			{
				id: "misty-hills",
				name: "Misty Hills",
				localizedName: "薄雾山丘",
				tags: ["landscape", "mist", "hills", "风景", "薄雾"],
				defaultIntensity: 72,
				recipe: {
					contrast: -0.04,
					saturation: 0.96,
					temperature: -0.04,
					fade: 0.12,
				},
			},
			{
				id: "sunset-ridge",
				name: "Sunset Ridge",
				localizedName: "暮色山脊",
				tags: ["landscape", "sunset", "ridge", "风景", "日落"],
				defaultIntensity: 76,
				recipe: {
					contrast: 0.16,
					saturation: 1.08,
					temperature: 0.42,
					highlightTint: [0.052, 0.02, -0.034],
				},
				extras: { vignette: 6 },
			},
		],
	},
	{
		category: "food",
		presets: [
			{
				id: "fresh-brunch",
				name: "Fresh Brunch",
				localizedName: "明亮早午餐",
				tags: ["food", "brunch", "fresh", "美食", "早午餐"],
				defaultIntensity: 78,
				isNew: true,
				recipe: {
					exposure: 0.08,
					contrast: 0.08,
					saturation: 1.14,
					temperature: 0.12,
				},
				extras: { sharpness: 8 },
			},
			{
				id: "sauce-gloss",
				name: "Sauce Gloss",
				localizedName: "酱汁光泽",
				tags: ["food", "sauce", "gloss", "美食", "光泽"],
				defaultIntensity: 74,
				recipe: {
					contrast: 0.16,
					saturation: 1.18,
					temperature: 0.18,
					gamma: 0.98,
				},
				extras: { sharpness: 12 },
			},
			{
				id: "clean-dessert",
				name: "Clean Dessert",
				localizedName: "清甜点心",
				tags: ["food", "dessert", "clean", "美食", "甜点"],
				defaultIntensity: 76,
				recipe: {
					exposure: 0.1,
					contrast: -0.02,
					saturation: 1.08,
					temperature: 0.08,
				},
			},
			{
				id: "market-fresh",
				name: "Market Fresh",
				localizedName: "市集鲜味",
				tags: ["food", "market", "fresh", "美食", "市集"],
				defaultIntensity: 78,
				recipe: {
					contrast: 0.12,
					saturation: 1.24,
					temperature: 0.02,
					tint: -0.04,
				},
				extras: { sharpness: 10 },
			},
			{
				id: "warm-kitchen",
				name: "Warm Kitchen",
				localizedName: "暖厨房",
				tags: ["food", "kitchen", "warm", "美食", "厨房"],
				defaultIntensity: 74,
				recipe: {
					exposure: 0.04,
					contrast: 0.1,
					saturation: 1.1,
					temperature: 0.34,
					highlightTint: [0.035, 0.012, -0.018],
				},
				extras: { vignette: 4 },
			},
		],
	},
	{
		category: "camera",
		presets: [
			{
				id: "provia-clear",
				name: "Provia Clear",
				localizedName: "普罗维亚清透",
				tags: ["camera", "film", "clear", "相机", "清透"],
				defaultIntensity: 74,
				isNew: true,
				recipe: { contrast: 0.1, saturation: 1.06, temperature: -0.04 },
				extras: { grain: 4, sharpness: 8 },
			},
			{
				id: "chrome-muted",
				name: "Chrome Muted",
				localizedName: "经典铬彩",
				tags: ["camera", "chrome", "muted", "相机", "低饱和"],
				defaultIntensity: 76,
				recipe: {
					contrast: 0.14,
					saturation: 0.82,
					temperature: -0.08,
					fade: 0.04,
				},
				extras: { grain: 6 },
			},
			{
				id: "ccd-flash",
				name: "CCD Flash",
				localizedName: "CCD 闪光",
				tags: ["camera", "ccd", "flash", "相机", "闪光"],
				defaultIntensity: 70,
				recipe: {
					exposure: 0.12,
					contrast: 0.12,
					saturation: 0.92,
					temperature: 0.18,
				},
				extras: { grain: 12, sharpness: 6 },
			},
			{
				id: "rangefinder-warm",
				name: "Rangefinder Warm",
				localizedName: "旁轴暖色",
				tags: ["camera", "rangefinder", "warm", "相机", "旁轴"],
				defaultIntensity: 72,
				recipe: {
					contrast: 0.08,
					saturation: 0.96,
					temperature: 0.28,
					fade: 0.08,
				},
				extras: { grain: 10, vignette: 6 },
			},
			{
				id: "digital-clean",
				name: "Digital Clean",
				localizedName: "数码干净",
				tags: ["camera", "digital", "clean", "相机", "数码"],
				defaultIntensity: 80,
				recipe: {
					exposure: 0.04,
					contrast: 0.06,
					saturation: 1.03,
					gamma: 1.01,
				},
				extras: { sharpness: 12 },
			},
		],
	},
	{
		category: "night",
		presets: [
			{
				id: "street-neon",
				name: "Street Neon",
				localizedName: "街头霓虹",
				tags: ["night", "neon", "street", "夜景", "街头"],
				defaultIntensity: 72,
				isNew: true,
				recipe: {
					exposure: -0.08,
					contrast: 0.28,
					saturation: 1.22,
					temperature: -0.3,
					tint: 0.18,
				},
				extras: { vignette: 16, sharpness: 8 },
			},
			{
				id: "city-rain",
				name: "City Rain",
				localizedName: "雨夜城市",
				tags: ["night", "rain", "city", "夜景", "雨夜"],
				defaultIntensity: 74,
				recipe: {
					exposure: -0.1,
					contrast: 0.2,
					saturation: 0.94,
					temperature: -0.18,
					shadowTint: [-0.02, 0.012, 0.055],
				},
				extras: { vignette: 14 },
			},
			{
				id: "lantern-night",
				name: "Lantern Night",
				localizedName: "灯笼夜色",
				tags: ["night", "lantern", "warm", "夜景", "暖光"],
				defaultIntensity: 70,
				recipe: {
					exposure: -0.06,
					contrast: 0.18,
					saturation: 1.08,
					temperature: 0.34,
					highlightTint: [0.05, 0.018, -0.03],
				},
				extras: { vignette: 12 },
			},
			{
				id: "deep-midnight",
				name: "Deep Midnight",
				localizedName: "深夜蓝",
				tags: ["night", "midnight", "blue", "夜景", "深蓝"],
				defaultIntensity: 76,
				recipe: {
					exposure: -0.14,
					contrast: 0.24,
					saturation: 0.82,
					temperature: -0.48,
					shadowTint: [-0.026, 0.01, 0.08],
				},
				extras: { vignette: 18 },
			},
			{
				id: "night-market",
				name: "Night Market",
				localizedName: "夜市烟火",
				tags: ["night", "market", "warm", "夜景", "夜市"],
				defaultIntensity: 72,
				recipe: {
					contrast: 0.22,
					saturation: 1.18,
					temperature: 0.16,
					blackLift: -0.01,
				},
				extras: { grain: 8, vignette: 10 },
			},
		],
	},
	{
		category: "cinematic",
		presets: [
			{
				id: "indie-drama",
				name: "Indie Drama",
				localizedName: "独立剧情",
				tags: ["cinema", "indie", "drama", "影视", "剧情"],
				defaultIntensity: 70,
				isNew: true,
				skinProtection: 24,
				recipe: {
					contrast: 0.18,
					saturation: 0.86,
					temperature: 0.12,
					fade: 0.04,
					shadowTint: [0.018, 0.006, -0.02],
				},
				extras: { grain: 8, vignette: 8 },
			},
			{
				id: "cold-thriller",
				name: "Cold Thriller",
				localizedName: "冷调惊悚",
				tags: ["cinema", "thriller", "cold", "影视", "冷调"],
				defaultIntensity: 68,
				recipe: {
					contrast: 0.3,
					saturation: 0.7,
					temperature: -0.32,
					blackLift: -0.018,
					shadowTint: [-0.03, 0.018, 0.05],
				},
				extras: { vignette: 18 },
			},
			{
				id: "warm-feature",
				name: "Warm Feature",
				localizedName: "暖调长片",
				tags: ["cinema", "feature", "warm", "影视", "暖调"],
				defaultIntensity: 72,
				skinProtection: 18,
				recipe: {
					contrast: 0.22,
					saturation: 0.98,
					temperature: 0.28,
					highlightTint: [0.055, 0.018, -0.032],
				},
				extras: { grain: 6, vignette: 10 },
			},
			{
				id: "silver-screen",
				name: "Silver Screen",
				localizedName: "银幕灰调",
				tags: ["cinema", "silver", "muted", "影视", "灰调"],
				defaultIntensity: 70,
				recipe: {
					contrast: 0.24,
					saturation: 0.62,
					temperature: -0.08,
					fade: 0.03,
				},
				extras: { grain: 10, vignette: 12 },
			},
			{
				id: "epic-gold",
				name: "Epic Gold",
				localizedName: "史诗金色",
				tags: ["cinema", "gold", "epic", "影视", "金色"],
				defaultIntensity: 66,
				skinProtection: 20,
				recipe: {
					contrast: 0.26,
					saturation: 1.08,
					temperature: 0.46,
					shadowTint: [-0.02, 0.014, 0.04],
					highlightTint: [0.07, 0.02, -0.04],
				},
				extras: { vignette: 14 },
			},
		],
	},
	{
		category: "outdoor",
		presets: [
			{
				id: "camp-morning",
				name: "Camp Morning",
				localizedName: "露营清晨",
				tags: ["outdoor", "camp", "morning", "户外", "露营"],
				defaultIntensity: 78,
				isNew: true,
				recipe: {
					exposure: 0.08,
					contrast: 0.1,
					saturation: 1.1,
					temperature: 0.18,
				},
				extras: { sharpness: 10 },
			},
			{
				id: "trail-sun",
				name: "Trail Sun",
				localizedName: "徒步晴光",
				tags: ["outdoor", "trail", "sun", "户外", "徒步"],
				defaultIntensity: 76,
				recipe: { contrast: 0.14, saturation: 1.16, temperature: 0.08 },
				extras: { sharpness: 12 },
			},
			{
				id: "pine-air",
				name: "Pine Air",
				localizedName: "松林空气",
				tags: ["outdoor", "pine", "fresh", "户外", "松林"],
				defaultIntensity: 74,
				recipe: {
					contrast: 0.1,
					saturation: 1.12,
					temperature: -0.08,
					tint: -0.12,
				},
				extras: { sharpness: 8 },
			},
			{
				id: "open-field",
				name: "Open Field",
				localizedName: "开阔草地",
				tags: ["outdoor", "field", "open", "户外", "草地"],
				defaultIntensity: 78,
				recipe: {
					exposure: 0.06,
					contrast: 0.08,
					saturation: 1.18,
					temperature: 0.04,
				},
			},
			{
				id: "sunset-camp",
				name: "Sunset Camp",
				localizedName: "营地日落",
				tags: ["outdoor", "sunset", "camp", "户外", "日落"],
				defaultIntensity: 74,
				recipe: {
					contrast: 0.16,
					saturation: 1.08,
					temperature: 0.44,
					highlightTint: [0.052, 0.018, -0.032],
				},
				extras: { vignette: 6 },
			},
		],
	},
	{
		category: "stylized",
		presets: [
			{
				id: "comic-bright",
				name: "Comic Bright",
				localizedName: "漫画亮彩",
				tags: ["stylized", "comic", "bright", "风格化", "漫画"],
				defaultIntensity: 62,
				isNew: true,
				recipe: {
					contrast: 0.28,
					saturation: 1.34,
					temperature: 0.04,
					hueShift: 4,
				},
				extras: { sharpness: 18 },
			},
			{
				id: "vapor-dream",
				name: "Vapor Dream",
				localizedName: "蒸汽梦境",
				tags: ["stylized", "vapor", "dream", "风格化", "梦境"],
				defaultIntensity: 64,
				recipe: {
					exposure: 0.06,
					contrast: -0.08,
					saturation: 1.12,
					tint: 0.28,
					fade: 0.12,
				},
			},
			{
				id: "electric-cyan",
				name: "Electric Cyan",
				localizedName: "电光青",
				tags: ["stylized", "cyan", "electric", "风格化", "电光"],
				defaultIntensity: 58,
				recipe: {
					contrast: 0.22,
					saturation: 1.28,
					temperature: -0.26,
					hueShift: -8,
					shadowTint: [-0.018, 0.032, 0.06],
				},
				extras: { sharpness: 10 },
			},
			{
				id: "rose-surreal",
				name: "Rose Surreal",
				localizedName: "玫瑰超现实",
				tags: ["stylized", "rose", "surreal", "风格化", "玫瑰"],
				defaultIntensity: 60,
				recipe: {
					contrast: 0.12,
					saturation: 1.2,
					tint: 0.24,
					temperature: 0.12,
				},
				extras: { vignette: 8 },
			},
			{
				id: "poster-crush",
				name: "Poster Crush",
				localizedName: "海报重彩",
				tags: ["stylized", "poster", "bold", "风格化", "重彩"],
				defaultIntensity: 56,
				recipe: {
					contrast: 0.34,
					saturation: 1.36,
					blackLift: -0.018,
					gamma: 0.96,
				},
				extras: { sharpness: 16 },
			},
		],
	},
	{
		category: "film",
		presets: [
			{
				id: "kodak-summer",
				name: "Kodak Summer",
				localizedName: "柯达夏日",
				tags: ["film", "kodak", "summer", "胶片", "夏日"],
				defaultIntensity: 74,
				isNew: true,
				recipe: {
					contrast: 0.08,
					saturation: 0.98,
					temperature: 0.32,
					fade: 0.08,
				},
				extras: { grain: 14, vignette: 6 },
			},
			{
				id: "cinestill-night",
				name: "Cinestill Night",
				localizedName: "电影卷夜色",
				tags: ["film", "cinestill", "night", "胶片", "夜色"],
				defaultIntensity: 70,
				recipe: {
					contrast: 0.18,
					saturation: 0.92,
					temperature: -0.12,
					shadowTint: [-0.018, 0.01, 0.04],
				},
				extras: { grain: 18, vignette: 10 },
			},
			{
				id: "expired-roll",
				name: "Expired Roll",
				localizedName: "过期胶卷",
				tags: ["film", "expired", "roll", "胶片", "过期"],
				defaultIntensity: 72,
				recipe: {
					contrast: -0.08,
					saturation: 0.76,
					temperature: 0.18,
					tint: 0.16,
					fade: 0.2,
				},
				extras: { grain: 22 },
			},
			{
				id: "slide-film",
				name: "Slide Film",
				localizedName: "反转片",
				tags: ["film", "slide", "vivid", "胶片", "反转片"],
				defaultIntensity: 76,
				recipe: {
					contrast: 0.2,
					saturation: 1.16,
					temperature: 0.04,
					blackLift: -0.01,
				},
				extras: { grain: 8, sharpness: 6 },
			},
			{
				id: "matte-print",
				name: "Matte Print",
				localizedName: "哑光冲印",
				tags: ["film", "matte", "print", "胶片", "哑光"],
				defaultIntensity: 74,
				recipe: { contrast: -0.02, saturation: 0.88, fade: 0.14, gamma: 1.06 },
				extras: { grain: 12 },
			},
		],
	},
	{
		category: "monochrome",
		presets: [
			{
				id: "soft-charcoal",
				name: "Soft Charcoal",
				localizedName: "柔炭黑白",
				tags: ["monochrome", "charcoal", "soft", "黑白", "柔和"],
				defaultIntensity: 92,
				isNew: true,
				recipe: { monochrome: 1, contrast: -0.02, fade: 0.08, gamma: 1.05 },
				extras: { grain: 8 },
			},
			{
				id: "street-contrast",
				name: "Street Contrast",
				localizedName: "街拍高反差",
				tags: ["monochrome", "street", "contrast", "黑白", "街拍"],
				defaultIntensity: 94,
				recipe: {
					monochrome: 1,
					contrast: 0.32,
					blackLift: -0.022,
					gamma: 0.97,
				},
				extras: { grain: 12, sharpness: 10 },
			},
			{
				id: "pearl-mono",
				name: "Pearl Mono",
				localizedName: "珍珠黑白",
				tags: ["monochrome", "pearl", "bright", "黑白", "明亮"],
				defaultIntensity: 90,
				recipe: { monochrome: 1, exposure: 0.08, contrast: 0.04, gamma: 1.04 },
			},
			{
				id: "newsprint-mono",
				name: "Newsprint Mono",
				localizedName: "报纸颗粒",
				tags: ["monochrome", "newsprint", "grain", "黑白", "颗粒"],
				defaultIntensity: 96,
				recipe: { monochrome: 1, contrast: 0.18, saturation: 0.7, fade: 0.04 },
				extras: { grain: 20, sharpness: 8 },
			},
			{
				id: "deep-ink",
				name: "Deep Ink",
				localizedName: "深墨黑白",
				tags: ["monochrome", "ink", "deep", "黑白", "深墨"],
				defaultIntensity: 94,
				recipe: {
					monochrome: 1,
					contrast: 0.38,
					blackLift: -0.03,
					gamma: 0.94,
				},
				extras: { vignette: 10, sharpness: 8 },
			},
		],
	},
	{
		category: "portrait",
		presets: [
			{
				id: "milk-skin",
				name: "Milk Skin",
				localizedName: "奶油肌",
				tags: ["portrait", "skin", "soft", "人像", "奶油肌"],
				defaultIntensity: 66,
				isNew: true,
				skinProtection: 62,
				recipe: {
					exposure: 0.08,
					contrast: -0.08,
					saturation: 0.98,
					temperature: 0.18,
					tint: 0.08,
				},
			},
			{
				id: "clean-beauty",
				name: "Clean Beauty",
				localizedName: "清透美颜",
				tags: ["portrait", "beauty", "clean", "人像", "清透"],
				defaultIntensity: 68,
				skinProtection: 58,
				recipe: {
					exposure: 0.1,
					contrast: -0.03,
					saturation: 1.02,
					temperature: 0.12,
				},
				extras: { sharpness: 4 },
			},
			{
				id: "cool-editorial",
				name: "Cool Editorial",
				localizedName: "冷调大片",
				tags: ["portrait", "editorial", "cool", "人像", "大片"],
				defaultIntensity: 70,
				skinProtection: 42,
				recipe: {
					contrast: 0.14,
					saturation: 0.92,
					temperature: -0.24,
					shadowTint: [-0.02, 0.014, 0.045],
				},
				extras: { sharpness: 8 },
			},
			{
				id: "peach-window",
				name: "Peach Window",
				localizedName: "窗边蜜桃",
				tags: ["portrait", "peach", "window", "人像", "蜜桃"],
				defaultIntensity: 66,
				skinProtection: 60,
				recipe: {
					exposure: 0.08,
					contrast: -0.05,
					saturation: 1.04,
					temperature: 0.24,
					tint: 0.12,
				},
			},
			{
				id: "studio-clear",
				name: "Studio Clear",
				localizedName: "棚拍清晰",
				tags: ["portrait", "studio", "clear", "人像", "棚拍"],
				defaultIntensity: 72,
				skinProtection: 48,
				recipe: {
					contrast: 0.1,
					saturation: 0.98,
					temperature: 0.02,
					gamma: 1.01,
				},
				extras: { sharpness: 10 },
			},
		],
	},
	{
		category: "hd",
		presets: [
			{
				id: "micro-detail",
				name: "Micro Detail",
				localizedName: "微细节",
				tags: ["hd", "detail", "micro", "高清", "细节"],
				defaultIntensity: 58,
				isNew: true,
				recipe: { contrast: 0.1, saturation: 1.02, gamma: 0.99 },
				extras: { sharpness: 42 },
			},
			{
				id: "edge-clean",
				name: "Edge Clean",
				localizedName: "边缘清晰",
				tags: ["hd", "edge", "clean", "高清", "边缘"],
				defaultIntensity: 56,
				recipe: { contrast: 0.08, saturation: 0.98, blackLift: -0.006 },
				extras: { sharpness: 48 },
			},
			{
				id: "texture-rise",
				name: "Texture Rise",
				localizedName: "纹理提升",
				tags: ["hd", "texture", "sharp", "高清", "纹理"],
				defaultIntensity: 60,
				recipe: { contrast: 0.14, saturation: 1.06, gamma: 0.98 },
				extras: { sharpness: 36 },
			},
			{
				id: "bright-hd",
				name: "Bright HD",
				localizedName: "明亮高清",
				tags: ["hd", "bright", "clear", "高清", "明亮"],
				defaultIntensity: 62,
				recipe: {
					exposure: 0.06,
					contrast: 0.08,
					saturation: 1.04,
					gamma: 1.01,
				},
				extras: { sharpness: 26 },
			},
			{
				id: "natural-8k",
				name: "Natural 8K",
				localizedName: "自然 8K",
				tags: ["hd", "8k", "natural", "高清", "自然"],
				defaultIntensity: 58,
				recipe: { contrast: 0.06, saturation: 1.02, temperature: 0.02 },
				extras: { sharpness: 32 },
			},
		],
	},
	{
		category: "indoor",
		presets: [
			{
				id: "apartment-day",
				name: "Apartment Day",
				localizedName: "公寓日光",
				tags: ["indoor", "apartment", "daylight", "室内", "日光"],
				defaultIntensity: 78,
				isNew: true,
				recipe: {
					exposure: 0.1,
					contrast: 0.02,
					saturation: 0.98,
					temperature: 0.08,
				},
				extras: { sharpness: 6 },
			},
			{
				id: "warm-lamp",
				name: "Warm Lamp",
				localizedName: "暖灯",
				tags: ["indoor", "lamp", "warm", "室内", "暖灯"],
				defaultIntensity: 74,
				recipe: {
					exposure: 0.04,
					contrast: 0.08,
					saturation: 1.04,
					temperature: 0.46,
					highlightTint: [0.042, 0.016, -0.026],
				},
				extras: { vignette: 5 },
			},
			{
				id: "museum-soft",
				name: "Museum Soft",
				localizedName: "展馆柔光",
				tags: ["indoor", "museum", "soft", "室内", "展馆"],
				defaultIntensity: 76,
				recipe: {
					exposure: 0.08,
					contrast: -0.02,
					saturation: 0.9,
					temperature: -0.04,
				},
			},
			{
				id: "studio-white",
				name: "Studio White",
				localizedName: "棚内白光",
				tags: ["indoor", "studio", "white", "室内", "白光"],
				defaultIntensity: 78,
				recipe: {
					exposure: 0.12,
					contrast: 0.04,
					saturation: 0.94,
					temperature: -0.08,
				},
				extras: { sharpness: 8 },
			},
			{
				id: "cozy-evening",
				name: "Cozy Evening",
				localizedName: "舒适傍晚",
				tags: ["indoor", "cozy", "evening", "室内", "傍晚"],
				defaultIntensity: 72,
				recipe: {
					contrast: 0.08,
					saturation: 1.02,
					temperature: 0.34,
					fade: 0.04,
					shadowTint: [0.018, 0.006, -0.014],
				},
				extras: { vignette: 6 },
			},
		],
	},
];

function createExpansionPreset({
	category,
	spec,
}: {
	category: FilterCategory;
	spec: FilterExpansionPresetSpec;
}): FilterPreset {
	return {
		...spec,
		version: 1,
		category,
		thumbnail: `/images/filter-previews/${spec.id}.webp`,
		lutAssetId: `qcut/filter/${spec.id}/v1`,
	};
}

export const CATEGORY_EXPANSION_FILTER_PRESETS: FilterPreset[] =
	CATEGORY_EXPANSIONS.flatMap(({ category, presets }) =>
		presets.map((spec) => createExpansionPreset({ category, spec }))
	);
