import type { FilterCategory, FilterPreset } from "./filter-types";
import { CATEGORY_EXPANSION_FILTER_PRESETS } from "./filter-category-expansion-presets";
import { COLLECTION_FILTER_PRESETS } from "./filter-collection-presets";
import { EXTENDED_FILTER_PRESETS } from "./filter-extended-presets";

export const FILTER_NONE_ID = "none";

const CORE_FILTER_PRESETS: FilterPreset[] = [
	{
		id: "clean",
		version: 1,
		name: "Clean",
		localizedName: "清透",
		category: "basic",
		tags: ["natural", "clear", "neutral", "自然", "清晰"],
		thumbnail: "/images/filter-previews/clean.webp",
		lutAssetId: "qcut/filter/clean/v1",
		defaultIntensity: 85,
		recipe: { contrast: 0.05, saturation: 1.03, gamma: 1.02 },
		extras: { sharpness: 8 },
	},
	{
		id: "vivid",
		version: 1,
		name: "Vivid",
		localizedName: "鲜明",
		category: "basic",
		tags: ["colorful", "punchy", "bright", "鲜艳", "高饱和"],
		thumbnail: "/images/filter-previews/vivid.webp",
		lutAssetId: "qcut/filter/vivid/v1",
		defaultIntensity: 80,
		recipe: { contrast: 0.14, saturation: 1.2, gamma: 1.01 },
		extras: { sharpness: 10 },
	},
	{
		id: "soft",
		version: 1,
		name: "Soft",
		localizedName: "柔光",
		category: "basic",
		tags: ["gentle", "low contrast", "pastel", "柔和", "低对比"],
		thumbnail: "/images/filter-previews/soft.webp",
		lutAssetId: "qcut/filter/soft/v1",
		defaultIntensity: 75,
		recipe: { contrast: -0.08, saturation: 0.94, fade: 0.08, gamma: 1.05 },
	},
	{
		id: "sunlight",
		version: 1,
		name: "Sunlight",
		localizedName: "晴日",
		category: "summer",
		tags: ["summer", "sunny", "warm", "夏日", "阳光"],
		thumbnail: "/images/filter-previews/sunlight.webp",
		lutAssetId: "qcut/filter/sunlight/v1",
		defaultIntensity: 82,
		recipe: {
			exposure: 0.08,
			contrast: 0.08,
			saturation: 1.1,
			temperature: 0.34,
			highlightTint: [0.045, 0.018, -0.025],
		},
	},
	{
		id: "coastal",
		version: 1,
		name: "Coastal",
		localizedName: "海岸",
		category: "summer",
		tags: ["sea", "travel", "cyan", "海边", "旅行"],
		thumbnail: "/images/filter-previews/coastal.webp",
		lutAssetId: "qcut/filter/coastal/v1",
		defaultIntensity: 80,
		recipe: {
			contrast: 0.1,
			saturation: 1.14,
			temperature: -0.1,
			shadowTint: [-0.018, 0.018, 0.04],
			highlightTint: [0.025, 0.012, -0.01],
		},
	},
	{
		id: "fresh-green",
		version: 1,
		name: "Fresh Green",
		localizedName: "青翠",
		category: "summer",
		tags: ["nature", "green", "fresh", "清新", "绿色"],
		thumbnail: "/images/filter-previews/fresh-green.webp",
		lutAssetId: "qcut/filter/fresh-green/v1",
		defaultIntensity: 78,
		recipe: {
			contrast: 0.08,
			saturation: 1.12,
			temperature: -0.04,
			tint: -0.12,
			hueShift: -2,
		},
	},
	{
		id: "alpine",
		version: 1,
		name: "Alpine",
		localizedName: "雪岭",
		category: "landscape",
		tags: ["mountain", "crisp", "landscape", "山景", "通透"],
		thumbnail: "/images/filter-previews/alpine.webp",
		lutAssetId: "qcut/filter/alpine/v1",
		defaultIntensity: 82,
		recipe: {
			contrast: 0.17,
			saturation: 1.12,
			temperature: -0.12,
			shadowTint: [-0.01, 0.012, 0.035],
		},
		extras: { sharpness: 14 },
	},
	{
		id: "ocean-blue",
		version: 1,
		name: "Ocean Blue",
		localizedName: "深海蓝",
		category: "landscape",
		tags: ["ocean", "blue", "cool", "海洋", "蓝调"],
		thumbnail: "/images/filter-previews/ocean-blue.webp",
		lutAssetId: "qcut/filter/ocean-blue/v1",
		defaultIntensity: 76,
		recipe: {
			contrast: 0.16,
			saturation: 1.2,
			temperature: -0.34,
			shadowTint: [-0.025, 0.015, 0.065],
			hueShift: -3,
		},
	},
	{
		id: "golden-hour",
		version: 1,
		name: "Golden Hour",
		localizedName: "黄金时刻",
		category: "landscape",
		tags: ["sunset", "gold", "warm", "日落", "金色"],
		thumbnail: "/images/filter-previews/golden-hour.webp",
		lutAssetId: "qcut/filter/golden-hour/v1",
		defaultIntensity: 78,
		recipe: {
			exposure: 0.06,
			contrast: 0.1,
			saturation: 1.08,
			temperature: 0.62,
			tint: 0.08,
			highlightTint: [0.065, 0.025, -0.04],
		},
	},
	{
		id: "warm-table",
		version: 1,
		name: "Warm Table",
		localizedName: "暖餐桌",
		category: "food",
		tags: ["food", "cafe", "warm", "美食", "咖啡"],
		thumbnail: "/images/filter-previews/warm-table.webp",
		lutAssetId: "qcut/filter/warm-table/v1",
		defaultIntensity: 80,
		recipe: { contrast: 0.08, saturation: 1.08, temperature: 0.38 },
		extras: { sharpness: 6 },
	},
	{
		id: "rich-food",
		version: 1,
		name: "Rich Food",
		localizedName: "浓香",
		category: "food",
		tags: ["food", "rich", "color", "美食", "浓郁"],
		thumbnail: "/images/filter-previews/rich-food.webp",
		lutAssetId: "qcut/filter/rich-food/v1",
		defaultIntensity: 74,
		recipe: { contrast: 0.2, saturation: 1.24, temperature: 0.18, gamma: 0.98 },
		extras: { sharpness: 12, vignette: 5 },
	},
	{
		id: "teal-gold",
		version: 1,
		name: "Teal Gold",
		localizedName: "青橙电影",
		category: "cinematic",
		tags: ["cinema", "teal", "orange", "电影", "青橙"],
		thumbnail: "/images/filter-previews/teal-gold.webp",
		lutAssetId: "qcut/filter/teal-gold/v1",
		defaultIntensity: 72,
		skinProtection: 28,
		recipe: {
			contrast: 0.22,
			saturation: 1.08,
			shadowTint: [-0.045, 0.038, 0.075],
			highlightTint: [0.07, 0.022, -0.035],
		},
		extras: { vignette: 12 },
	},
	{
		id: "bleach-bypass",
		version: 1,
		name: "Bleach Bypass",
		localizedName: "银留",
		category: "cinematic",
		tags: ["cinema", "desaturated", "hard", "电影", "低饱和"],
		thumbnail: "/images/filter-previews/bleach-bypass.webp",
		lutAssetId: "qcut/filter/bleach-bypass/v1",
		defaultIntensity: 68,
		recipe: {
			contrast: 0.32,
			saturation: 0.48,
			blackLift: -0.018,
			gamma: 0.96,
		},
		extras: { grain: 12, vignette: 10, sharpness: 8 },
	},
	{
		id: "night-blue",
		version: 1,
		name: "Night Blue",
		localizedName: "夜幕蓝",
		category: "night",
		tags: ["night", "moody", "blue", "夜景", "冷调"],
		thumbnail: "/images/filter-previews/night-blue.webp",
		lutAssetId: "qcut/filter/night-blue/v1",
		defaultIntensity: 76,
		recipe: {
			exposure: -0.08,
			contrast: 0.24,
			saturation: 0.94,
			temperature: -0.42,
			shadowTint: [-0.035, 0.008, 0.08],
		},
		extras: { vignette: 16 },
	},
	{
		id: "soft-negative",
		version: 1,
		name: "Soft Negative",
		localizedName: "柔和负片",
		category: "film",
		tags: ["film", "negative", "matte", "胶片", "褪色"],
		thumbnail: "/images/filter-previews/soft-negative.webp",
		lutAssetId: "qcut/filter/soft-negative/v1",
		defaultIntensity: 78,
		recipe: {
			contrast: -0.04,
			saturation: 0.88,
			fade: 0.13,
			gamma: 1.08,
			temperature: 0.08,
		},
		extras: { grain: 14 },
	},
	{
		id: "warm-film",
		version: 1,
		name: "Warm Film",
		localizedName: "暖胶片",
		category: "film",
		tags: ["film", "warm", "nostalgic", "胶片", "怀旧"],
		thumbnail: "/images/filter-previews/warm-film.webp",
		lutAssetId: "qcut/filter/warm-film/v1",
		defaultIntensity: 76,
		recipe: {
			contrast: 0.08,
			saturation: 0.94,
			temperature: 0.3,
			fade: 0.08,
			shadowTint: [0.025, 0.004, -0.018],
		},
		extras: { grain: 10, vignette: 8 },
	},
	{
		id: "neutral-mono",
		version: 1,
		name: "Neutral Mono",
		localizedName: "中性黑白",
		category: "monochrome",
		tags: ["black white", "mono", "classic", "黑白", "中性"],
		thumbnail: "/images/filter-previews/neutral-mono.webp",
		lutAssetId: "qcut/filter/neutral-mono/v1",
		defaultIntensity: 100,
		recipe: { monochrome: 1, contrast: 0.08 },
	},
	{
		id: "hard-mono",
		version: 1,
		name: "Hard Mono",
		localizedName: "硬朗黑白",
		category: "monochrome",
		tags: ["black white", "contrast", "street", "黑白", "高对比"],
		thumbnail: "/images/filter-previews/hard-mono.webp",
		lutAssetId: "qcut/filter/hard-mono/v1",
		defaultIntensity: 92,
		recipe: { monochrome: 1, contrast: 0.36, blackLift: -0.025, gamma: 0.96 },
		extras: { grain: 16, vignette: 12, sharpness: 8 },
	},
	{
		id: "soft-skin",
		version: 1,
		name: "Soft Skin",
		localizedName: "柔肤色调",
		category: "portrait",
		tags: ["portrait", "skin", "soft", "人像", "肤色"],
		thumbnail: "/images/filter-previews/soft-skin.webp",
		lutAssetId: "qcut/filter/soft-skin/v1",
		defaultIntensity: 70,
		skinProtection: 48,
		recipe: {
			exposure: 0.05,
			contrast: -0.04,
			saturation: 0.97,
			temperature: 0.14,
			fade: 0.035,
		},
	},
	{
		id: "cool-fashion",
		version: 1,
		name: "Cool Fashion",
		localizedName: "冷调时尚",
		category: "portrait",
		tags: ["portrait", "fashion", "cool", "人像", "时尚"],
		thumbnail: "/images/filter-previews/cool-fashion.webp",
		lutAssetId: "qcut/filter/cool-fashion/v1",
		defaultIntensity: 72,
		skinProtection: 40,
		recipe: {
			contrast: 0.12,
			saturation: 0.96,
			temperature: -0.22,
			tint: 0.08,
			shadowTint: [-0.018, 0.012, 0.04],
		},
		extras: { sharpness: 6 },
	},
];

export const FILTER_PRESETS: FilterPreset[] = [
	...CORE_FILTER_PRESETS,
	...EXTENDED_FILTER_PRESETS,
	...CATEGORY_EXPANSION_FILTER_PRESETS,
	...COLLECTION_FILTER_PRESETS,
];

const presetsById = new Map(
	FILTER_PRESETS.map((preset) => [preset.id, preset])
);

export function getFilterPreset({ presetId }: { presetId: string }) {
	return presetsById.get(presetId);
}

export function getFilterPresetsByCategory({
	category,
}: {
	category: FilterCategory;
}) {
	return FILTER_PRESETS.filter((preset) => preset.category === category);
}
