/**
 * @qcut/editor-core — Platform-agnostic editor domain logic for QCut.
 *
 * This package contains:
 * - Domain types (timeline, project, editor, captions)
 * - Timeline utility functions (track management, element operations)
 * - Type guards and validation
 * - History/undo-redo command pattern
 * - Storage provider interface
 *
 * No React, Zustand, or Electron dependencies.
 *
 * @module @qcut/editor-core
 */

// Types
export type {
	BackgroundType,
	CanvasSize,
	CanvasMode,
	CanvasPreset,
	ColorBasicSettings,
	ColorCubeLut,
	ColorDualLutSettings,
	ColorCurvePoint,
	ColorCurveShapeKeyframe,
	ColorCurveShapeProperty,
	ColorCurvesSettings,
	ColorFilterApplication,
	ColorSecondaryCurve,
	ColorSecondaryCurveName,
	ColorSecondaryCurvesSettings,
	ColorGradeMaskSettings,
	ColorHslKeyframeProperty,
	ColorHslRangeName,
	ColorHslRangeSettings,
	ColorHslSettings,
	ColorKeyframeProperty,
	ColorLutSettings,
	ColorMultiPassOperation,
	ColorMultiPassSettings,
	ColorManagementSettings,
	ColorPropertyKeyframe,
	ColorSmartSettings,
	ColorSpace,
	ColorWheelKeyframeProperty,
	ColorWheelSettings,
	ColorWheelsSettings,
	MediaColorSettings,
	BlurIntensity,
	DraftInteropProjectBindingV1,
	DraftInteropWritebackStatus,
	ProjectFolder,
	ProjectGuides,
	ProjectTimelineSettings,
	Scene,
	TProject,
	MediaType,
	TrackType,
	MediaElement,
	EffectElement,
	CompoundMediaClip,
	MediaCompound,
	MediaBlendMode,
	MediaFitMode,
	MediaCrop,
	MediaPerspective,
	MediaKeyframeProperty,
	MediaPropertyKeyframe,
	MediaAnimationType,
	MediaComboAnimationType,
	StickerAnimationLoopType,
	StickerMotionTracking,
	StickerTrackingAnchor,
	ClipTransition,
	ClipTransitionDirection,
	ClipTransitionEngine,
	ClipTransitionEasing,
	ClipTransitionMaskShape,
	ClipTransitionKeyframeEasing,
	ClipTransitionTuning,
	ClipTransitionTuningKeyframe,
	ClipTransitionTuningKeyframes,
	ClipTransitionTuningProperty,
	ClipTransitionType,
	MediaAdjustments,
	MediaMask,
	MediaMaskType,
	MediaMaskBlendMode,
	MediaMaskMirrorMode,
	MediaMaskKeyframeProperty,
	MediaMaskPoint,
	MediaMaskStroke,
	MediaMaskStrokeStyle,
	MediaMaskTracking,
	MediaMaskTrackingDirection,
	MediaCustomCutout,
	MediaCustomCutoutBrushMode,
	MediaCustomCutoutPoint,
	MediaCustomCutoutStroke,
	MediaChromaKey,
	MediaChromaKeyKeyframeProperty,
	MediaEnhancements,
	AudioKeyframeProperty,
	AudioLoudnessSettings,
	AudioDenoiseSettings,
	AudioVoiceEnhanceSettings,
	AudioPitchSettings,
	AudioEqualizerSettings,
	AudioCompressorSettings,
	AudioLimiterSettings,
	AudioReverbSettings,
	AudioEchoSettings,
	AudioTelephoneSettings,
	AudioChannelMode,
	AudioParametricFilterType,
	AudioParametricEqBand,
	AudioParametricEqualizerSettings,
	AudioRepairSettings,
	AudioDuckingSettings,
	AudioAutoCrossfadeSettings,
	AudioCrossfade,
	AudioBusEffectsSettings,
	TimelineTrackAudioSettings,
	AudioMixBusSettings,
	ProjectAudioMixSettings,
	AudioStemName,
	AudioSeparationSettings,
	AudioVoiceConversionSettings,
	AudioCoverSettings,
	AudioLyricsWord,
	AudioLyricsSettings,
	MediaAudioSettings,
	TextElement,
	TextFontAssetReference,
	JianyingTextEditMode,
	JianyingTextPackageKind,
	JianyingTextSlotMapping,
	JianyingTextStyleReference,
	JianyingTextTimeMapping,
	TextKeyframeProperty,
	TextPropertyKeyframe,
	StickerElement,
	StickerKeyframeProperty,
	StickerPropertyKeyframe,
	AdjustmentElement,
	CaptionElement,
	SubtitleStyle,
	RemotionElement,
	HyperframesElement,
	HyperframesVariableDefinition,
	HyperframesVariableType,
	HyperframesVariableValue,
	MarkdownElement,
	TimelineElement,
	CreateMediaElement,
	CreateEffectElement,
	CreateTextElement,
	CreateStickerElement,
	CreateAdjustmentElement,
	CreateCaptionElement,
	CreateRemotionElement,
	CreateHyperframesElement,
	CreateMarkdownElement,
	CreateTimelineElement,
	TimelineTrack,
	MediaItemDragData,
	TextItemDragData,
	StickerItemDragData,
	RemotionItemDragData,
	HyperframesItemDragData,
	MarkdownItemDragData,
	DragData,
	TranscriptionSegment,
	TranscriptionResult,
	TranscriptionRequest,
	TranscriptionError,
	CaptionSegment,
	CaptionTrackData,
	TranscriptionStatus,
	TranscriptionProgress,
	CaptionFormat,
	CaptionExportOptions,
	AnimatedParameter,
	EffectAudioCompanion,
	EffectTimelineRange,
	EffectChain,
	EffectEngine,
	EffectInstance,
	EffectKeyframe,
	EffectParameters,
	EffectType,
	EffectAudioReactiveRenderStage,
	EffectAudioReactiveEnvelope,
	EffectAudioReactiveKeyframe,
	EffectCompositeRenderStage,
	EffectDecorationRenderStage,
	EffectDecorationVariant,
	EffectDistortionRenderStage,
	EffectDistortionVariant,
	EffectFilterRenderStage,
	EffectMotionChannel,
	EffectMotionProperty,
	EffectMotionRenderStage,
	EffectMotionWaveform,
	EffectOverlayRenderStage,
	EffectParticleRenderStage,
	EffectParticleVariant,
	EffectPersonTrackingRenderStage,
	EffectRenderProgram,
	EffectRenderWindow,
	EffectRenderStage,
	EffectRenderStageKind,
} from "./types/index.js";

export {
	DEFAULT_PROJECT_TIMELINE_SETTINGS,
	resolveProjectTimelineSettings,
} from "./types/project.js";

export { normalizeJianyingTextStyleReference } from "./jianying-text-reference.js";

export {
	compileTextAnimation,
	evaluateTextAnimationFrame,
	IDENTITY_TEXT_ANIMATION_VISUAL_STATE,
	isCanonicalTextAnimations,
	normalizeTextAnimations,
	evaluateTextKeyframeTrack,
	mixTextAnimationColors,
	parseTextAnimationHexColor,
	sampleTextAnimationPalette,
	segmentGraphemesFallback,
	segmentText,
	TEXT_ANIMATION_SCHEMA_VERSION,
} from "./text-animation/index.js";

export type {
	CompiledTextAnimation,
	CompiledTextAnimationPhase,
	CompiledTextAnimationUnit,
	TextAnimationActivePhase,
	TextAnimationDecorationState,
	TextAnimationDirection,
	TextAnimationDistance,
	TextAnimationEasing,
	TextAnimationEdgePhase,
	TextAnimationEffect,
	TextAnimationFrameState,
	TextAnimationGraphemeLayout,
	TextAnimationLayout,
	TextAnimationLoopPhase,
	TextAnimationMaskState,
	TextAnimationOrder,
	TextAnimationPhaseBase,
	TextAnimationPostProcessState,
	TextAnimationProjectionState,
	TextAnimationPresetRef,
	TextAnimationRect,
	TextAnimations,
	TextAnimationsV1,
	TextAnimationSegment,
	TextAnimationSequence,
	TextAnimationTarget,
	TextAnimationTiming,
	TextAnimationUnit,
	TextAnimationUnitState,
	TextAnimationVisualState,
	TextBlurEffect,
	TextBounceEffect,
	TextFadeEffect,
	TextFlipEffect,
	TextFlip3DEffect,
	TextCylinder3DEffect,
	TextJitter3DEffect,
	TextJitterEffect,
	TextArcEffect,
	TextSqueezeEffect,
	TextFoldEffect,
	TextSpiralEffect,
	TextScatterEffect,
	TextTumbleEffect,
	TextShatterEffect,
	TextAnimationShatterState,
	TextHeartEffect,
	TextLaserEffect,
	TextOrbitEffect,
	TextRotateEffect,
	TextScaleEffect,
	TextSlideEffect,
	TextTypewriterEffect,
	TextColorCycleEffect,
	TextKeyframesEffect,
	TextKeyframeChannel,
	TextKeyframePoint,
	TextAnimationColorMixState,
	TextAnimationNormalizationIssue,
	TextAnimationNormalizationResult,
	TextAnimationNormalizationSource,
} from "./text-animation/index.js";

export {
	collectEffectRenderStageKinds,
	combineEffectRenderPrograms,
	EFFECT_KEYFRAME_PARAMETER_KEYS,
	findEffectKeyframeAtTime,
	isEffectKeyframeParameter,
	removeEffectKeyframe,
	resolveEffectAnimationValue,
	resolveEffectParametersAtTime,
	trimEffectAnimations,
	upsertEffectKeyframe,
	withEffectRenderWindow,
	validateEffectRenderProgram,
	sampleEffectParticles,
	sampleDistortionSource,
	type EffectKeyframeParameter,
	type EffectRenderProgramValidation,
	type SampledEffectParticle,
	type DistortionSample,
} from "./effects/index.js";

// Timeline utilities
export {
	sortTracksByOrder,
	normalizeTrackOrder,
	moveTrack,
	compareTrackTypePriority,
	buildCompositionPlan,
	getMainTrack,
	ensureMainTrack,
	getTrackName,
	createTrack,
	getEffectiveDuration,
	getElementEndTime,
	getElementNameWithSuffix,
	CLIP_TRANSITION_MAX_DURATION_SECONDS,
	CLIP_TRANSITION_MIN_DURATION_SECONDS,
	CLIP_TRANSITION_TYPES,
	TRANSITION_SEAM_TOLERANCE_SECONDS,
	clampClipTransitionDuration,
	findClosestMediaSeam,
	getAudioCrossfadeMaxDuration,
	getTransitionMaxDuration,
	isClipTransitionEasing,
	isClipTransitionType,
	reconcileTrackAudioCrossfades,
	reconcileTimelineTransitions,
	reconcileTrackTransitions,
	resolveAudioCrossfade,
	resolveClipTransition,
	type ResolvedAudioCrossfade,
	isMediaElement,
	isEffectElement,
	isTextElement,
	isStickerElement,
	isAdjustmentElement,
	isCaptionElement,
	isRemotionElement,
	isHyperframesElement,
	isMarkdownElement,
	getRemotionElements,
	getActiveRemotionElements,
	getHyperframesElements,
	getActiveHyperframesElements,
	canElementGoOnTrack,
	validateElementTrackCompatibility,
	collectTimelineEffectsByTarget,
	getEffectRenderWindow,
	getTimelineEffectsAtTime,
} from "./timeline/index.js";

export type {
	BuildCompositionPlanOptions,
	CompositionAudioElement,
	CompositionDurationContext,
	CompositionLayer,
	CompositionPlan,
	MediaSeam,
	ResolvedClipTransition,
} from "./timeline/index.js";

// Commands (history/undo-redo)
export {
	type HistoryState,
	createHistory,
	pushState,
	undo,
	redo,
	canUndo,
	canRedo,
	clearHistory,
} from "./commands/index.js";

// Storage interface
export type { EditorStorageProvider } from "./storage/index.js";

// Transcription persistence types
export type {
	PersistedTranscriptionWord,
	PersistedTranscriptionSegment,
	PersistedTranscription,
	TranscriptionAvailability,
} from "./types/index.js";

// Search
export {
	searchTranscriptions,
	type SearchResult,
	type SearchOptions,
} from "./search/index.js";

// Captions — shared subtitle utilities (CLI + renderer)
export {
	DEFAULT_SUBTITLE_STYLE,
	resolveSubtitleStyle,
	hexToRgba,
	rgbToASSColor,
	assColorToRgb,
	alignToASSAlignment,
	assAlignmentToAlign,
	assAlignmentToTextAlign,
	CAPTION_ANIMATION_TYPES,
	resolveCaptionAnimation,
	getCaptionAnimationState,
	type CaptionAnimationState,
	generateASS,
	secondsToASSTime,
	parseASS,
	assTimeToSeconds,
	assStyleToSubtitleStyle,
	type ASSGeneratorOptions,
	type ASSStyle,
	type ASSEvent,
	type ASSDocument,
} from "./captions/index.js";

// Audio — beat detection engine
export {
	analyzeFromSamples,
	resolveConfig as resolveBeatConfig,
	type Beat,
	type BeatDetectionConfig,
	type BeatDetectionResult,
	type ResolvedBeatDetectionConfig,
} from "./audio/index.js";

// Assets — shared manifest, catalog, licensing, and cache state
export {
	ASSET_FILE_ROLES,
	ASSET_KINDS,
	ASSET_MANIFEST_SCHEMA_VERSION,
	assetManifestIdentity,
	assetManifestVersionKey,
	buildAssetCatalog,
	createInitialAssetRuntimeState,
	getAssetManifestFile,
	queryAssetCatalog,
	resolveAssetManifestEntry,
	validateAssetManifestPack,
	type AssetCacheStatus,
	type AssetCatalog,
	type AssetCatalogQuery,
	type AssetCommercialUse,
	type AssetDelivery,
	type AssetDownloadStatus,
	type AssetFileRole,
	type AssetKind,
	type AssetLicense,
	type AssetManifestEntry,
	type AssetManifestFile,
	type AssetManifestPack,
	type AssetManifestValidationCode,
	type AssetManifestValidationIssue,
	type AssetManifestValidationResult,
	type AssetRuntimeFileState,
	type AssetRuntimeState,
} from "./assets/index.js";

// Collaboration — portable review packages and deterministic conflict merging
export {
	MAX_REVIEW_COMMENT_LENGTH,
	MAX_REVIEW_COMMENTS,
	REVIEW_PACKAGE_VERSION,
	isPortableReviewComment,
	isReviewPackage,
	mergeReviewComments,
	type PortableReviewComment,
	type ReviewPackage,
} from "./collaboration/index.js";

// Templates — versioned slot-based timeline template protocol
export {
	TEMPLATE_ASPECT_RATIOS,
	TIMELINE_TEMPLATE_SCHEMA,
	TIMELINE_TEMPLATE_SCHEMA_VERSION,
	migrateTemplateSlotValues,
	migrateTimelineTemplate,
	resolveTemplateFontDependencies,
	resolveTimelineTemplateVariant,
	validateTemplateSlotValues,
	validateTimelineTemplate,
	type LegacyTimelineTemplateV1,
	type TemplateAspectRatio,
	type TemplateFontDependency,
	type TemplateInstanceBinding,
	type TemplateMediaPlacement,
	type TemplateMediaSlot,
	type TemplateTextPlacement,
	type TemplateTextSlot,
	type TimelineTemplate,
	type TimelineTemplateDocument,
	type TimelineTemplatePlacement,
	type TimelineTemplateSlot,
	type TimelineTemplateSlotValue,
	type TimelineTemplateSlotValues,
	type TimelineTemplateValidationCode,
	type TimelineTemplateValidationIssue,
	type TimelineTemplateValidationResult,
	type TimelineTemplateVariant,
	type TimelineTemplateVersionMigration,
} from "./templates/index.js";

export {
	buildSmartPackagingPlan,
	type SmartPackagingAction,
	type SmartPackagingBeat,
	type SmartPackagingCaption,
	type SmartPackagingOptions,
	type SmartPackagingPlan,
	type SmartPackagingShot,
} from "./templates/index.js";

// Utils
export { generateUUID } from "./utils.js";

export { computeShatterTiles, shatterNoise } from "./text-animation/shatter.js";
export type { ShatterTile } from "./text-animation/shatter.js";
