/**
 * @qcut/editor-core — Platform-agnostic editor domain logic for QCut.
 *
 * This package contains:
 * - Domain types (timeline, project, editor, captions)
 * - Timeline utility functions (track management, element operations)
 * - Type guards and validation
 * - History/undo-redo command pattern
 * - Storage provider interface
 *
 * No React, Zustand, or Electron dependencies.
 *
 * @module @qcut/editor-core
 */

// Types
export type {
	BackgroundType,
	CanvasSize,
	CanvasMode,
	CanvasPreset,
	ColorBasicSettings,
	ColorCubeLut,
	ColorCurvePoint,
	ColorCurveShapeKeyframe,
	ColorCurveShapeProperty,
	ColorCurvesSettings,
	ColorFilterApplication,
	ColorSecondaryCurve,
	ColorSecondaryCurveName,
	ColorSecondaryCurvesSettings,
	ColorGradeMaskSettings,
	ColorHslKeyframeProperty,
	ColorHslRangeName,
	ColorHslRangeSettings,
	ColorHslSettings,
	ColorKeyframeProperty,
	ColorLutSettings,
	ColorManagementSettings,
	ColorPropertyKeyframe,
	ColorSmartSettings,
	ColorSpace,
	ColorWheelKeyframeProperty,
	ColorWheelSettings,
	ColorWheelsSettings,
	MediaColorSettings,
	BlurIntensity,
	Scene,
	TProject,
	MediaType,
	TrackType,
	MediaElement,
	MediaBlendMode,
	MediaFitMode,
	MediaCrop,
	MediaPerspective,
	MediaKeyframeProperty,
	MediaPropertyKeyframe,
	MediaAnimationType,
	MediaComboAnimationType,
	ClipTransition,
	ClipTransitionDirection,
	ClipTransitionEasing,
	ClipTransitionType,
	MediaAdjustments,
	MediaMask,
	MediaMaskType,
	MediaMaskBlendMode,
	MediaMaskKeyframeProperty,
	MediaMaskPoint,
	MediaMaskStroke,
	MediaMaskStrokeStyle,
	MediaMaskTracking,
	MediaMaskTrackingDirection,
	MediaCustomCutout,
	MediaCustomCutoutBrushMode,
	MediaCustomCutoutPoint,
	MediaCustomCutoutStroke,
	MediaChromaKey,
	MediaChromaKeyKeyframeProperty,
	MediaEnhancements,
	AudioKeyframeProperty,
	AudioLoudnessSettings,
	AudioDenoiseSettings,
	AudioVoiceEnhanceSettings,
	AudioPitchSettings,
	AudioEqualizerSettings,
	AudioCompressorSettings,
	AudioLimiterSettings,
	AudioReverbSettings,
	AudioEchoSettings,
	AudioTelephoneSettings,
	AudioChannelMode,
	AudioParametricFilterType,
	AudioParametricEqBand,
	AudioParametricEqualizerSettings,
	AudioRepairSettings,
	AudioDuckingSettings,
	AudioAutoCrossfadeSettings,
	AudioCrossfade,
	AudioBusEffectsSettings,
	TimelineTrackAudioSettings,
	AudioMixBusSettings,
	ProjectAudioMixSettings,
	AudioStemName,
	AudioSeparationSettings,
	AudioVoiceConversionSettings,
	AudioCoverSettings,
	AudioLyricsWord,
	AudioLyricsSettings,
	MediaAudioSettings,
	TextElement,
	TextKeyframeProperty,
	TextPropertyKeyframe,
	StickerElement,
	CaptionElement,
	SubtitleStyle,
	RemotionElement,
	MarkdownElement,
	TimelineElement,
	CreateMediaElement,
	CreateTextElement,
	CreateStickerElement,
	CreateCaptionElement,
	CreateRemotionElement,
	CreateMarkdownElement,
	CreateTimelineElement,
	TimelineTrack,
	MediaItemDragData,
	TextItemDragData,
	StickerItemDragData,
	RemotionItemDragData,
	MarkdownItemDragData,
	DragData,
	TranscriptionSegment,
	TranscriptionResult,
	TranscriptionRequest,
	TranscriptionError,
	CaptionSegment,
	CaptionTrackData,
	TranscriptionStatus,
	TranscriptionProgress,
	CaptionFormat,
	CaptionExportOptions,
	AnimatedParameter,
	EffectChain,
	EffectInstance,
	EffectKeyframe,
	EffectParameters,
	EffectType,
} from "./types/index.js";

// Timeline utilities
export {
	sortTracksByOrder,
	normalizeTrackOrder,
	moveTrack,
	compareTrackTypePriority,
	buildCompositionPlan,
	getMainTrack,
	ensureMainTrack,
	getTrackName,
	createTrack,
	getEffectiveDuration,
	getElementEndTime,
	getElementNameWithSuffix,
	TRANSITION_SEAM_TOLERANCE_SECONDS,
	findClosestMediaSeam,
	getAudioCrossfadeMaxDuration,
	getTransitionMaxDuration,
	reconcileTrackAudioCrossfades,
	reconcileTimelineTransitions,
	reconcileTrackTransitions,
	resolveAudioCrossfade,
	resolveClipTransition,
	type ResolvedAudioCrossfade,
	isMediaElement,
	isTextElement,
	isStickerElement,
	isCaptionElement,
	isRemotionElement,
	isMarkdownElement,
	getRemotionElements,
	getActiveRemotionElements,
	canElementGoOnTrack,
	validateElementTrackCompatibility,
} from "./timeline/index.js";

export type {
	BuildCompositionPlanOptions,
	CompositionAudioElement,
	CompositionDurationContext,
	CompositionLayer,
	CompositionPlan,
	MediaSeam,
	ResolvedClipTransition,
} from "./timeline/index.js";

// Commands (history/undo-redo)
export {
	type HistoryState,
	createHistory,
	pushState,
	undo,
	redo,
	canUndo,
	canRedo,
	clearHistory,
} from "./commands/index.js";

// Storage interface
export type { EditorStorageProvider } from "./storage/index.js";

// Transcription persistence types
export type {
	PersistedTranscriptionWord,
	PersistedTranscriptionSegment,
	PersistedTranscription,
	TranscriptionAvailability,
} from "./types/index.js";

// Search
export {
	searchTranscriptions,
	type SearchResult,
	type SearchOptions,
} from "./search/index.js";

// Captions — shared subtitle utilities (CLI + renderer)
export {
	DEFAULT_SUBTITLE_STYLE,
	resolveSubtitleStyle,
	hexToRgba,
	rgbToASSColor,
	assColorToRgb,
	alignToASSAlignment,
	assAlignmentToAlign,
	generateASS,
	secondsToASSTime,
	parseASS,
	assTimeToSeconds,
	assStyleToSubtitleStyle,
	type ASSGeneratorOptions,
	type ASSStyle,
	type ASSEvent,
	type ASSDocument,
} from "./captions/index.js";

// Audio — beat detection engine
export {
	analyzeFromSamples,
	resolveConfig as resolveBeatConfig,
	type Beat,
	type BeatDetectionConfig,
	type BeatDetectionResult,
	type ResolvedBeatDetectionConfig,
} from "./audio/index.js";

// Utils
export { generateUUID } from "./utils.js";
