import type {
	JianyingPortraitAdjustmentCategory,
	JianyingPortraitAdjustmentControl,
	JianyingPortraitAdjustmentRuntimePackage,
	JianyingPortraitAdjustmentSection,
	MediaPortraitAdjustmentKey,
} from "../jianying-portrait-adjustment-contract.js";

function faceControl({
	key,
	section,
	category,
	runtimePackage,
	titleZh,
	titleEn,
	min = -50,
	max = 50,
}: {
	key: MediaPortraitAdjustmentKey;
	section: JianyingPortraitAdjustmentSection;
	category: JianyingPortraitAdjustmentCategory;
	runtimePackage: JianyingPortraitAdjustmentRuntimePackage;
	titleZh: string;
	titleEn: string;
	min?: number;
	max?: number;
}): JianyingPortraitAdjustmentControl {
	return {
		key,
		group: "face",
		section,
		category,
		runtimePackage,
		titleZh,
		titleEn,
		min,
		max,
		step: 1,
	};
}

export const JIANYING_PORTRAIT_ADVANCED_CONTROLS = [
	faceControl({
		key: "face_adjust_skin_Intensity",
		section: "skin",
		category: "skin",
		runtimePackage: "skin-tone",
		titleZh: "肤色",
		titleEn: "Skin tone",
		min: 0,
		max: 100,
	}),
	faceControl({
		key: "face_adjust_skin_ColdWarm",
		section: "skin",
		category: "skin",
		runtimePackage: "skin-tone",
		titleZh: "冷暖",
		titleEn: "Warmth",
	}),
	faceControl({
		key: "face_adjust_eye",
		section: "features",
		category: "eyes",
		runtimePackage: "features",
		titleZh: "眼睛大小",
		titleEn: "Eye size",
	}),
	faceControl({
		key: "face_adjust_eye_width",
		section: "features",
		category: "eyes",
		runtimePackage: "features",
		titleZh: "眼睛宽度",
		titleEn: "Eye width",
	}),
	faceControl({
		key: "face_adjust_eye_height",
		section: "features",
		category: "eyes",
		runtimePackage: "features",
		titleZh: "眼睛高度",
		titleEn: "Eye height",
	}),
	faceControl({
		key: "face_adjust_eye_position",
		section: "features",
		category: "eyes",
		runtimePackage: "features",
		titleZh: "眼睛高低",
		titleEn: "Eye position",
	}),
	faceControl({
		key: "face_adjust_eye_distance",
		section: "features",
		category: "eyes",
		runtimePackage: "features",
		titleZh: "眼距精修",
		titleEn: "Eye distance",
	}),
	faceControl({
		key: "face_adjust_pupil",
		section: "features",
		category: "eyes",
		runtimePackage: "features",
		titleZh: "瞳孔",
		titleEn: "Pupil",
	}),
	faceControl({
		key: "face_adjust_lower_eyelid",
		section: "features",
		category: "eyes",
		runtimePackage: "features",
		titleZh: "下眼睑",
		titleEn: "Lower eyelid",
	}),
	faceControl({
		key: "face_adjust_inner_corner",
		section: "features",
		category: "eyes",
		runtimePackage: "features",
		titleZh: "内眼角",
		titleEn: "Inner eye corner",
	}),
	faceControl({
		key: "face_adjust_outer_corner",
		section: "features",
		category: "eyes",
		runtimePackage: "features",
		titleZh: "外眼角",
		titleEn: "Outer eye corner",
	}),
	faceControl({
		key: "face_adjust_outer_corner_inout",
		section: "features",
		category: "eyes",
		runtimePackage: "features",
		titleZh: "外眼角内外",
		titleEn: "Outer corner depth",
	}),
	faceControl({
		key: "face_adjust_nose",
		section: "features",
		category: "nose",
		runtimePackage: "features",
		titleZh: "鼻子大小",
		titleEn: "Nose size",
	}),
	faceControl({
		key: "face_adjust_nose_bridge",
		section: "features",
		category: "nose",
		runtimePackage: "features",
		titleZh: "鼻梁",
		titleEn: "Nose bridge",
	}),
	faceControl({
		key: "face_adjust_nose_position",
		section: "features",
		category: "nose",
		runtimePackage: "features",
		titleZh: "鼻子高低",
		titleEn: "Nose position",
	}),
	faceControl({
		key: "face_adjust_nose_root",
		section: "features",
		category: "nose",
		runtimePackage: "features",
		titleZh: "山根",
		titleEn: "Nose root",
	}),
	faceControl({
		key: "face_adjust_nose_tip",
		section: "features",
		category: "nose",
		runtimePackage: "features",
		titleZh: "鼻尖",
		titleEn: "Nose tip",
	}),
	faceControl({
		key: "face_adjust_nose_wing",
		section: "features",
		category: "nose",
		runtimePackage: "features",
		titleZh: "鼻翼",
		titleEn: "Nose wing",
	}),
	faceControl({
		key: "face_adjust_mouse",
		section: "features",
		category: "mouth",
		runtimePackage: "features",
		titleZh: "嘴巴大小",
		titleEn: "Mouth size",
	}),
	faceControl({
		key: "face_adjust_mouse_width",
		section: "features",
		category: "mouth",
		runtimePackage: "features",
		titleZh: "嘴巴宽度",
		titleEn: "Mouth width",
	}),
	faceControl({
		key: "face_adjust_mouse_position",
		section: "features",
		category: "mouth",
		runtimePackage: "features",
		titleZh: "嘴巴高低",
		titleEn: "Mouth position",
	}),
	faceControl({
		key: "face_adjust_mouse_corner",
		section: "features",
		category: "mouth",
		runtimePackage: "features",
		titleZh: "嘴角精修",
		titleEn: "Mouth corners",
	}),
	faceControl({
		key: "face_adjust_upper_lip",
		section: "features",
		category: "mouth",
		runtimePackage: "features",
		titleZh: "上唇",
		titleEn: "Upper lip",
	}),
	faceControl({
		key: "face_adjust_under_lip",
		section: "features",
		category: "mouth",
		runtimePackage: "features",
		titleZh: "下唇",
		titleEn: "Lower lip",
	}),
	faceControl({
		key: "face_adjust_lip_line",
		section: "features",
		category: "mouth",
		runtimePackage: "features",
		titleZh: "唇线",
		titleEn: "Lip line",
	}),
	faceControl({
		key: "face_adjust_brow_ridge",
		section: "features",
		category: "brows",
		runtimePackage: "features",
		titleZh: "眉骨",
		titleEn: "Brow ridge",
	}),
	faceControl({
		key: "face_adjust_brow_size",
		section: "features",
		category: "brows",
		runtimePackage: "features",
		titleZh: "眉毛大小",
		titleEn: "Brow size",
	}),
	faceControl({
		key: "face_adjust_brow_position",
		section: "features",
		category: "brows",
		runtimePackage: "features",
		titleZh: "眉毛高低",
		titleEn: "Brow position",
	}),
	faceControl({
		key: "face_adjust_brow_tilt",
		section: "features",
		category: "brows",
		runtimePackage: "features",
		titleZh: "眉毛倾斜",
		titleEn: "Brow tilt",
	}),
	faceControl({
		key: "face_adjust_brow_width",
		section: "features",
		category: "brows",
		runtimePackage: "features",
		titleZh: "眉毛宽度",
		titleEn: "Brow width",
	}),
	faceControl({
		key: "face_adjust_brow_distance",
		section: "features",
		category: "brows",
		runtimePackage: "features",
		titleZh: "眉间距",
		titleEn: "Brow distance",
	}),
	faceControl({
		key: "face_adjust_BrightEye",
		section: "features",
		category: "details",
		runtimePackage: "eye-details",
		titleZh: "亮眼",
		titleEn: "Bright eyes",
		min: 0,
		max: 100,
	}),
	faceControl({
		key: "face_adjust_Pouch",
		section: "features",
		category: "details",
		runtimePackage: "eye-details",
		titleZh: "淡化眼袋",
		titleEn: "Reduce eye bags",
		min: 0,
		max: 100,
	}),
	faceControl({
		key: "face_adjust_NasolabialFolds",
		section: "features",
		category: "details",
		runtimePackage: "eye-details",
		titleZh: "淡化法令纹",
		titleEn: "Reduce smile lines",
		min: 0,
		max: 100,
	}),
] as const satisfies readonly JianyingPortraitAdjustmentControl[];
