import type { TextAnimationPresetDefinition } from "./types";

export const ENTRANCE_TEXT_ANIMATION_PRESETS = [
	{
		id: "none",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.none",
		previewKind: "none",
		defaultDuration: 0.6,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["none", "off", "无"],
	},
	{
		id: "typewriter-cursor",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterCursor",
		previewKind: "typewriter",
		defaultDuration: 1.4,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["typewriter", "cursor", "打字", "光标"],
	},
	{
		id: "fade-characters",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.fadeCharacters",
		previewKind: "fade",
		defaultDuration: 0.9,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["fade", "characters", "文字", "渐显"],
	},
	{
		id: "typewriter-leading",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterLeading",
		previewKind: "typewriter",
		defaultDuration: 1.1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["typewriter", "leading", "打字机"],
	},
	{
		id: "typewriter-i",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterI",
		previewKind: "typewriter",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["typewriter", "one", "打字机"],
	},
	{
		id: "typewriter-ii",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterII",
		previewKind: "typewriter",
		defaultDuration: 1.6,
		defaultDelay: 0,
		defaultIntensity: 0.75,
		searchTerms: ["typewriter", "soft", "two", "打字机"],
	},
	{
		id: "blur-slide-right-ii",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.blurSlideRightII",
		previewKind: "slide-right-blur",
		defaultDuration: 0.7,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["blur", "slide", "right", "向右", "模糊"],
	},
	{
		id: "rotate-fly-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.rotateFlyIn",
		previewKind: "rotate-fly",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["rotate", "fly", "旋转", "飞入"],
	},
	{
		id: "typewriter-preview",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterPreview",
		previewKind: "typewriter",
		defaultDuration: 1.8,
		defaultDelay: 0,
		defaultIntensity: 0.65,
		searchTerms: ["typewriter", "preview", "预览", "打字"],
	},
	{
		id: "typewriter-iv",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterIV",
		previewKind: "typewriter",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["typewriter", "fast", "four", "打字机"],
	},
	{
		id: "scale-up",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.scaleUp",
		previewKind: "scale",
		defaultDuration: 0.55,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["scale", "zoom", "放大"],
	},
	{
		id: "orbit-disappear",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.orbitDisappear",
		previewKind: "orbit",
		defaultDuration: 1.1,
		defaultDelay: 0,
		defaultIntensity: 0.85,
		searchTerms: ["orbit", "disappear", "环绕", "消失"],
	},
	{
		id: "cursor-typewriter",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.cursorTypewriter",
		previewKind: "typewriter",
		defaultDuration: 1.3,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["cursor", "typewriter", "光标", "打字"],
	},
	{
		id: "bounce-up",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.bounceUp",
		previewKind: "bounce-up",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["bounce", "up", "向上", "弹入"],
	},
	{
		id: "pop-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.popIn",
		previewKind: "pop",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 0.85,
		searchTerms: ["pop", "弹入"],
	},
	{
		id: "slide-up",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.slideUp",
		previewKind: "slide-up",
		defaultDuration: 0.65,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["slide", "up", "向上", "滑动"],
	},
	{
		id: "fade-text",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.fadeText",
		previewKind: "fade",
		defaultDuration: 0.7,
		defaultDelay: 0,
		defaultIntensity: 0.7,
		searchTerms: ["fade", "text", "淡入", "文字"],
	},
	{
		id: "laser-etch",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.laserEtch",
		previewKind: "laser",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["laser", "etch", "激光", "雕刻"],
	},
	{
		id: "heart-bounce",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.heartBounce",
		previewKind: "heart-bounce",
		defaultDuration: 0.9,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["heart", "bounce", "爱心", "弹跳"],
	},
	{
		id: "flip-open",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.flipOpen",
		previewKind: "flip",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["flip", "open", "unfold", "翻动", "翻开", "展开"],
	},
	{
		id: "typewriter-rhythm",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterRhythm",
		previewKind: "typewriter",
		defaultDuration: 1.4,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["typewriter", "rhythm", "human", "打字", "节奏", "人性化"],
	},
	{
		id: "rotate-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.rotateIn",
		previewKind: "rotate",
		defaultDuration: 0.75,
		defaultDelay: 0,
		defaultIntensity: 0.85,
		searchTerms: ["rotate", "in", "旋入"],
	},
] as const satisfies readonly TextAnimationPresetDefinition[];
