import type { TextAnimationPresetDefinition } from "./types";

export const EXIT_TEXT_ANIMATION_PRESETS = [
	{
		id: "none",
		phase: "exit",
		nameKey: "textProperties.animationPreset.none",
		previewKind: "none",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["none", "off", "无"],
	},
	{
		id: "fade-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.fadeOut",
		previewKind: "fade",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["fade", "out", "淡出"],
	},
	{
		id: "slide-down-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.slideDownOut",
		previewKind: "slide-down",
		defaultDuration: 0.55,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["slide", "down", "下滑", "出场"],
	},
	{
		id: "slide-right-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.slideRightOut",
		previewKind: "slide-right",
		defaultDuration: 0.55,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["slide", "right", "右滑", "出场"],
	},
	{
		id: "scale-down-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.scaleDownOut",
		previewKind: "scale",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 0.85,
		searchTerms: ["scale", "shrink", "缩小"],
	},
	{
		id: "orbit-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.orbitOut",
		previewKind: "orbit",
		defaultDuration: 0.9,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["orbit", "out", "环绕", "消失"],
	},
	{
		id: "blur-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.blurOut",
		previewKind: "blur",
		defaultDuration: 0.65,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["blur", "out", "模糊", "消失"],
	},
	{
		id: "rotate-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.rotateOut",
		previewKind: "rotate",
		defaultDuration: 0.65,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["rotate", "out", "旋出"],
	},
	{
		id: "typewriter-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.typewriterOut",
		previewKind: "typewriter",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["typewriter", "reverse", "打字", "消失"],
	},
	{
		id: "spiral-down",
		phase: "exit",
		nameKey: "textProperties.animationPreset.spiralDown",
		previewKind: "spiral-down",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["spiral", "corkscrew", "drop", "螺旋", "下降", "旋转"],
	},
	{
		id: "elastic-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.elasticOut",
		previewKind: "elastic-out",
		defaultDuration: 0.7,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["elastic", "stretch", "spring", "弹性", "伸缩", "弹簧"],
	},
	{
		id: "fly-up-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.flyUpOut",
		previewKind: "fly-up-out",
		defaultDuration: 0.6,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["fly", "up", "launch", "飞出", "向上", "上飞"],
	},
	{
		id: "flicker-scatter",
		phase: "exit",
		nameKey: "textProperties.animationPreset.flickerScatter",
		previewKind: "flicker-scatter",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["flicker", "scatter", "strobe", "闪烁", "散开", "碎散"],
	},
	{
		id: "random-fly-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.randomFlyOut",
		previewKind: "random-fly-out",
		defaultDuration: 0.7,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["random", "fly", "burst", "随机", "飞出", "四散"],
	},
	{
		id: "particle-shatter",
		phase: "exit",
		nameKey: "textProperties.animationPreset.particleShatter",
		previewKind: "particle-shatter",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["particle", "shatter", "dissolve", "粒子", "碎落", "溶解"],
	},
	{
		id: "shrink-shake",
		phase: "exit",
		nameKey: "textProperties.animationPreset.shrinkShake",
		previewKind: "shrink-shake",
		defaultDuration: 0.7,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["shrink", "shake", "tremble", "收缩", "震动", "颤缩"],
	},
] as const satisfies readonly TextAnimationPresetDefinition[];

export const LOOP_TEXT_ANIMATION_PRESETS = [
	{
		id: "none",
		phase: "loop",
		nameKey: "textProperties.animationPreset.none",
		previewKind: "none",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["none", "off", "无"],
	},
	{
		id: "pulse",
		phase: "loop",
		nameKey: "textProperties.animationPreset.pulse",
		previewKind: "pulse",
		defaultDuration: 1.5,
		defaultDelay: 0,
		defaultIntensity: 0.5,
		searchTerms: ["pulse", "脉冲"],
	},
	{
		id: "float",
		phase: "loop",
		nameKey: "textProperties.animationPreset.float",
		previewKind: "float",
		defaultDuration: 1.8,
		defaultDelay: 0,
		defaultIntensity: 0.5,
		searchTerms: ["float", "漂浮"],
	},
	{
		id: "bounce",
		phase: "loop",
		nameKey: "textProperties.animationPreset.bounce",
		previewKind: "bounce",
		defaultDuration: 1.1,
		defaultDelay: 0,
		defaultIntensity: 0.6,
		searchTerms: ["bounce", "弹跳"],
	},
	{
		id: "heartbeat",
		phase: "loop",
		nameKey: "textProperties.animationPreset.heartbeat",
		previewKind: "heartbeat",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 0.65,
		searchTerms: ["heartbeat", "heart", "心跳"],
	},
	{
		id: "rotate",
		phase: "loop",
		nameKey: "textProperties.animationPreset.rotateLoop",
		previewKind: "rotate",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 0.55,
		searchTerms: ["rotate", "spin", "旋转"],
	},
	{
		id: "sway",
		phase: "loop",
		nameKey: "textProperties.animationPreset.sway",
		previewKind: "rotate",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 0.6,
		searchTerms: ["sway", "swing", "pendulum", "摇摆", "钟摆"],
	},
	{
		id: "flip",
		phase: "loop",
		nameKey: "textProperties.animationPreset.flip",
		previewKind: "flip",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["flip", "turn", "horizontal", "翻转", "空间翻转", "水平"],
	},
	{
		id: "flip-3d",
		phase: "loop",
		nameKey: "textProperties.animationPreset.flip3D",
		previewKind: "flip",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["3d", "perspective", "flip", "三维", "透视", "翻转"],
	},
	{
		id: "cylinder-3d",
		phase: "loop",
		nameKey: "textProperties.animationPreset.cylinder3D",
		previewKind: "ring-orbit",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["3d", "cylinder", "carousel", "三维", "圆柱", "环绕"],
	},
	{
		id: "jitter-3d",
		phase: "loop",
		nameKey: "textProperties.animationPreset.jitter3D",
		previewKind: "jitter",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["3d", "jitter", "trail", "三维", "颤抖", "拖影"],
	},
	{
		id: "ring-orbit",
		phase: "loop",
		nameKey: "textProperties.animationPreset.ringOrbit",
		previewKind: "ring-orbit",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["orbit", "ring", "carousel", "环绕", "环形", "旋转"],
	},
	{
		id: "jitter",
		phase: "loop",
		nameKey: "textProperties.animationPreset.jitter",
		previewKind: "jitter",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["jitter", "shake", "step", "抖动", "颤抖", "分步"],
	},
	{
		id: "shimmer",
		phase: "loop",
		nameKey: "textProperties.animationPreset.shimmer",
		previewKind: "shimmer",
		defaultDuration: 1.4,
		defaultDelay: 0,
		defaultIntensity: 0.65,
		searchTerms: ["shimmer", "shine", "闪光"],
	},
	{
		id: "wave",
		phase: "loop",
		nameKey: "textProperties.animationPreset.wave",
		previewKind: "wave",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 0.6,
		searchTerms: ["wave", "波浪"],
	},
	{
		id: "flicker",
		phase: "loop",
		nameKey: "textProperties.animationPreset.flicker",
		previewKind: "flicker",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 0.55,
		searchTerms: ["flicker", "blink", "闪烁"],
	},
	{
		id: "breathe",
		phase: "loop",
		nameKey: "textProperties.animationPreset.breathe",
		previewKind: "breathe",
		defaultDuration: 2.2,
		defaultDelay: 0,
		defaultIntensity: 0.45,
		searchTerms: ["breathe", "breathing", "呼吸"],
	},
	{
		id: "vortex",
		phase: "loop",
		nameKey: "textProperties.animationPreset.vortex",
		previewKind: "vortex",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["vortex", "swirl", "doodle", "漩涡", "涡", "圆形涂鸦"],
	},
	{
		id: "pendulum",
		phase: "loop",
		nameKey: "textProperties.animationPreset.pendulum",
		previewKind: "pendulum",
		defaultDuration: 1.4,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["pendulum", "swing", "钟摆", "摆动", "摇摆"],
	},
	{
		id: "zoom-each",
		phase: "loop",
		nameKey: "textProperties.animationPreset.zoomEach",
		previewKind: "zoom-each",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["zoom", "each", "sequence", "逐字", "放大", "轮流"],
	},
	{
		id: "wave-squeeze",
		phase: "loop",
		nameKey: "textProperties.animationPreset.waveSqueeze",
		previewKind: "wave-squeeze",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["wave", "squeeze", "squash", "波浪", "挤压", "压扁"],
	},
	{
		id: "fold",
		phase: "loop",
		nameKey: "textProperties.animationPreset.fold",
		previewKind: "fold",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["fold", "flatten", "折叠", "对折", "翻折"],
	},
	{
		id: "arc-up",
		phase: "loop",
		nameKey: "textProperties.animationPreset.arcUp",
		previewKind: "arc-up",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["arc", "bow", "curve", "上弧", "弧形", "拱起"],
	},
	{
		id: "lucky-bag",
		phase: "loop",
		nameKey: "textProperties.animationPreset.luckyBag",
		previewKind: "lucky-bag",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["lucky", "coin", "burst", "福袋", "炸开", "金币"],
	},
] as const satisfies readonly TextAnimationPresetDefinition[];
