import type { TextAnimationPresetDefinition } from "./types";

export const EXIT_TEXT_ANIMATION_PRESETS = [
	{
		id: "none",
		phase: "exit",
		nameKey: "textProperties.animationPreset.none",
		previewKind: "none",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["none", "off", "无"],
	},
	{
		id: "fade-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.fadeOut",
		previewKind: "fade",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["fade", "out", "淡出"],
	},
	{
		id: "slide-down-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.slideDownOut",
		previewKind: "slide-down",
		defaultDuration: 0.55,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["slide", "down", "下滑", "出场"],
	},
	{
		id: "slide-right-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.slideRightOut",
		previewKind: "slide-right",
		defaultDuration: 0.55,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["slide", "right", "右滑", "出场"],
	},
	{
		id: "scale-down-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.scaleDownOut",
		previewKind: "scale",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 0.85,
		searchTerms: ["scale", "shrink", "缩小"],
	},
	{
		id: "orbit-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.orbitOut",
		previewKind: "orbit",
		defaultDuration: 0.9,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["orbit", "out", "环绕", "消失"],
	},
	{
		id: "blur-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.blurOut",
		previewKind: "blur",
		defaultDuration: 0.65,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["blur", "out", "模糊", "消失"],
	},
	{
		id: "rotate-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.rotateOut",
		previewKind: "rotate",
		defaultDuration: 0.65,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["rotate", "out", "旋出"],
	},
	{
		id: "typewriter-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.typewriterOut",
		previewKind: "typewriter",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["typewriter", "reverse", "打字", "消失"],
	},
	{
		id: "spiral-down",
		phase: "exit",
		nameKey: "textProperties.animationPreset.spiralDown",
		previewKind: "spiral-down",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["spiral", "corkscrew", "drop", "螺旋", "下降", "旋转"],
	},
	{
		id: "elastic-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.elasticOut",
		previewKind: "elastic-out",
		defaultDuration: 0.7,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["elastic", "stretch", "spring", "弹性", "伸缩", "弹簧"],
	},
	{
		id: "fly-up-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.flyUpOut",
		previewKind: "fly-up-out",
		defaultDuration: 0.6,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["fly", "up", "launch", "飞出", "向上", "上飞"],
	},
	{
		id: "flicker-scatter",
		phase: "exit",
		nameKey: "textProperties.animationPreset.flickerScatter",
		previewKind: "flicker-scatter",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["flicker", "scatter", "strobe", "闪烁", "散开", "碎散"],
	},
	{
		id: "random-fly-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.randomFlyOut",
		previewKind: "random-fly-out",
		defaultDuration: 0.7,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["random", "fly", "burst", "随机", "飞出", "四散"],
	},
	{
		id: "particle-shatter",
		phase: "exit",
		nameKey: "textProperties.animationPreset.particleShatter",
		previewKind: "particle-shatter",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["particle", "shatter", "dissolve", "粒子", "碎落", "溶解"],
	},
	{
		id: "shrink-shake",
		phase: "exit",
		nameKey: "textProperties.animationPreset.shrinkShake",
		previewKind: "shrink-shake",
		defaultDuration: 0.7,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["shrink", "shake", "tremble", "收缩", "震动", "颤缩"],
	},
	{
		id: "book-flip-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.bookFlipOut",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["book", "flip", "out", "立体翻书", "立体", "翻书"],
	},
	{
		id: "hearts-drift",
		phase: "exit",
		nameKey: "textProperties.animationPreset.heartsDrift",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["hearts", "drift", "爱心飘散", "爱心", "飘散"],
	},
	{
		id: "kitten-swallow",
		phase: "exit",
		nameKey: "textProperties.animationPreset.kittenSwallow",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["kitten", "swallow", "小猫吞字", "小猫", "吞字"],
	},
	{
		id: "scarecrow-harvest",
		phase: "exit",
		nameKey: "textProperties.animationPreset.scarecrowHarvest",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["scarecrow", "harvest", "稻草人收割"],
	},
	{
		id: "twist-dissolve",
		phase: "exit",
		nameKey: "textProperties.animationPreset.twistDissolve",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["twist", "dissolve", "扭曲消散", "扭曲", "消散"],
	},
	{
		id: "feather-erase-left",
		phase: "exit",
		nameKey: "textProperties.animationPreset.featherEraseLeft",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["feather", "erase", "left", "羽化向左擦除"],
	},
	{
		id: "feather-erase-right",
		phase: "exit",
		nameKey: "textProperties.animationPreset.featherEraseRight",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["feather", "erase", "right", "羽化向右擦除"],
	},
	{
		id: "ghost-swell",
		phase: "exit",
		nameKey: "textProperties.animationPreset.ghostSwell",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["ghost", "swell", "逐字虚影", "逐字", "虚影"],
	},
	{
		id: "ghost-trail-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.ghostTrailOut",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["ghost", "trail", "out", "叠影并出", "叠影", "并出"],
	},
	{
		id: "glow-blur-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.glowBlurOut",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["glow", "blur", "out", "发光模糊", "发光", "模糊"],
	},
	{
		id: "roll-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.rollOut",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["roll", "out", "滚出"],
	},
	{
		id: "wave-pop-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.wavePopOut",
		previewKind: "keyframes",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["wave", "pop", "out", "波浪弹出", "波浪", "弹出"],
	},
	{
		id: "wipe-bottom-right",
		phase: "exit",
		nameKey: "textProperties.animationPreset.wipeBottomRight",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["bottom", "right", "wipe", "右下擦除", "右下", "擦除"],
	},
	{
		id: "particle-dissolve",
		phase: "exit",
		nameKey: "textProperties.animationPreset.particleDissolve",
		previewKind: "particle-shatter",
		defaultDuration: 1.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["particle", "dissolve", "粒子消散", "粒子", "消散"],
	},
	{
		id: "slide-drop-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.slideDropOut",
		previewKind: "keyframes",
		defaultDuration: 1.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["slide", "and", "drop", "滑动下落", "滑动", "下落"],
	},
	{
		id: "spin-out-each",
		phase: "exit",
		nameKey: "textProperties.animationPreset.spinOutEach",
		previewKind: "keyframes",
		defaultDuration: 1.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["spin", "out", "逐字旋出", "逐字", "旋出"],
	},
	{
		id: "burst-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.burstOut",
		previewKind: "particle-shatter",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["burst", "explode", "炸开", "爆炸"],
	},
	{
		id: "two-stage-scale",
		phase: "exit",
		nameKey: "textProperties.animationPreset.twoStageScale",
		previewKind: "keyframes",
		defaultDuration: 1.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["scale", "two", "stage", "二段缩放", "二段", "缩放"],
	},
	{
		id: "lie-down",
		phase: "exit",
		nameKey: "textProperties.animationPreset.lieDown",
		previewKind: "keyframes",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["lie", "down", "fall", "躺下"],
	},
	{
		id: "whip-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.whipOut",
		previewKind: "keyframes",
		defaultDuration: 0.6,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["whip", "out", "甩回", "甩出"],
	},
	{
		id: "spin-scale-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.spinScaleOut",
		previewKind: "keyframes",
		defaultDuration: 1.6,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["spin", "scale", "rotate", "旋转缩放", "旋转", "缩放"],
	},
	{
		id: "wrap-slide-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.wrapSlideOut",
		previewKind: "keyframes",
		defaultDuration: 1.0,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["wrap", "slide", "out", "环绕滑出", "环绕", "滑出"],
	},
] as const satisfies readonly TextAnimationPresetDefinition[];

export const LOOP_TEXT_ANIMATION_PRESETS = [
	{
		id: "none",
		phase: "loop",
		nameKey: "textProperties.animationPreset.none",
		previewKind: "none",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["none", "off", "无"],
	},
	{
		id: "pulse",
		phase: "loop",
		nameKey: "textProperties.animationPreset.pulse",
		previewKind: "pulse",
		defaultDuration: 1.5,
		defaultDelay: 0,
		defaultIntensity: 0.5,
		searchTerms: ["pulse", "脉冲"],
	},
	{
		id: "float",
		phase: "loop",
		nameKey: "textProperties.animationPreset.float",
		previewKind: "float",
		defaultDuration: 1.8,
		defaultDelay: 0,
		defaultIntensity: 0.5,
		searchTerms: ["float", "漂浮"],
	},
	{
		id: "bounce",
		phase: "loop",
		nameKey: "textProperties.animationPreset.bounce",
		previewKind: "bounce",
		defaultDuration: 1.1,
		defaultDelay: 0,
		defaultIntensity: 0.6,
		searchTerms: ["bounce", "弹跳"],
	},
	{
		id: "heartbeat",
		phase: "loop",
		nameKey: "textProperties.animationPreset.heartbeat",
		previewKind: "heartbeat",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 0.65,
		searchTerms: ["heartbeat", "heart", "心跳"],
	},
	{
		id: "rotate",
		phase: "loop",
		nameKey: "textProperties.animationPreset.rotateLoop",
		previewKind: "rotate",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 0.55,
		searchTerms: ["rotate", "spin", "旋转"],
	},
	{
		id: "sway",
		phase: "loop",
		nameKey: "textProperties.animationPreset.sway",
		previewKind: "rotate",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 0.6,
		searchTerms: ["sway", "swing", "pendulum", "摇摆", "钟摆"],
	},
	{
		id: "flip",
		phase: "loop",
		nameKey: "textProperties.animationPreset.flip",
		previewKind: "flip",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["flip", "turn", "horizontal", "翻转", "空间翻转", "水平"],
	},
	{
		id: "flip-3d",
		phase: "loop",
		nameKey: "textProperties.animationPreset.flip3D",
		previewKind: "flip",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["3d", "perspective", "flip", "三维", "透视", "翻转"],
	},
	{
		id: "cylinder-3d",
		phase: "loop",
		nameKey: "textProperties.animationPreset.cylinder3D",
		previewKind: "ring-orbit",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["3d", "cylinder", "carousel", "三维", "圆柱", "环绕"],
	},
	{
		id: "jitter-3d",
		phase: "loop",
		nameKey: "textProperties.animationPreset.jitter3D",
		previewKind: "jitter",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["3d", "jitter", "trail", "三维", "颤抖", "拖影"],
	},
	{
		id: "ring-orbit",
		phase: "loop",
		nameKey: "textProperties.animationPreset.ringOrbit",
		previewKind: "ring-orbit",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["orbit", "ring", "carousel", "环绕", "环形", "旋转"],
	},
	{
		id: "jitter",
		phase: "loop",
		nameKey: "textProperties.animationPreset.jitter",
		previewKind: "jitter",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["jitter", "shake", "step", "抖动", "颤抖", "分步"],
	},
	{
		id: "shimmer",
		phase: "loop",
		nameKey: "textProperties.animationPreset.shimmer",
		previewKind: "shimmer",
		defaultDuration: 1.4,
		defaultDelay: 0,
		defaultIntensity: 0.65,
		searchTerms: ["shimmer", "shine", "闪光"],
	},
	{
		id: "wave",
		phase: "loop",
		nameKey: "textProperties.animationPreset.wave",
		previewKind: "wave",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 0.6,
		searchTerms: ["wave", "波浪"],
	},
	{
		id: "flicker",
		phase: "loop",
		nameKey: "textProperties.animationPreset.flicker",
		previewKind: "flicker",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 0.55,
		searchTerms: ["flicker", "blink", "闪烁"],
	},
	{
		id: "breathe",
		phase: "loop",
		nameKey: "textProperties.animationPreset.breathe",
		previewKind: "breathe",
		defaultDuration: 2.2,
		defaultDelay: 0,
		defaultIntensity: 0.45,
		searchTerms: ["breathe", "breathing", "呼吸"],
	},
	{
		id: "vortex",
		phase: "loop",
		nameKey: "textProperties.animationPreset.vortex",
		previewKind: "vortex",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["vortex", "swirl", "doodle", "漩涡", "涡", "圆形涂鸦"],
	},
	{
		id: "pendulum",
		phase: "loop",
		nameKey: "textProperties.animationPreset.pendulum",
		previewKind: "pendulum",
		defaultDuration: 1.4,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["pendulum", "swing", "钟摆", "摆动", "摇摆"],
	},
	{
		id: "zoom-each",
		phase: "loop",
		nameKey: "textProperties.animationPreset.zoomEach",
		previewKind: "zoom-each",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["zoom", "each", "sequence", "逐字", "放大", "轮流"],
	},
	{
		id: "wave-squeeze",
		phase: "loop",
		nameKey: "textProperties.animationPreset.waveSqueeze",
		previewKind: "wave-squeeze",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["wave", "squeeze", "squash", "波浪", "挤压", "压扁"],
	},
	{
		id: "fold",
		phase: "loop",
		nameKey: "textProperties.animationPreset.fold",
		previewKind: "fold",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["fold", "flatten", "折叠", "对折", "翻折"],
	},
	{
		id: "arc-up",
		phase: "loop",
		nameKey: "textProperties.animationPreset.arcUp",
		previewKind: "arc-up",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["arc", "bow", "curve", "上弧", "弧形", "拱起"],
	},
	{
		id: "lucky-bag",
		phase: "loop",
		nameKey: "textProperties.animationPreset.luckyBag",
		previewKind: "lucky-bag",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["lucky", "coin", "burst", "福袋", "炸开", "金币"],
	},
	{
		id: "color-bounce",
		phase: "loop",
		nameKey: "textProperties.animationPreset.colorBounce",
		previewKind: "color-bounce",
		defaultDuration: 1.6,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["color", "bounce", "tint", "变色", "弹跳", "彩色"],
	},
	{
		id: "glow-pulse",
		phase: "loop",
		nameKey: "textProperties.animationPreset.glowPulse",
		previewKind: "glow-pulse",
		defaultDuration: 1.6,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["glow", "pulse", "shine", "泛光", "发光", "辉光"],
	},
	{
		id: "doodle-boil-ii",
		phase: "loop",
		nameKey: "textProperties.animationPreset.doodleBoilIi",
		previewKind: "keyframes",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["doodle", "boil", "ii", "涂鸦手绘 II", "涂鸦", "手绘 II"],
	},
	{
		id: "graffiti-doodle",
		phase: "loop",
		nameKey: "textProperties.animationPreset.graffitiDoodle",
		previewKind: "keyframes",
		defaultDuration: 3,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["graffiti", "doodle", "涂鸦手绘", "涂鸦", "手绘"],
	},
	{
		id: "playful-wiggle",
		phase: "loop",
		nameKey: "textProperties.animationPreset.playfulWiggle",
		previewKind: "keyframes",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["playful", "wiggle", "调皮"],
	},
	{
		id: "rainbow-macaron",
		phase: "loop",
		nameKey: "textProperties.animationPreset.rainbowMacaron",
		previewKind: "color-bounce",
		defaultDuration: 5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["rainbow", "macaron", "彩虹-马卡龙"],
	},
	{
		id: "rainbow-mocha",
		phase: "loop",
		nameKey: "textProperties.animationPreset.rainbowMocha",
		previewKind: "color-bounce",
		defaultDuration: 5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["rainbow", "mocha", "彩虹"],
	},
	{
		id: "rainbow-new-year",
		phase: "loop",
		nameKey: "textProperties.animationPreset.rainbowNewYear",
		previewKind: "color-bounce",
		defaultDuration: 5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["rainbow", "new", "year", "彩虹-新年", "彩虹", "-新年"],
	},
	{
		id: "rainbow-valentine",
		phase: "loop",
		nameKey: "textProperties.animationPreset.rainbowValentine",
		previewKind: "color-bounce",
		defaultDuration: 5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["rainbow", "valentine", "彩虹-情人节"],
	},
	{
		id: "scream-shake",
		phase: "loop",
		nameKey: "textProperties.animationPreset.screamShake",
		previewKind: "keyframes",
		defaultDuration: 1.4,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["scream", "shake", "呐喊"],
	},
	{
		id: "space-flip-i",
		phase: "loop",
		nameKey: "textProperties.animationPreset.spaceFlipI",
		previewKind: "keyframes",
		defaultDuration: 1.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["space", "flip", "i", "空间翻转 I", "空间", "翻转 I"],
	},
	{
		id: "space-flip-ii",
		phase: "loop",
		nameKey: "textProperties.animationPreset.spaceFlipIi",
		previewKind: "keyframes",
		defaultDuration: 1.1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["space", "flip", "ii", "空间翻转 II", "空间", "翻转 II"],
	},
	{
		id: "space-flip-iii",
		phase: "loop",
		nameKey: "textProperties.animationPreset.spaceFlipIii",
		previewKind: "keyframes",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["space", "flip", "iii", "空间翻转 III", "空间", "翻转 III"],
	},
	{
		id: "wriggle",
		phase: "loop",
		nameKey: "textProperties.animationPreset.wriggle",
		previewKind: "jitter",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["wriggle", "扭动"],
	},
	{
		id: "alternating-scale",
		phase: "loop",
		nameKey: "textProperties.animationPreset.alternatingScale",
		previewKind: "keyframes",
		defaultDuration: 3,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["alternating", "scale", "交替缩放", "交替", "缩放"],
	},
	{
		id: "breathing-light",
		phase: "loop",
		nameKey: "textProperties.animationPreset.breathingLight",
		previewKind: "color-bounce",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["breathing", "light", "呼吸灯"],
	},
	{
		id: "one-by-one-reveal",
		phase: "loop",
		nameKey: "textProperties.animationPreset.oneByOneReveal",
		previewKind: "keyframes",
		defaultDuration: 3,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["reveal", "one", "by", "逐个显出", "逐个", "显出"],
	},
	{
		id: "strobe-outline",
		phase: "loop",
		nameKey: "textProperties.animationPreset.strobeOutline",
		previewKind: "keyframes",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["strobe", "outline", "频闪边框", "频闪", "边框"],
	},
	{
		id: "wave-glide",
		phase: "loop",
		nameKey: "textProperties.animationPreset.waveGlide",
		previewKind: "keyframes",
		defaultDuration: 3,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["wave", "glide", "波浪滑过", "波浪", "滑过"],
	},
	{
		id: "pulse-scale",
		phase: "loop",
		nameKey: "textProperties.animationPreset.pulseScale",
		previewKind: "keyframes",
		defaultDuration: 1.375,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["pulse", "scale", "放大缩小", "放大", "缩小"],
	},
	{
		id: "hold-stretch",
		phase: "loop",
		nameKey: "textProperties.animationPreset.holdStretch",
		previewKind: "keyframes",
		defaultDuration: 1.6,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["hold", "stretch", "pull", "拉住"],
	},
	{
		id: "throb",
		phase: "loop",
		nameKey: "textProperties.animationPreset.throb",
		previewKind: "keyframes",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["throb", "pulse", "悸动"],
	},
	{
		id: "strobe-flash",
		phase: "loop",
		nameKey: "textProperties.animationPreset.strobeFlash",
		previewKind: "keyframes",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["strobe", "flash", "blink", "爆闪"],
	},
] as const satisfies readonly TextAnimationPresetDefinition[];
