import type { TextAnimationPresetDefinition } from "./types";

export const EXIT_TEXT_ANIMATION_PRESETS = [
	{
		id: "none",
		phase: "exit",
		nameKey: "textProperties.animationPreset.none",
		previewKind: "none",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["none", "off", "无"],
	},
	{
		id: "fade-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.fadeOut",
		previewKind: "fade",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["fade", "out", "淡出"],
	},
	{
		id: "slide-down-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.slideDownOut",
		previewKind: "slide-down",
		defaultDuration: 0.55,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["slide", "down", "下滑", "出场"],
	},
	{
		id: "slide-right-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.slideRightOut",
		previewKind: "slide-right",
		defaultDuration: 0.55,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["slide", "right", "右滑", "出场"],
	},
	{
		id: "scale-down-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.scaleDownOut",
		previewKind: "scale",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 0.85,
		searchTerms: ["scale", "shrink", "缩小"],
	},
	{
		id: "orbit-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.orbitOut",
		previewKind: "orbit",
		defaultDuration: 0.9,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["orbit", "out", "环绕", "消失"],
	},
	{
		id: "blur-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.blurOut",
		previewKind: "blur",
		defaultDuration: 0.65,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["blur", "out", "模糊", "消失"],
	},
	{
		id: "rotate-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.rotateOut",
		previewKind: "rotate",
		defaultDuration: 0.65,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["rotate", "out", "旋出"],
	},
	{
		id: "typewriter-out",
		phase: "exit",
		nameKey: "textProperties.animationPreset.typewriterOut",
		previewKind: "typewriter",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["typewriter", "reverse", "打字", "消失"],
	},
] as const satisfies readonly TextAnimationPresetDefinition[];

export const LOOP_TEXT_ANIMATION_PRESETS = [
	{
		id: "none",
		phase: "loop",
		nameKey: "textProperties.animationPreset.none",
		previewKind: "none",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["none", "off", "无"],
	},
	{
		id: "pulse",
		phase: "loop",
		nameKey: "textProperties.animationPreset.pulse",
		previewKind: "pulse",
		defaultDuration: 1.5,
		defaultDelay: 0,
		defaultIntensity: 0.5,
		searchTerms: ["pulse", "脉冲"],
	},
	{
		id: "float",
		phase: "loop",
		nameKey: "textProperties.animationPreset.float",
		previewKind: "float",
		defaultDuration: 1.8,
		defaultDelay: 0,
		defaultIntensity: 0.5,
		searchTerms: ["float", "漂浮"],
	},
	{
		id: "bounce",
		phase: "loop",
		nameKey: "textProperties.animationPreset.bounce",
		previewKind: "bounce",
		defaultDuration: 1.1,
		defaultDelay: 0,
		defaultIntensity: 0.6,
		searchTerms: ["bounce", "弹跳"],
	},
	{
		id: "heartbeat",
		phase: "loop",
		nameKey: "textProperties.animationPreset.heartbeat",
		previewKind: "heartbeat",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 0.65,
		searchTerms: ["heartbeat", "heart", "心跳"],
	},
	{
		id: "rotate",
		phase: "loop",
		nameKey: "textProperties.animationPreset.rotateLoop",
		previewKind: "rotate",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 0.55,
		searchTerms: ["rotate", "spin", "旋转"],
	},
	{
		id: "sway",
		phase: "loop",
		nameKey: "textProperties.animationPreset.sway",
		previewKind: "rotate",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 0.6,
		searchTerms: ["sway", "swing", "pendulum", "摇摆", "钟摆"],
	},
	{
		id: "flip-3d",
		phase: "loop",
		nameKey: "textProperties.animationPreset.flip3D",
		previewKind: "flip-3d",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["3d", "flip", "horizontal", "三维", "翻转", "水平"],
	},
	{
		id: "cylinder-3d",
		phase: "loop",
		nameKey: "textProperties.animationPreset.cylinder3D",
		previewKind: "cylinder-3d",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["3d", "cylinder", "carousel", "圆柱", "环绕", "旋转"],
	},
	{
		id: "jitter-3d",
		phase: "loop",
		nameKey: "textProperties.animationPreset.jitter3D",
		previewKind: "jitter-3d",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["3d", "jitter", "shake", "trail", "抖动", "颤抖", "拖影"],
	},
	{
		id: "shimmer",
		phase: "loop",
		nameKey: "textProperties.animationPreset.shimmer",
		previewKind: "shimmer",
		defaultDuration: 1.4,
		defaultDelay: 0,
		defaultIntensity: 0.65,
		searchTerms: ["shimmer", "shine", "闪光"],
	},
	{
		id: "wave",
		phase: "loop",
		nameKey: "textProperties.animationPreset.wave",
		previewKind: "wave",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 0.6,
		searchTerms: ["wave", "波浪"],
	},
	{
		id: "flicker",
		phase: "loop",
		nameKey: "textProperties.animationPreset.flicker",
		previewKind: "flicker",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 0.55,
		searchTerms: ["flicker", "blink", "闪烁"],
	},
	{
		id: "breathe",
		phase: "loop",
		nameKey: "textProperties.animationPreset.breathe",
		previewKind: "breathe",
		defaultDuration: 2.2,
		defaultDelay: 0,
		defaultIntensity: 0.45,
		searchTerms: ["breathe", "breathing", "呼吸"],
	},
] as const satisfies readonly TextAnimationPresetDefinition[];
