import type { TextAnimationPresetDefinition } from "./types";

export const ENTRANCE_TEXT_ANIMATION_PRESETS = [
	{
		id: "none",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.none",
		previewKind: "none",
		defaultDuration: 0.6,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["none", "off", "无"],
	},
	{
		id: "typewriter-cursor",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterCursor",
		previewKind: "typewriter",
		defaultDuration: 1.4,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["typewriter", "cursor", "打字", "光标"],
	},
	{
		id: "fade-characters",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.fadeCharacters",
		previewKind: "fade",
		defaultDuration: 0.9,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["fade", "characters", "文字", "渐显"],
	},
	{
		id: "typewriter-leading",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterLeading",
		previewKind: "typewriter",
		defaultDuration: 1.1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["typewriter", "leading", "打字机"],
	},
	{
		id: "typewriter-i",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterI",
		previewKind: "typewriter",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["typewriter", "one", "打字机"],
	},
	{
		id: "typewriter-ii",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterII",
		previewKind: "typewriter",
		defaultDuration: 1.6,
		defaultDelay: 0,
		defaultIntensity: 0.75,
		searchTerms: ["typewriter", "soft", "two", "打字机"],
	},
	{
		id: "blur-slide-right-ii",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.blurSlideRightII",
		previewKind: "slide-right-blur",
		defaultDuration: 0.7,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["blur", "slide", "right", "向右", "模糊"],
	},
	{
		id: "rotate-fly-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.rotateFlyIn",
		previewKind: "rotate-fly",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["rotate", "fly", "旋转", "飞入"],
	},
	{
		id: "typewriter-preview",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterPreview",
		previewKind: "typewriter",
		defaultDuration: 1.8,
		defaultDelay: 0,
		defaultIntensity: 0.65,
		searchTerms: ["typewriter", "preview", "预览", "打字"],
	},
	{
		id: "typewriter-iv",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterIV",
		previewKind: "typewriter",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["typewriter", "fast", "four", "打字机"],
	},
	{
		id: "scale-up",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.scaleUp",
		previewKind: "scale",
		defaultDuration: 0.55,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["scale", "zoom", "放大"],
	},
	{
		id: "orbit-disappear",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.orbitDisappear",
		previewKind: "orbit",
		defaultDuration: 1.1,
		defaultDelay: 0,
		defaultIntensity: 0.85,
		searchTerms: ["orbit", "disappear", "环绕", "消失"],
	},
	{
		id: "cursor-typewriter",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.cursorTypewriter",
		previewKind: "typewriter",
		defaultDuration: 1.3,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["cursor", "typewriter", "光标", "打字"],
	},
	{
		id: "bounce-up",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.bounceUp",
		previewKind: "bounce-up",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["bounce", "up", "向上", "弹入"],
	},
	{
		id: "pop-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.popIn",
		previewKind: "pop",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 0.85,
		searchTerms: ["pop", "弹入"],
	},
	{
		id: "slide-up",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.slideUp",
		previewKind: "slide-up",
		defaultDuration: 0.65,
		defaultDelay: 0,
		defaultIntensity: 0.8,
		searchTerms: ["slide", "up", "向上", "滑动"],
	},
	{
		id: "fade-text",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.fadeText",
		previewKind: "fade",
		defaultDuration: 0.7,
		defaultDelay: 0,
		defaultIntensity: 0.7,
		searchTerms: ["fade", "text", "淡入", "文字"],
	},
	{
		id: "laser-etch",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.laserEtch",
		previewKind: "laser",
		defaultDuration: 1.2,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["laser", "etch", "激光", "雕刻"],
	},
	{
		id: "heart-bounce",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.heartBounce",
		previewKind: "heart-bounce",
		defaultDuration: 0.9,
		defaultDelay: 0,
		defaultIntensity: 0.9,
		searchTerms: ["heart", "bounce", "爱心", "弹跳"],
	},
	{
		id: "confetti-burst",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.confettiBurst",
		previewKind: "confetti-burst",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["confetti", "ribbon", "burst", "彩带", "喷射", "庆祝"],
	},
	{
		id: "flip-open",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.flipOpen",
		previewKind: "flip",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["flip", "open", "unfold", "翻动", "翻开", "展开"],
	},
	{
		id: "typewriter-rhythm",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.typewriterRhythm",
		previewKind: "typewriter",
		defaultDuration: 1.4,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["typewriter", "rhythm", "human", "打字", "节奏", "人性化"],
	},
	{
		id: "rotate-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.rotateIn",
		previewKind: "rotate",
		defaultDuration: 0.75,
		defaultDelay: 0,
		defaultIntensity: 0.85,
		searchTerms: ["rotate", "in", "旋入"],
	},
	{
		id: "fade-reveal",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.fadeReveal",
		previewKind: "fade",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["fade", "reveal", "rise", "淡入", "显现", "浮现"],
	},
	{
		id: "petal-wipe",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.petalWipe",
		previewKind: "petal-wipe",
		// The package ships animation_duration 0.5 s as its default.
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["petal", "wipe", "sweep", "blue", "蓝瓣", "划入", "蓝色"],
	},
	{
		id: "blue-glint-flash",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.blueGlintFlash",
		previewKind: "keyframes",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["blue", "glint", "flash", "蓝芒瞬烁", "蓝芒", "瞬烁"],
	},
	{
		id: "bunny-hop",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.bunnyHop",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["bunny", "hop", "兔子跳跃", "兔子", "跳跃"],
	},
	{
		id: "butterfly-weave",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.butterflyWeave",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["butterfly", "weave", "蝴蝶穿梭", "蝴蝶", "穿梭"],
	},
	{
		id: "confetti-particles",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.confettiParticles",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["confetti", "particles", "礼花粒子", "礼花", "粒子"],
	},
	{
		id: "ember-rise",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.emberRise",
		previewKind: "keyframes",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["ember", "rise", "焰尘上浮", "焰尘", "上浮"],
	},
	{
		id: "fan-spin",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.fanSpin",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["fan", "spin", "风扇旋转", "风扇", "旋转"],
	},
	{
		id: "firework-blast",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.fireworkBlast",
		previewKind: "keyframes",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["firework", "blast", "烟火炸旋", "烟火", "炸旋"],
	},
	{
		id: "flame-sweep",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.flameSweep",
		previewKind: "keyframes",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["flame", "sweep", "横掠焰光", "横掠", "焰光"],
	},
	{
		id: "free-growth",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.freeGrowth",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["free", "growth", "自由生长", "自由", "生长"],
	},
	{
		id: "gold-dust-drift",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.goldDustDrift",
		previewKind: "keyframes",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["gold", "dust", "drift", "金粉飘入", "金粉", "飘入"],
	},
	{
		id: "rainbow-rise",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.rainbowRise",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["rainbow", "rise", "彩虹渐变", "彩虹", "渐变"],
	},
	{
		id: "scroll-unfold",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.scrollUnfold",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["scroll", "unfold", "卷轴展开", "卷轴", "展开"],
	},
	{
		id: "starlight-flow",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.starlightFlow",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["starlight", "flow", "星光流转", "星光", "流转"],
	},
	{
		id: "teal-pull",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.tealPull",
		previewKind: "keyframes",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["teal", "pull", "青粒牵引", "青粒", "牵引"],
	},
	{
		id: "blur-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.blurIn",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["blur", "in", "模糊"],
	},
	{
		id: "color-mapping",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.colorMapping",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["color", "mapping", "彩色映射", "彩色", "映射"],
	},
	{
		id: "develop-reveal",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.developReveal",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["develop", "reveal", "逐字显影", "逐字", "显影"],
	},
	{
		id: "diagonal-wipe-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.diagonalWipeIn",
		previewKind: "keyframes",
		defaultDuration: 3,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["diagonal", "wipe", "in", "右下擦开", "右下", "擦开"],
	},
	{
		id: "elastic-stretch-ii",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.elasticStretchIi",
		previewKind: "keyframes",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["elastic", "stretch", "ii", "弹性伸缩 II", "弹性", "伸缩 II"],
	},
	{
		id: "feather-wipe-left",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.featherWipeLeft",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["feather", "wipe", "left", "羽化向左擦开"],
	},
	{
		id: "feather-wipe-right",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.featherWipeRight",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["feather", "wipe", "right", "羽化向右擦开"],
	},
	{
		id: "fly-in-down",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.flyInDown",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["fly", "in", "down", "向下飞入", "向下", "飞入"],
	},
	{
		id: "ghost-merge-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.ghostMergeIn",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["ghost", "merge", "in", "叠影并入", "叠影", "并入"],
	},
	{
		id: "ripple-karaoke",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.rippleKaraoke",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["ripple", "karaoke", "波纹 II"],
	},
	{
		id: "screen-rush",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.screenRush",
		previewKind: "keyframes",
		defaultDuration: 1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["screen", "rush", "冲屏位移", "冲屏", "位移"],
	},
	{
		id: "wave-bounce-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.waveBounceIn",
		previewKind: "keyframes",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["wave", "bounce", "in", "波浪弹入", "波浪", "弹入"],
	},
	{
		id: "blur-shrink",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.blurShrink",
		previewKind: "keyframes",
		defaultDuration: 1.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["blur", "shrink", "模糊缩小", "模糊", "缩小"],
	},
	{
		id: "candy-pop",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.candyPop",
		previewKind: "keyframes",
		defaultDuration: 1.267,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["popping", "candy", "跳跳糖"],
	},
	{
		id: "outline-typewriter",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.outlineTypewriter",
		previewKind: "typewriter",
		defaultDuration: 2,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["text", "outline", "文字描边", "文字", "描边"],
	},
	{
		id: "zoom-shake",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.zoomShake",
		previewKind: "keyframes",
		defaultDuration: 0.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["zoom", "shake", "放大震动", "放大", "震动"],
	},
	{
		id: "random-rise",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.randomRise",
		previewKind: "keyframes",
		defaultDuration: 1.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["random", "rise", "随机上升", "随机", "上升"],
	},
	{
		id: "random-gather",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.randomGather",
		previewKind: "keyframes",
		defaultDuration: 2.5,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["random", "gather", "随机集合", "随机", "集合"],
	},
	{
		id: "stand-up",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.standUp",
		previewKind: "keyframes",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["stand", "up", "rise", "站起"],
	},
	{
		id: "wave-bounce",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.waveBounce",
		previewKind: "keyframes",
		defaultDuration: 1.0,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["wave", "bounce", "波浪弹跳", "波浪", "弹跳"],
	},
	{
		id: "whip-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.whipIn",
		previewKind: "keyframes",
		defaultDuration: 0.9,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["whip", "swing", "甩出", "甩入"],
	},
	{
		id: "slide-pop-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.slidePopIn",
		previewKind: "keyframes",
		defaultDuration: 1.0,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["slide", "pop", "左移弹动", "左移", "弹动"],
	},
	{
		id: "flip-in-each",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.flipInEach",
		previewKind: "keyframes",
		defaultDuration: 2.0,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["flip", "each", "逐字翻转", "逐字", "翻转"],
	},
	{
		id: "spin-in-each",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.spinInEach",
		previewKind: "keyframes",
		defaultDuration: 2.0,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["spin", "rotate", "each", "逐字旋转", "逐字", "旋转"],
	},
	{
		id: "mischief-hop",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.mischiefHop",
		previewKind: "keyframes",
		defaultDuration: 1.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["hop", "bounce", "mischief", "跳跳捣蛋鬼", "跳跳", "捣蛋鬼"],
	},
	{
		id: "gather-right",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.gatherRight",
		previewKind: "keyframes",
		defaultDuration: 2.0,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["gather", "converge", "right", "向右集合", "向右", "集合"],
	},
	{
		id: "trail-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.trailIn",
		previewKind: "keyframes",
		defaultDuration: 0.8,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["trail", "diagonal", "渐变拖尾", "渐变", "拖尾"],
	},
	{
		id: "mosaic-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.mosaicIn",
		previewKind: "keyframes",
		defaultDuration: 2.0,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["mosaic", "pixel", "马赛克滑入", "马赛克", "滑入"],
	},
	{
		id: "glow-flicker-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.glowFlickerIn",
		previewKind: "keyframes",
		defaultDuration: 2.0,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["glow", "flicker", "neon", "发光闪入", "发光", "闪入"],
	},
	{
		id: "stroke-fill-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.strokeFillIn",
		previewKind: "keyframes",
		defaultDuration: 0.9,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["stroke", "outline", "fill", "描边填充", "描边", "填充"],
	},
	{
		id: "warp-blur-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.warpBlurIn",
		previewKind: "keyframes",
		defaultDuration: 2.0,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["warp", "blur", "distort", "扭曲模糊", "扭曲", "模糊"],
	},
	{
		id: "echo-trail-in",
		phase: "entrance",
		nameKey: "textProperties.animationPreset.echoTrailIn",
		previewKind: "keyframes",
		defaultDuration: 1.1,
		defaultDelay: 0,
		defaultIntensity: 1,
		searchTerms: ["echo", "trail", "zoom", "拖尾入场", "拖尾", "入场"],
	},
] as const satisfies readonly TextAnimationPresetDefinition[];
