import type { FilterPreset } from "../filter-types";

export const JIANYING_FILM_PARITY_FILTER_PRESETS: FilterPreset[] = [
	{
		id: "jy-nostalgia",
		version: 1,
		name: "Nostalgia",
		localizedName: "怀旧",
		category: "film",
		tags: ["film", "vintage", "复古", "胶片", "怀旧", "Nostalgia"],
		thumbnail: "/images/filter-previews/jy-nostalgia.webp",
		lutAssetId: "qcut/filter/jy-nostalgia/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.066,
			gamma: 1.039,
			blackLift: 0.085,
			shadowTint: [-0.011, 0.103, -0.008],
			highlightTint: [-0.236, -0.154, -0.24],
			temperature: 0.275,
			tint: 0.559,
			contrast: 1.071,
			saturation: 0.879,
			hueShift: -0.5,
			monochrome: 0.328,
			fade: 0.845,
		},
	},
	{
		id: "jy-old-time-frame",
		version: 1,
		name: "Old Time Frame",
		localizedName: "旧时光帧",
		category: "film",
		tags: ["film", "vintage", "复古", "胶片", "旧时光帧", "Old Time Frame"],
		thumbnail: "/images/filter-previews/jy-old-time-frame.webp",
		lutAssetId: "qcut/filter/jy-old-time-frame/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.119,
			gamma: 1.194,
			blackLift: -0.04,
			shadowTint: [0.199, 0.201, 0.091],
			highlightTint: [-0.187, -0.095, -0.301],
			temperature: -0.062,
			tint: 1.027,
			contrast: 0.435,
			saturation: 1.05,
			monochrome: 0.507,
			fade: 0.019,
		},
	},
	{
		id: "jy-retro-cinema",
		version: 1,
		name: "Retro Cinema",
		localizedName: "复古电影感",
		category: "film",
		tags: ["film", "vintage", "复古", "胶片", "复古电影感", "Retro Cinema"],
		thumbnail: "/images/filter-previews/jy-retro-cinema.webp",
		lutAssetId: "qcut/filter/jy-retro-cinema/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.259,
			blackLift: 0.212,
			shadowTint: [-0.311, -0.24, -0.35],
			highlightTint: [-0.236, 0.037, -0.055],
			temperature: 1.2,
			tint: 1.153,
			contrast: -0.081,
			saturation: 2.163,
			hueShift: -0.4,
			monochrome: 0.574,
			fade: 0.248,
		},
	},
	{
		id: "jy-vintage-portrait",
		version: 1,
		name: "Vintage Portrait",
		localizedName: "国民旧照",
		category: "film",
		tags: ["film", "vintage", "复古", "胶片", "国民旧照", "Vintage Portrait"],
		thumbnail: "/images/filter-previews/jy-vintage-portrait.webp",
		lutAssetId: "qcut/filter/jy-vintage-portrait/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: -0.206,
			gamma: 1.099,
			blackLift: 0.168,
			shadowTint: [-0.09, -0.35, -0.234],
			highlightTint: [0.34, 0.35, -0.35],
			temperature: 1.009,
			tint: 1.2,
			contrast: 0.056,
			saturation: 0.428,
			hueShift: 1.3,
			monochrome: 0.249,
			fade: 0.308,
		},
	},
	{
		id: "jy-amber",
		version: 1,
		name: "Amber",
		localizedName: "琥珀",
		category: "film",
		tags: ["film", "vintage", "复古", "胶片", "琥珀", "Amber"],
		thumbnail: "/images/filter-previews/jy-amber.webp",
		lutAssetId: "qcut/filter/jy-amber/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.03,
			gamma: 0.884,
			blackLift: 0.082,
			shadowTint: [-0.204, -0.12, -0.341],
			highlightTint: [-0.131, 0.132, 0.138],
			temperature: 1.2,
			tint: 1.2,
			contrast: 0.035,
			saturation: 0.777,
			hueShift: 2.4,
			monochrome: 0.028,
			fade: 0.49,
		},
	},
];
