import type { FilterPreset } from "../filter-types";
import { JIANYING_PORTRAIT_PARITY_FILTER_PRESETS } from "./portrait-presets";
import { JIANYING_LANDSCAPE_PARITY_FILTER_PRESETS } from "./landscape-presets";
import { JIANYING_FOOD_PARITY_FILTER_PRESETS } from "./food-presets";
import { JIANYING_CAMERA_PARITY_FILTER_PRESETS } from "./camera-presets";
import { JIANYING_FILM_PARITY_FILTER_PRESETS } from "./film-presets";
import { JIANYING_MONOCHROME_PARITY_FILTER_PRESETS } from "./monochrome-presets";
import { JIANYING_NIGHT_PARITY_FILTER_PRESETS } from "./night-presets";
import { JIANYING_OUTDOOR_PARITY_FILTER_PRESETS } from "./outdoor-presets";
import { JIANYING_STYLIZED_PARITY_FILTER_PRESETS } from "./stylized-presets";

export const JIANYING_PARITY_FILTER_PRESETS: FilterPreset[] = [
	...JIANYING_PORTRAIT_PARITY_FILTER_PRESETS,
	...JIANYING_LANDSCAPE_PARITY_FILTER_PRESETS,
	...JIANYING_FOOD_PARITY_FILTER_PRESETS,
	...JIANYING_CAMERA_PARITY_FILTER_PRESETS,
	...JIANYING_FILM_PARITY_FILTER_PRESETS,
	...JIANYING_MONOCHROME_PARITY_FILTER_PRESETS,
	...JIANYING_NIGHT_PARITY_FILTER_PRESETS,
	...JIANYING_OUTDOOR_PARITY_FILTER_PRESETS,
	...JIANYING_STYLIZED_PARITY_FILTER_PRESETS,
];
