import type { FilterPreset } from "../filter-types";

export const JIANYING_MONOCHROME_PARITY_FILTER_PRESETS: FilterPreset[] = [
	{
		id: "jy-mono-memory",
		version: 1,
		name: "Mono Memory",
		localizedName: "黑白记忆",
		category: "monochrome",
		tags: ["monochrome", "black and white", "黑白", "黑白记忆", "Mono Memory"],
		thumbnail: "/images/filter-previews/jy-mono-memory.webp",
		lutAssetId: "qcut/filter/jy-mono-memory/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.581,
			gamma: 0.582,
			blackLift: -0.25,
			shadowTint: [-0.35, -0.35, -0.246],
			highlightTint: [-0.35, 0.343, -0.35],
			temperature: 1.2,
			tint: 1.2,
			contrast: -0.348,
			saturation: 0.183,
			hueShift: 40,
			monochrome: 0.956,
			fade: 0.582,
		},
	},
	{
		id: "jy-jiangnan-mono",
		version: 1,
		name: "Jiangnan Mono",
		localizedName: "江浙沪",
		category: "monochrome",
		tags: ["monochrome", "black and white", "黑白", "江浙沪", "Jiangnan Mono"],
		thumbnail: "/images/filter-previews/jy-jiangnan-mono.webp",
		lutAssetId: "qcut/filter/jy-jiangnan-mono/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.409,
			gamma: 0.6,
			blackLift: -0.25,
			shadowTint: [-0.095, -0.103, -0.096],
			highlightTint: [-0.184, -0.018, -0.165],
			temperature: 0.265,
			tint: 1.2,
			contrast: -0.42,
			saturation: 0.572,
			hueShift: -2.5,
			monochrome: 0.254,
		},
	},
	{
		id: "jy-hd-mono",
		version: 1,
		name: "HD Mono",
		localizedName: "高清黑白",
		category: "monochrome",
		tags: ["monochrome", "black and white", "黑白", "高清黑白", "HD Mono"],
		thumbnail: "/images/filter-previews/jy-hd-mono.webp",
		lutAssetId: "qcut/filter/jy-hd-mono/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: -1.171,
			gamma: 1.62,
			blackLift: 0.233,
			shadowTint: [0.35, 0.291, -0.35],
			highlightTint: [0.35, 0.255, -0.35],
			temperature: 0.852,
			tint: 1.2,
			contrast: 2.924,
			saturation: 0.254,
			hueShift: -40,
			monochrome: 0.997,
		},
	},
	{
		id: "jy-forest-mountain",
		version: 1,
		name: "Forest Mountain",
		localizedName: "森山",
		category: "monochrome",
		tags: ["monochrome", "black and white", "黑白", "森山", "Forest Mountain"],
		thumbnail: "/images/filter-previews/jy-forest-mountain.webp",
		lutAssetId: "qcut/filter/jy-forest-mountain/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: -0.301,
			gamma: 1.037,
			blackLift: 0.096,
			shadowTint: [0.35, 0.35, -0.35],
			highlightTint: [0.35, -0.35, 0.35],
			temperature: 1.2,
			tint: 1.2,
			contrast: 2.711,
			saturation: 0.193,
			hueShift: -40,
			monochrome: 0.975,
		},
	},
	{
		id: "jy-blue-tone-mono",
		version: 1,
		name: "Blue Tone Mono",
		localizedName: "蓝调",
		category: "monochrome",
		tags: ["monochrome", "black and white", "黑白", "蓝调", "Blue Tone Mono"],
		thumbnail: "/images/filter-previews/jy-blue-tone-mono.webp",
		lutAssetId: "qcut/filter/jy-blue-tone-mono/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: -0.171,
			gamma: 1.386,
			blackLift: 0.202,
			shadowTint: [0.35, 0.257, -0.35],
			highlightTint: [-0.35, -0.35, 0.35],
			temperature: 1.2,
			tint: 1.2,
			contrast: 3,
			saturation: 0.131,
			hueShift: -24.4,
			monochrome: 0.819,
		},
	},
];
