import type { FilterPreset } from "../filter-types";

export const JIANYING_NIGHT_PARITY_FILTER_PRESETS: FilterPreset[] = [
	{
		id: "jy-night-dehaze",
		version: 1,
		name: "Night Dehaze",
		localizedName: "夜景去雾",
		category: "night",
		tags: ["night", "cityscape", "夜景", "夜景去雾", "Night Dehaze"],
		thumbnail: "/images/filter-previews/jy-night-dehaze.webp",
		lutAssetId: "qcut/filter/jy-night-dehaze/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.395,
			gamma: 0.599,
			blackLift: -0.089,
			shadowTint: [0.013, 0.072, 0.13],
			highlightTint: [-0.347, -0.076, 0.012],
			temperature: 0.583,
			tint: 0.204,
			contrast: 0.427,
			saturation: 1.165,
			hueShift: -0.3,
			monochrome: 0.176,
			fade: 0.78,
		},
	},
	{
		id: "jy-night-boost-ii",
		version: 1,
		name: "Night Boost II",
		localizedName: "夜景增色II",
		category: "night",
		tags: ["night", "cityscape", "夜景", "夜景增色II", "Night Boost II"],
		thumbnail: "/images/filter-previews/jy-night-boost-ii.webp",
		lutAssetId: "qcut/filter/jy-night-boost-ii/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.347,
			gamma: 0.536,
			blackLift: 0.081,
			shadowTint: [-0.35, -0.215, -0.202],
			highlightTint: [-0.35, -0.328, 0.093],
			temperature: 0.974,
			tint: -1.14,
			contrast: 0.04,
			saturation: 2.128,
			hueShift: -0.6,
			monochrome: 0.386,
			fade: 0.839,
		},
	},
	{
		id: "jy-urban-cinema-ii",
		version: 1,
		name: "Urban Cinema II",
		localizedName: "都市电影II",
		category: "night",
		tags: ["night", "cityscape", "夜景", "都市电影II", "Urban Cinema II"],
		thumbnail: "/images/filter-previews/jy-urban-cinema-ii.webp",
		lutAssetId: "qcut/filter/jy-urban-cinema-ii/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.274,
			gamma: 0.495,
			blackLift: 0.126,
			shadowTint: [0.013, -0.065, 0.05],
			highlightTint: [0.35, -0.35, -0.182],
			temperature: 0.772,
			tint: -1.028,
			contrast: 0.143,
			saturation: 0.711,
			hueShift: -4.9,
			monochrome: 0.438,
			fade: 0.011,
		},
	},
	{
		id: "jy-cool-fireworks",
		version: 1,
		name: "Cool Fireworks",
		localizedName: "冷烟花",
		category: "night",
		tags: ["night", "cityscape", "夜景", "冷烟花", "Cool Fireworks"],
		thumbnail: "/images/filter-previews/jy-cool-fireworks.webp",
		lutAssetId: "qcut/filter/jy-cool-fireworks/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: -0.06,
			gamma: 0.78,
			blackLift: 0.02,
			shadowTint: [-0.126, 0.159, 0.186],
			highlightTint: [-0.35, -0.149, 0.35],
			temperature: 1.2,
			tint: 0.646,
			contrast: 0.167,
			saturation: 1.501,
			hueShift: 5.5,
			monochrome: 0.485,
		},
	},
	{
		id: "jy-orange-teal",
		version: 1,
		name: "Orange Teal",
		localizedName: "橙蓝",
		category: "night",
		tags: ["night", "cityscape", "夜景", "橙蓝", "Orange Teal"],
		thumbnail: "/images/filter-previews/jy-orange-teal.webp",
		lutAssetId: "qcut/filter/jy-orange-teal/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.193,
			gamma: 0.749,
			blackLift: -0.059,
			shadowTint: [-0.341, -0.08, -0.27],
			highlightTint: [0.217, 0.35, 0.172],
			temperature: -0.119,
			tint: 1.2,
			contrast: -0.06,
			saturation: 1.61,
			hueShift: -9.2,
			fade: 0.974,
		},
	},
];
