import type { FilterPreset } from "../filter-types";

export const JIANYING_OUTDOOR_PARITY_FILTER_PRESETS: FilterPreset[] = [
	{
		id: "jy-stone-mountain",
		version: 1,
		name: "Stone Mountain",
		localizedName: "石山",
		category: "outdoor",
		tags: ["outdoor", "nature", "户外", "自然", "石山", "Stone Mountain"],
		thumbnail: "/images/filter-previews/jy-stone-mountain.webp",
		lutAssetId: "qcut/filter/jy-stone-mountain/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.261,
			gamma: 0.669,
			blackLift: 0.164,
			shadowTint: [-0.21, -0.099, -0.029],
			highlightTint: [-0.252, -0.23, -0.115],
			temperature: 0.413,
			tint: 0.267,
			contrast: 0.97,
			saturation: 0.879,
			monochrome: 0.11,
			fade: 0.886,
		},
	},
	{
		id: "jy-ice-falls",
		version: 1,
		name: "Ice Falls",
		localizedName: "冰瀑",
		category: "outdoor",
		tags: ["outdoor", "nature", "户外", "自然", "冰瀑", "Ice Falls"],
		thumbnail: "/images/filter-previews/jy-ice-falls.webp",
		lutAssetId: "qcut/filter/jy-ice-falls/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: -0.035,
			gamma: 0.973,
			blackLift: -0.031,
			shadowTint: [0.039, 0.319, 0.35],
			highlightTint: [-0.35, -0.086, 0.067],
			temperature: 0.006,
			tint: 1.2,
			contrast: 0.708,
			saturation: 1.008,
			monochrome: 0.426,
			fade: 0.242,
		},
	},
	{
		id: "jy-wildland",
		version: 1,
		name: "Wildland",
		localizedName: "旷野",
		category: "outdoor",
		tags: ["outdoor", "nature", "户外", "自然", "旷野", "Wildland"],
		thumbnail: "/images/filter-previews/jy-wildland.webp",
		lutAssetId: "qcut/filter/jy-wildland/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: -0.448,
			gamma: 1.708,
			blackLift: 0.005,
			shadowTint: [-0.164, 0.083, 0.068],
			highlightTint: [-0.321, -0.072, -0.02],
			temperature: 0.246,
			tint: 0.677,
			contrast: 1.016,
			saturation: 0.832,
			hueShift: 1.2,
			fade: 0.034,
		},
	},
	{
		id: "jy-rain-sky",
		version: 1,
		name: "Rain Sky",
		localizedName: "雨空",
		category: "outdoor",
		tags: ["outdoor", "nature", "户外", "自然", "雨空", "Rain Sky"],
		thumbnail: "/images/filter-previews/jy-rain-sky.webp",
		lutAssetId: "qcut/filter/jy-rain-sky/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: 0.274,
			gamma: 0.578,
			blackLift: -0.25,
			shadowTint: [-0.144, 0.222, 0.35],
			highlightTint: [0.039, 0.058, 0.258],
			temperature: -1.151,
			tint: 1.2,
			contrast: -0.147,
			saturation: 2.2,
			hueShift: 2.6,
			monochrome: 0.737,
			fade: 0.557,
		},
	},
	{
		id: "jy-offroad",
		version: 1,
		name: "Off-road",
		localizedName: "越野",
		category: "outdoor",
		tags: ["outdoor", "nature", "户外", "自然", "越野", "Off-road"],
		thumbnail: "/images/filter-previews/jy-offroad.webp",
		lutAssetId: "qcut/filter/jy-offroad/v1",
		defaultIntensity: 100,
		isNew: true,
		recipe: {
			exposure: -0.212,
			gamma: 1.152,
			blackLift: -0.026,
			shadowTint: [0.02, 0.102, 0.157],
			highlightTint: [-0.117, -0.029, -0.012],
			temperature: 0.202,
			tint: 0.69,
			contrast: 0.633,
			saturation: 0.848,
			hueShift: -1.7,
			monochrome: 0.01,
		},
	},
];
