import type { TransitionPreset } from "../transition-preset-types";
import { enginePresetFamily } from "./build-engine-preset-family";

const glassPresets = enginePresetFamily({
	clipType: "glass-refraction",
	type: "glass",
	variants: [
		{
			id: "glass-slice",
			name: "Glass Slice",
			localizedName: "玻璃切片",
			category: "distortion",
			direction: "left",
			intensity: 0.7,
			frequency: 1,
		},
		{
			id: "prism-bars",
			name: "Prism Bars",
			localizedName: "棱镜条纹",
			category: "light",
			direction: "right",
			intensity: 0.95,
			frequency: 1.6,
		},
		{
			id: "crystal-shift",
			name: "Crystal Shift",
			localizedName: "水晶偏移",
			category: "slideshow",
			direction: "up",
			intensity: 0.55,
			frequency: 0.7,
		},
		{
			id: "glass-pan",
			name: "Glass Pan",
			localizedName: "玻璃摇镜",
			category: "camera",
			direction: "down",
			intensity: 1.15,
			frequency: 1.2,
		},
		{
			id: "refraction-cut",
			name: "Refraction Cut",
			localizedName: "折射切镜",
			category: "shooting",
			direction: "left",
			intensity: 1.35,
			frequency: 2,
		},
		{
			id: "shard-sweep",
			name: "Shard Sweep",
			localizedName: "碎片扫过",
			category: "split",
			direction: "right",
			intensity: 1.6,
			frequency: 2.4,
		},
		{
			id: "kaleido-glass",
			name: "Kaleido Glass",
			localizedName: "万花玻璃",
			category: "variety",
			direction: "up",
			intensity: 1.8,
			frequency: 3,
		},
		{
			id: "neon-glass",
			name: "Neon Glass",
			localizedName: "霓虹玻璃",
			category: "glitch",
			direction: "down",
			intensity: 2,
			frequency: 3.6,
			tint: "#70f4ff",
		},
	],
});

const pageFlipPresets = enginePresetFamily({
	clipType: "page-flip",
	type: "page",
	variants: [
		{
			id: "page-flip-left",
			name: "Page Flip Left",
			localizedName: "向左翻页",
			category: "slideshow",
			direction: "left",
			intensity: 0.7,
		},
		{
			id: "page-flip-right",
			name: "Page Flip Right",
			localizedName: "向右翻页",
			category: "slideshow",
			direction: "right",
			intensity: 0.8,
		},
		{
			id: "page-flip-up",
			name: "Page Flip Up",
			localizedName: "向上翻页",
			category: "slideshow",
			direction: "up",
			intensity: 0.95,
		},
		{
			id: "page-flip-down",
			name: "Page Flip Down",
			localizedName: "向下翻页",
			category: "slideshow",
			direction: "down",
			intensity: 1.05,
		},
		{
			id: "card-turn",
			name: "Card Turn",
			localizedName: "卡片翻转",
			category: "mg",
			direction: "right",
			intensity: 1.2,
		},
		{
			id: "album-leaf",
			name: "Album Leaf",
			localizedName: "相册揭页",
			category: "slideshow",
			direction: "left",
			intensity: 0.55,
		},
		{
			id: "panel-fold",
			name: "Panel Fold",
			localizedName: "面板折叠",
			category: "split",
			direction: "up",
			intensity: 1.45,
		},
		{
			id: "poster-flip",
			name: "Poster Flip",
			localizedName: "海报翻转",
			category: "variety",
			direction: "down",
			intensity: 1.8,
		},
	],
});

export const GLASS_AND_PAGE_PRESETS: TransitionPreset[] = [
	...glassPresets,
	...pageFlipPresets,
];
